In [3]:
# ============================================================
# Data Exploration
# ============================================================

import json
import sys
import time
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path("../..").resolve()
sys.path.insert(0, str(PROJECT_ROOT))

In [29]:
import os

# Find where you are right now
print("Current directory:", os.getcwd())

# List everything in current folder
print("\nFiles here:")
for item in os.listdir('.'):
    print(item)

Current directory: /Users/pallavi_chandanshive/projects/clinical-summarization-eval/notebooks

Files here:
01_data_exploration.ipynb
02_workflow_1_direct_generation.ipynb
.ipynb_checkpoints

In [30]:
# Search for CSV files anywhere in your project
for root, dirs, files in os.walk('.'):
    # Skip venv folder
    if 'venv' in root:
        continue
    for file in files:
        if file.endswith('.csv'):
            print(os.path.join(root, file))

In [31]:
import pandas as pd

# Update these paths to match where your files are
notes = pd.read_csv('../data/raw/clinical_notes.csv')
patients = pd.read_csv('../data/raw/patients.csv')
admissions = pd.read_csv('../data/raw/admissions.csv')

In [32]:
# Basic shape
print("=== NOTES ===")
print(notes.shape)
print(notes.columns.tolist())
print(notes.head(2))

print("\n=== PATIENTS ===")
print(patients.shape)
print(patients.columns.tolist())

print("\n=== ADMISSIONS ===")
print(admissions.shape)
print(admissions.columns.tolist())

=== NOTES ===
(1602, 9)
['ingest_timestamp', 'clinical_note_id', 'clean_note_text', 'creation_timestamp', 'updt_dt_tm', 'note_subject', 'note_type', 'admission_id', 'person_id']
   ingest_timestamp                      clinical_note_id  \
0  07/01/2026 14:35  17bf845b-88f8-4604-8983-6e74453aada5
1  07/01/2026 14:50  e5d9c0a4-299a-425e-abbc-27fabe9cb742

                                     clean_note_text creation_timestamp  \
0  Patient Name: Judith Ada Wells\n- Patient ID: ...   07/01/2026 14:05
1  Patient reviewed at 14:20 on 07/01/26 by Nurse...   07/01/2026 14:20

         updt_dt_tm         note_subject note_type  \
0  07/01/2026 14:35            ED Triage        ED
1  07/01/2026 14:50  ED Triage Follow-Up        ED

                           admission_id                             person_id
0  63720303-3c1b-4356-befd-eea5438da62e  28570119-9cdc-4120-98c0-4edb76cf36a3
1  63720303-3c1b-4356-befd-eea5438da62e  28570119-9cdc-4120-98c0-4edb76cf36a3

=== PATIENTS ===
(69, 6)
['age', 'date_of_birth', 'full_name', 'gender_identity', 'nhs_number', 'person_id']

=== ADMISSIONS ===
(69, 15)
['admission_id', 'admission_method', 'admission_timestamp', 'admission_title', 'bed_location', 'date_of_birth', 'nhs_number', 'patient_id', 'patient_name', 'site_id', 'site_name', 'ward', 'full_name', 'first_name', 'surname']

In [33]:
print("\n=== NOTE TYPES ===")
print(notes['note_type'].value_counts())

=== NOTE TYPES ===
note_type
Orthopaedics Inpatients                      263
Physiotherapy Documentation                  262
Medicine Inpatients                          242
ED                                           155
Neurology Inpatients                         104
Therapies Inpatients                          81
Paediatrics Inpatients                        66
Anaesthetic Documentation                     62
Respiratory Inpatients                        62
ED Depart Summary                             39
Respiratory Medicine Inpatients               37
Pre-op Checklist                              35
Pre-op Consent                                31
Theatre notes                                 31
Neurosurgery Inpatients                       26
Orthopaedics Outpatients                      24
Occupational Therapy Documentation            24
Surgery Inpatients                            21
Dietetics Documentation                       14
Speech and Language Therapy Documentation      8
Surgery Outpatients                            6
Respiratory Therapy Documentation              2
Cardiology Inpatients                          2
Paediatric Respiratory Inpatients              2
Pediatrics Inpatients                          2
General Medicine Inpatients                    1
Name: count, dtype: int64

In [34]:
# How many notes per admission?
notes_per_admission = notes.groupby('admission_id')['clinical_note_id'].count()
print("\n=== NOTES PER ADMISSION ===")
print(notes_per_admission.describe())
print(notes_per_admission.value_counts().head(10))

# How many admissions per patient?
admissions_per_patient = admissions.groupby('patient_id')['admission_id'].count()
print("\n=== ADMISSIONS PER PATIENT ===")
print(admissions_per_patient.describe())
print(admissions_per_patient.value_counts().head(10))

=== NOTES PER ADMISSION ===
count    69.000000
mean     23.217391
std       8.709139
min      10.000000
25%      16.000000
50%      22.000000
75%      30.000000
max      45.000000
Name: clinical_note_id, dtype: float64
clinical_note_id
22    5
25    5
33    4
17    4
23    4
19    4
35    4
15    4
12    3
26    3
Name: count, dtype: int64

=== ADMISSIONS PER PATIENT ===
count    50.000000
mean      1.380000
std       0.490314
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       2.000000
Name: admission_id, dtype: float64
admission_id
1    31
2    19
Name: count, dtype: int64

In [35]:
# Pick first patient and show all their notes in order
first_patient = notes['person_id'].iloc[0]
patient_notes = notes[notes['person_id'] == first_patient].sort_values('creation_timestamp')

print(f"\n=== FULL JOURNEY FOR PATIENT {first_patient} ===")
for _, row in patient_notes.iterrows():
    print(f"\nDate: {row['creation_timestamp']}")
    print(f"Type: {row['note_type']}")
    print(f"Text preview: {str(row['clean_note_text'])[:200]}")
    print("---")

=== FULL JOURNEY FOR PATIENT 28570119-9cdc-4120-98c0-4edb76cf36a3 ===

Date: 07/01/2026 14:05
Type: ED
Text preview: Patient Name: Judith Ada Wells
- Patient ID: 28570119-9cdc-4120-98c0-4edb76cf36a3
- NHS Number: 272733208
- Date of Birth: 15/05/84 (39 years old)
- Gender: Female
- Allergies: NKA
- Current Medicatio
---

Date: 07/01/2026 14:20
Type: ED
Text preview: Patient reviewed at 14:20 on 07/01/26 by Nurse Chukwuebuka Okafor. Patient presented with a severe headache rated 8/10 in intensity. BP measured at 160/90 mmHg. HR recorded at 88 bpm. Brief neurologic
---

Date: 07/01/2026 14:45
Type: ED
Text preview: - Patient: Judith Ad a Wells, 39-year-old female, DOB: 15/05/84, NHS Number: 272733208.
 - Date/Time: 07/01/26, 14:45.
 - Staff involved: Nurse Jasmine Freda Murray.
 - Chief Complaint: Severe headach
---

Date: 07/01/2026 15:15
Type: ED
Text preview: Patient: Judith Ada Wells, 39-yer-old female, presenting with severe headache rated 8/10 in intensity after exertion. Current triage category: Category 2 (Urgent - potentially serious condition requir
---

Date: 07/01/2026 16:30
Type: ED Depart Summary
Text preview: Patient
Judith Ada Wells

Age
39

Sex
Female

NHS No.
272733208

Date/Time
07/01/26 16:30

Seen By
Dr. Victoria Ellen Holmes (with Dr. Rebecca Stephanie Norris, ED Consultant)

Presenting Complaint
Se
---

Date: 07/01/2026 17:00
Type: Neurology Inpatients
Text preview: Clerking Doctor
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

History of Presenting Complaint
Site: Generalised headache Onset: Sudden, described as 'thun
---

Date: 07/01/2026 18:30
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Kevin Richard Martin (Consultant), accompanied by Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

History of Presenting Com
---

Date: 07/01/2026 20:00
Type: Neurology Inpatients
Text preview: - Contacted patient's GP, Dr. Ethel Joanne Duffy, at 20:00 on 07/21/26.
- Provided update on admission and preliminary diagnosis of RCVS.
- No immediate changes to treatment plan following communicati
---

Date: 08/01/2026 10:00
Type: Medicine Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Confirmed by MR
---

Date: 08/01/2026 16:00
Type: Neurology Inpatients
Text preview: - Provided patient with educational materials on RCVS.
- Emphasised importance of avoiding triggers including intense physical exertion, stress, and medications such as triptans or ergotamines.
- Addr
---

Date: 09/01/2026 10:30
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Mild hyponatrem
---

Date: 09/01/2026 15:00
Type: Neurology Inpatients
Text preview: - Rehab team completed initial assessment of physical mobility and strength. - Mild residual neck stiffness noted; no significant functional impairments. - Decision made to arrange outpatient lhysio p
---

Date: 10/01/2026 09:15
Type: Medicine Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Diagnosis confi
---

Date: 10/01/2026 17:45
Type: Neurology Inpatients
Text preview: - Provided patient with discharge planning booklet covering RCVS management. - Reviewed booklet contents with the patient, including lifestyle modifications, warning signs, and follow-up card. - Patie
---

Date: 11/01/2026 08:45
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR), Dr. Glenn Robert Cartwright (Cons)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstrict
---

Date: 11/01/2026 10:30
Type: Neurology Inpatients
Text preview: - Repeat MRA performed at 10:30 on 11/01/26. Significant improvdment in cerebral vasoconstriction observed.
- Diagnosis of RCVS confirmed.
- Decision made to proceed with discharge planning on 12/01
---

Date: 12/01/2026 09:00
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Confirmed diagn
---

Date: 12/01/2026 12:00
Type: Neurology Inpatients
Text preview: - GP, Dr. Ethel Joanne Duffy, contacted by Nurse Jasmine Freda Murray on 12/01/26 at 12:00.
- Summary of patientâ€™s hospit al stay provided, including diagnosis of RCVS.
- Discharge medication (amlod
---

Date: 12/01/2026 13:30
Type: Medicine Inpatients
Text preview: - Contacted patient's GP, Dr. Ethel Joanne Duffy, to provide an update on discharge.
- OP follow-up arranged for 4 weeks.
- No changes to meds or treatment plan made during this event.
Nurse Jasmine
---

In [36]:
# Check duration of admissions
notes['creation_timestamp'] = pd.to_datetime(
    notes['creation_timestamp'], 
    format='%d/%m/%Y %H:%M',
    dayfirst=True
)

date_range = notes.groupby('admission_id')['creation_timestamp'].agg(['min', 'max'])
date_range['duration_days'] = (date_range['max'] - date_range['min']).dt.days

print("=== ADMISSION DURATION ===")
print(date_range['duration_days'].describe())

# Check patients with 2 admissions
admissions_per_patient = admissions.groupby('patient_id')['admission_id'].count()
two_admission_patients = admissions_per_patient[admissions_per_patient == 2].index.tolist()
print(f"\nPatients with 2 admissions: {len(two_admission_patients)}")

# Check note types for multi-admission patients
multi_notes = notes[notes['person_id'].isin(two_admission_patients)]
print(f"Total notes for multi-admission patients: {len(multi_notes)}")

# Find discharge summary note type
print("\n=== DISCHARGE SUMMARY NOTES ===")
discharge_notes = notes[notes['note_type'].str.contains('Depart|Discharge|Summary', 
                                                          case=False, na=False)]
print(f"Count: {len(discharge_notes)}")
print(discharge_notes['note_type'].value_counts())

=== ADMISSION DURATION ===
count    69.000000
mean      8.869565
std       6.216470
min       0.000000
25%       4.000000
50%       7.000000
75%      15.000000
max      20.000000
Name: duration_days, dtype: float64

Patients with 2 admissions: 19
Total notes for multi-admission patients: 988

=== DISCHARGE SUMMARY NOTES ===
Count: 39
note_type
ED Depart Summary    39
Name: count, dtype: int64

In [37]:
# First confirm column names in both tables
print("Notes columns:", notes.columns.tolist())
print("Admissions columns:", admissions.columns.tolist())

# Check if person_id and patient_id contain same values
print("\nSample person_id from notes:", notes['person_id'].iloc[0])
print("Sample patient_id from admissions:", admissions['patient_id'].iloc[0])

Notes columns: ['ingest_timestamp', 'clinical_note_id', 'clean_note_text', 'creation_timestamp', 'updt_dt_tm', 'note_subject', 'note_type', 'admission_id', 'person_id']
Admissions columns: ['admission_id', 'admission_method', 'admission_timestamp', 'admission_title', 'bed_location', 'date_of_birth', 'nhs_number', 'patient_id', 'patient_name', 'site_id', 'site_name', 'ward', 'full_name', 'first_name', 'surname']

Sample person_id from notes: 28570119-9cdc-4120-98c0-4edb76cf36a3
Sample patient_id from admissions: 28570119-9cdc-4120-98c0-4edb76cf36a3

In [38]:
import pandas as pd

admissions_per_patient = admissions.groupby('patient_id')['admission_id'].count()
two_admission_patients = admissions_per_patient[admissions_per_patient >= 2].index.tolist()
print(f"Patients with 2 admissions: {len(two_admission_patients)}")

Patients with 2 admissions: 19

In [39]:
multi_admission_with_gt = notes[
    (notes['person_id'].isin(two_admission_patients)) & 
    (notes['note_type'] == 'ED Depart Summary')
].groupby('person_id')['admission_id'].nunique()

both_admissions_have_gt = multi_admission_with_gt[
    multi_admission_with_gt == 2
].index.tolist()

print(f"Patients with ground truth for both admissions: {len(both_admissions_have_gt)}")

Patients with ground truth for both admissions: 10

In [40]:
# How many admissions do these 10 patients have total?
print(admissions[admissions['patient_id'].isin(both_admissions_have_gt)].groupby('patient_id')['admission_id'].count())

patient_id
04df53ea-55c1-48d9-84a1-1f15c133b29b    2
137b8481-4f1d-4b7f-babd-20f7117023ad    2
359014a1-10e6-4bd8-9ba7-513d021c971e    2
5e434d78-b2f6-4d88-b327-fff6ee50b901    2
61699d6d-904a-4ece-9026-cd61b3fd9a50    2
69bf7e25-abb2-4dde-857f-f1138d4d0d8a    2
8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc    2
c50e236f-6b3d-41c8-9e16-7ec343cac820    2
c6c45c39-cd73-49dd-818d-0a7865fe8a7f    2
ff8c4724-b7de-4189-bccf-cffddd4d6d44    2
Name: admission_id, dtype: int64

In [41]:
import json

with open('../data/patients/longitudinal_patient_ids.json', 'w') as f:
    json.dump(both_admissions_have_gt, f)

print(f"Saved {len(both_admissions_have_gt)} patient IDs")

Saved 10 patient IDs

In [42]:
# Basic counts from the notes table
print("Number of notes:", len(notes))
print("Number of patients:", notes["person_id"].nunique())
print("Number of admissions:", notes["admission_id"].nunique())

# Check whether each patient has one or multiple admissions
admissions_per_patient = (
    notes.groupby("person_id")["admission_id"]
    .nunique()
)

print("\nAdmissions per patient:")
print(admissions_per_patient.describe())

print("\nPatients with more than one admission:")
print((admissions_per_patient > 1).sum())


# Calculate approximate note length in words
notes["word_count"] = (
    notes["clean_note_text"]
    .fillna("")
    .str.split()
    .str.len()
)

print("\nNote length statistics:")
print(
    notes["word_count"].describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

Number of notes: 1602
Number of patients: 50
Number of admissions: 69

Admissions per patient:
count    50.000000
mean      1.380000
std       0.490314
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       2.000000
Name: admission_id, dtype: float64

Patients with more than one admission:
19

Note length statistics:
count    1602.000000
mean      129.997503
std        83.061291
min         1.000000
25%        60.250000
50%       124.500000
75%       174.000000
90%       228.900000
95%       280.000000
max       561.000000
Name: word_count, dtype: float64

In [43]:
notes_per_admission = (
    notes.groupby("admission_id")
    .size()
)

print("\nNotes per admission:")
print(
    notes_per_admission.describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

Notes per admission:
count    69.000000
mean     23.217391
std       8.709139
min      10.000000
25%      16.000000
50%      22.000000
75%      30.000000
90%      35.000000
95%      36.000000
max      45.000000
dtype: float64

In [44]:
longest_notes = notes.nlargest(10, "word_count")

for _, row in longest_notes.iterrows():
    print("=" * 80)
    print("Words:", row["word_count"])
    print("Subject:", row["note_subject"])
    print("Type:", row["note_type"])
    print()
    print(row["clean_note_text"])
    print()

================================================================================
Words: 561
Subject: Medical Clerking
Type: Neurology Inpatients

Clerking Doctor
Dr. Kelly Nicola Hayward (SpR)

Presenting Complaint
Acute confusion following minor fall

History of Presenting Complaint
- Pt reports tripping over a loose carpet edge at home earlier in the day (02/01/26)
- No LOC reported but recalls feeling dazed afterward
- Developed pprogressive confusion over the following hours
- Unable to remember recent events clearly
- Denies headache, visual changes, N&V, or limb weakness
- No reported CP, palpitations, or SOB

Review of Systems
- CNS: Mild confusion, denies heaadche, no visual disturbances, no speech difficulti es, no limb weakness, denies seizures
- CVS: Denies chest pain, palpitations, or syncope
- Resp: No breathlessness or cough
- GIT: No abdominal pain, nausea, vomiting, or changes in bowel habit
- Renal: No dysuria or haematuria
- MSK: Reports mild right knee pain following the fall
- Endo: No polyuria, polydipsia, or heat/cold intolerance
- Other: No recent fever or weight changes

Past Medical History
- HTN
- Mild osteoarthritis

Medications
- No regular medications
- IV paracetamol 1g QID prescribed during ED stay to manage pain and prevent discomfort

Allergies
None

Social History
- Lives alone in a ground-floor flat
- Independent with activities of daily living
- Retired accountant
- Non-smoker
- Drinks alcohol occasionally, approximately 6 units per week
- No recreational drug use

Family History
- Father: Deceased, history of MI at age 67
- Motherr: Deceased, history of HTN and stroke
- No known family history of neurodegenerative or psychiatric disorders

On Examination
- Alert but mildly confused, GCS 14/15 (disoriented to time)
- Appears dehydrated with dry mucous membranes
- No obvious signs of head trauma or external injuries
- Neurological examination:
   - Cranial nerves: Intact, pupils equal and reactive to light bilaterally
  - Motor: Normal power (5/5) in all limbs
  - Sensory: No deficits detected in light touch, pinprick, or vibratkion sensation
  - Reflexes: Normal and symmetrical in all limbs, plantar reflexes downgoing bilaterally
 - Coordination: No dysmetria or intention tremor on finger-nose testing
  - Gait: Unsteady, requires assistance to walk; no gross abnormalities in stance or heel-to-toe walking
- Cardiovascular: Heart sounds dual, no murmurs, no peripheral oedema
- Respiratory: Equal air entry bilaterally, no added sounds
- Abdomen: Soft, non-tender, no organomegaly
- No meningeal signs

Observations
HR 88
BP 142/86
RR 16
Temp 36.8
SpO2 98% on room air

Investigations
- CT head (02/01/26): DSubdural hygroma noted, no MLS
- No further imaging performed or currently planned

Test Results
- FB: Normal
- U&E: Mild hyponatremia (Na 132 mmol/L)
- CRP: Normal
- LFTs: Normal
- Coagulation profile: Normal
- Blood glucose: Normal
- Pending: None

Impression
Acute confusion secondary to subdural hygroma and mild hypoNa, likely exacerbated by dehydration

Plan
- Commence IV 0.9% sodium chloride, 1L over 8 hours, to correct dehydration and mild hyponatremia
- Prescribe IV paracetamol 1g QID to mnaage pain and prevent discomfort
- Continue monitoring neurological status with GCS assessments every 4 hours
- Repeat U&E in 24 hours to assess resposne to fluid resuscitation
- Ensure adequate oral hydration once IV fluids are discontinued
- Monitor for any progression of symptoms or development of focal neurological deficits
- Liaise with neurology team for ongoing care and management
- Document any further findings during the patientâ€™s stay

Admitting Consultant
Dr. Ismel Siddique (Neurology Consultant)


Dr. Kelly Nicola Hayward (Specialty Registrar)
GMC number: 1746274

================================================================================
Words: 537
Subject: Medical Clerking
Type: Medicine Inpatients

Clerking Doctor
Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion following minor fall.

History of Presenting Complaint
- Pt reports tripping over a loose rug at home yesterday evening (05/01/26) with a minor fall onto carpeted flooring, no LOC reported. - Initially felt wel but developed confusion later in the evening, described as difficulty recognising familiar objects and people. - No recol lection of the events leading to confusion. - Denies any vertigo, N&V, or CP. - Reports a mild R-sided headache that started after the fall, described as dull and persistent, rated 3/10 in severity, not worsening over time. - No limb weakness, visual disturbances, or incontinence reported.

Review of Systems
- CNS: Mild confusion, no focal neurological deficits, no seizures, no dysarthria.
- CVS: No chest pain, palpitations, or syncope.
- Resp: No shortness of breath, cough, or wheeze.
- GI: No nausea, vomiting, abdominal pain, or change in bowel habits.
- GU: No dysuria, haematuria, or incntinence.
- MSK: eports mild discomfort in the right hip area, no obvious swelling or deformity.
- Endocrine: No symptoms of hyperglycaemia or hypoglycaemia.

Past Medical History
- HTN
- OA
- TIA (2018)

Medications
Paracetamol 1g PRN every 6 hours for headache as prescribed in A&E.

Allergies
- Pollen

Social History
- Retired builder, lives alone in a bungalow.
- Independent with ADLs.
- Mobilises with a single walking stick due to OA affecting knees.
- Denies smoking or recreational drug use.
- Drinks aproximately 10 units of alcohol weekly (occasional beer).

Family History
- Father had a history of stroke in his 70s.
- Mother had HTN and osteoarthriti s.

On Examination
- Alert but mildly confused, disoriented to time (stated the incorrect year), oriented to place and person.
- Speech fluent, normal tone and volume.
- CNs intact.
- Power 5/5 in all muscle groups bilatreally.
- Sensation intact to light touch and pinprick in all limbs.
- Reflexes symmetrical in upper and lower limbs.
- Gait not assessed due to acute confusion.
- No scalp lacerations or haematomas observed.
- Mild tenderness over the right hip, no obvious swelling, deformity, or crepitus.
- Skin turgor slightly reduced; dry mucous membranes, indicating mild dehydration.
- No peripheral oedema or cyanosis.

Observations
HR 88
BP 160/95
RR 18
Temp 36.7
SpO2 96% on room air

Investigations
- T head: Subdural hygroma confirmed with no acute haemorrhage or mass effect.

Test Results
- Urea: 9.8 mmol/L
- All other blood test results within normal limits.

Impression
Subdural hygroma, mild dehydration, and acute confusion post minor fall. Suspected contributing factors include recent minor head trauma and possible suboptimal oral intake.

Plan
- Commence IV fluids: 0.9% sodium chloride 1L over 8 hours to address dehydration.
- Neudrological observations, including GCS monitooring and pupil responses.
- Monitor fluid input/output to assess hydration status.
- Repeat U&E tests in 24 hours.
- Prescribe paracetamol 1g PRN every 6 hours for headache as needed.
- Liaise with physio for mobility assessment when clinically appropriate.
- If confusion persists after rehydration, consider further cognitive assessment and liaise with psych if required.
- Reassess for any changes in neurological status; escalate to neurosurgery if indicated.


Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

================================================================================
Words: 537
Subject: Medical Clerking
Type: Medicine Inpatients

Clerking Doctor
Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion following minor fall.

History of Presenting Complaint
- Pt reports tripping over a loose rug at home yesterday evening (05/01/26) with a minor fall onto carpeted flooring, no LOC reported. - Initially felt wel but developed confusion later in the evening, described as difficulty recognising familiar objects and people. - No recol lection of the events leading to confusion. - Denies any vertigo, N&V, or CP. - Reports a mild R-sided headache that started after the fall, described as dull and persistent, rated 3/10 in severity, not worsening over time. - No limb weakness, visual disturbances, or incontinence reported.

Review of Systems
- CNS: Mild confusion, no focal neurological deficits, no seizures, no dysarthria.
- CVS: No chest pain, palpitations, or syncope.
- Resp: No shortness of breath, cough, or wheeze.
- GI: No nausea, vomiting, abdominal pain, or change in bowel habits.
- GU: No dysuria, haematuria, or incntinence.
- MSK: eports mild discomfort in the right hip area, no obvious swelling or deformity.
- Endocrine: No symptoms of hyperglycaemia or hypoglycaemia.

Past Medical History
- HTN
- OA
- TIA (2018)

Medications
Paracetamol 1g PRN every 6 hours for headache as prescribed in A&E.

Allergies
- Pollen

Social History
- Retired builder, lives alone in a bungalow.
- Independent with ADLs.
- Mobilises with a single walking stick due to OA affecting knees.
- Denies smoking or recreational drug use.
- Drinks aproximately 10 units of alcohol weekly (occasional beer).

Family History
- Father had a history of stroke in his 70s.
- Mother had HTN and osteoarthriti s.

On Examination
- Alert but mildly confused, disoriented to time (stated the incorrect year), oriented to place and person.
- Speech fluent, normal tone and volume.
- CNs intact.
- Power 5/5 in all muscle groups bilatreally.
- Sensation intact to light touch and pinprick in all limbs.
- Reflexes symmetrical in upper and lower limbs.
- Gait not assessed due to acute confusion.
- No scalp lacerations or haematomas observed.
- Mild tenderness over the right hip, no obvious swelling, deformity, or crepitus.
- Skin turgor slightly reduced; dry mucous membranes, indicating mild dehydration.
- No peripheral oedema or cyanosis.

Observations
HR 88
BP 160/95
RR 18
Temp 36.7
SpO2 96% on room air

Investigations
- T head: Subdural hygroma confirmed with no acute haemorrhage or mass effect.

Test Results
- Urea: 9.8 mmol/L
- All other blood test results within normal limits.

Impression
Subdural hygroma, mild dehydration, and acute confusion post minor fall. Suspected contributing factors include recent minor head trauma and possible suboptimal oral intake.

Plan
- Commence IV fluids: 0.9% sodium chloride 1L over 8 hours to address dehydration.
- Neudrological observations, including GCS monitooring and pupil responses.
- Monitor fluid input/output to assess hydration status.
- Repeat U&E tests in 24 hours.
- Prescribe paracetamol 1g PRN every 6 hours for headache as needed.
- Liaise with physio for mobility assessment when clinically appropriate.
- If confusion persists after rehydration, consider further cognitive assessment and liaise with psych if required.
- Reassess for any changes in neurological status; escalate to neurosurgery if indicated.


Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

================================================================================
Words: 523
Subject: Medical Clerking
Type: Medicine Inpatients

Clerking Doctor
Dr. Joanna Naomi Burgess (SpR)

Presenting Complaint
Acute confusion

History of Presenting Complaint
- Patient reported by her son, Edward Ali, to have been increasingly confused over the past 3 days.
- No history of head trauma or recent travel.
- Associated symptoms include reduced oral intake, decreased mobility, and lethargy.
- No reported hallucinations, visual changes, or seizures.
- No complaints of dysuria, urinary frequency, or visible haematuria as per sonâ€™s account.
- No chest pain, cough, or SOB noted prior to presentation.
- No history of vomiting or diarhoea.

Review of Systems
- Cardiovascular: No palpitations, chest pain, or syncope.
- Respiratory: No SOB or cough.
- Gastrointestinal: No abdominal pain, nausea, or vomiting. No changes in bowel habits.
- Genitourinary: No dysuria or visible haematuria. Reduced urinary output reported.
- Neurological: Acute confusion noted. No focal neuroklogical deficits (FND) reported by the son.
- Musculoskeletal: No recent falls or new joint pains.
- Dermatological: No rashes or skin changes.

Past Medical History
- HTN
- Osteoarthritis
- Cataract surgery (LE)

Medications
- None currently prescribed

Allergies
No known drug allergies

Social History
- Livesalone with support from her son, who visits daily.
- Mobilises with a frame indoors and uses a walking stick outdoors.
- Independent with most ADLs but requires assistance with shopping and heavier household tasks.
- Non-smoker and no alcohol consumption.
- No recreational drug use.

Family History
- No family history of dementia or neurological disorders.
- Father had IHD diagnosed in his 60s.
- Mother had OA.

On Examination
- Alert but disoriented to time, place, and person.
- Appears frail and dehydrated.
- Neurological: GCS 13/15 (E4, V4, M5). No focal neurological defiicts. Pupils equal and reactive to light. No limb weakness or tremors.
- Abdominal: Soft, non-tender, no organomegaly or palpable masses. No evidence of bladder distension.
- Hydration: Dry mucous membranes and reduced skin turgor.
- Musculoskeletal: Generalised joint stiffness consistent with known OA. No swelling or erythema in joints. Reduced mobility noted.
- General: No peripheral oedema. No obvious signs of infection such as rashes or erythema.

Observations
HR 112
BP 96/60
RR 18
Temp 38.8
SpO2 96% on room air

Investigations
- CXR: No focal consolidation or abnormalities detected.
- Awaiting urine C&S results.
- Bloods: Elevated CRP (120 mg/L). Creatinine 145 Âµmol/L, consistent with mild AKI.
- Urinalysis: Positive for leukocytes and nitrites, suggesting UTI.
- FBC: Mild leucocytosis.
- U&Es: Elevated urea and creatinine, borderline sodium levels.
- LFTs: Normal.
- Blood glucose: Normal.

Impression
Delirium likely secondary to UTI, with associated dehydration and mild AKI.

Plan
- Start IVceftriaxone 1g daily for suspected UTI as per ED decision.
- Transition to IV cefuroxime 750 mg TDS for continued treatment of UTI after admission.
- Commence IV 0.9% sodium chloride 1 litre over 8 hours for rehydration.
- Monitor renal function daily.
- Repeat urinalysis and send for C&S if required.
- Liaise with the geriatric team for further assessment and management of delirium.
- Mobilisation support with physiotherapy if needed.
- Encourage oral intake as tolerated.


Dr. Joanna Naomi Burgess (Specialty Registrar)
GMC number: 1346744

================================================================================
Words: 447
Subject: Medical Clerking
Type: Paediatric Respiratory Inpatients

Clerking Doctor
Dr. Anika Hossain (SpR)

Presenting Complaint
Wheeze

History of Presenting Complaint
- Lei Zhao reports a 3-day history of worsening wheeze and SOB.
- Symptoms began gradually and progressively worsened.
- Associated with increased coughing and a sensation of chest tightnewss.
- Symptoms developed shortly after contracting a cold with nasal congestion and sore throat.
- No associated fever, CP, or haemoptysis.
- No vomiting or abdominal pain.

Review of Systems
- Respiratory: Persistent wheeze, SOB, no haenoptysis or pleuritic chest pain.
- Cardiovascular: No palpitations, syncope, or chest pain.
- Gastrointestinal: No nausea, vomiting, abdo pain, or diarrhoea.
- Neurological: No headaches, dizziness, or focal neurologica l symptoms.
- Genitourinary: No dysuria, haematuria, or flank pain.
- ENT: Recent nasal congestion and sore throat, no ear pain or hearing loss.
- Musculoskeletal: No joint pain or swelling.
- Dermatological: No rashes or skin changes.

Past Medical History
- Asthma
- Seasonal allergies

Medications
None

Allergies
- Sulfonamides

Social History
- Lives with parents and attends secondary school.
- Independent with ADLs.
- Denies smoking, alcohol, or recreational drug use.
- Active lifestyle with regular participation in sports but unable to engage in physical actviity over the past 3 days due to symptoms.

Family History
- Mother has asthma.
- No known FH of other respiratory or chronic illnesses.

On Examination
- General appearance: Alert but in moderate respiratory distress, sitting upright in bed.
- Respiratory: Moderate use of accessory muscles, reduced chest expansion bilaterally, persistent expiratory wheeze on auscultation, no crackles, no signs of cyanosis. Peak flow measured at 180 L/min.
- ENT: Mild nasal congestion noted, oropharynx mildly erythematous with no exudates.
- CVS: Heart sounds norkal, no murmurs or added sounds.
- Abdomen: Soft, non-tender, no organomegaly.
- Neuro: Alert and oriented, no focal neurological deficits.

Observations
HR 96
BP 112/68
RR 24
Temp 36.8
SpO2 93% on 2L oxygen via nasal cannula

Investigations
- CXR requested to exclude infection or pneumothorax.
- ABG results from A&E: pH 7.32, PaO2 9.8 kPa, PaCO2 6.2 kPa, consistent with mild respiratory acidosis.

Test Results
- ABG: pH 7.32, mild respiratory acidosis.
- PEF: 180 L/min, indicating severe airway obstruction.

Impression
Acute exacerbation of asthma, likely triggered by a recent upper respiratory tract infection (URTI).

Plan
- Administer IV hydrocortisone 100 mg Q6H to manage acute asthma exacerbation and discontinu e oral prednisolone.
- Continue nebulised salbutamol 2.5 mg Q4H.
- Continue nebulised ipratropium bromide 500 mcg Q6H.
- Maintain oxygentherapy via nasal cannula to target SpO2 >94%.
- Perform CXR to exclude infection or pneumothorax.
- Monitor clinical response and reassess PEF and ABGs as indicated.


Dr. Anika Hossain (Specialty Registrar)
GMC number: 1812838

================================================================================
Words: 444
Subject: Pre-op Assessment
Type: Surgery Outpatients

Pre-clerking Doctor
Dr. Lewis Joe Lamb (FY1)

Presenting Complaint
Severe left hip pain due to end-stage OA.

Procedure
Total left hip replacement

History of Presenting Complaint
Site: L hip Onset: Gradual overthe past 4 yrs, progressively worsening Character: Deep, aching pain Radiates: Occasionally radiates to the L thigh Associations: Stiffness, reduced ROM, difficulty walking Timing: Constant pain, worse at night and after prolonged activity Exacerbating factors: Weight-bearing activities, prolonged standing or walking Severity: 8/10 at worst, 4/10 at best with analgesics

Past Medical History
- HTN
- Hyperlipidemia
- Mild osteopenia

Medications
- Paracetamol 500mg twice daily
- Ibuprofen 400mg as needed

Allergies
No known drug allergies

Social History
- Lives in a bungalow with her partner
- Independent in activities of daily living (ADLs) but uses a walking stick for mobility
- Non-smoker
- Drinks 6-8 units of alcohol per week
- No recreational drug use
- Retired school teacher
- Engages in light stretchnig exercises but has significantly reduced activity levels due to hip pain

Family History
- Mother had HTN and osteoarthritis
- Father had type 2 diabetes and HLD

On Examination
- Patient appeared comfortable at rest but had a slightly antalgic gait due to left hip pain
- CVS: Normal heart sounds, no murmurs, no peripheral oedema
- Resp: Clear breath sounds bilaterally, no wheeze or crackles
- Abdo: Soft, non-tender, no organomegaly, normal bowel sounds
- MSK: Left hip joint tender to palpation, reduced ROM (especially internaland external rotation), mild muscle wasting noted in the left thigh. No effusion or erythema
- Neruo: Normal tone, power 4/5 in left lower limb due to pain, normal reflexes, intact sensation in both lower limbs

Observations
HR 78
BP 145/90
RR 16
Temp 36.8
SpO2 98%

Investigations
- ECG: Normal sinus rhythm, no evidence of ischaemia or arrhythmia
- Urinalysis: Normal, no evidence of infection or other abnormalities
- Blood tests as part of routine pre-operative investigations revealed mild anaemia (Hb 10.8 g/dL). Other results including renal and liver function tests were within normal limits.

Test Results
- Bloods: Mild anaemia (Hb 10.8 g/dL), other results including renal and LFTs within normal limits
- Pending: None

Plan

In [4]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

In [5]:
import sys

sys.path.insert(0, str(PROJECT_ROOT))
notes = pd.read_csv(DATA_DIR / "raw" / "clinical_notes.csv")
print("Original notes:", len(notes))
print(notes.columns.tolist())
print("Notes:", notes.shape)

Original notes: 1602
['ingest_timestamp', 'clinical_note_id', 'clean_note_text', 'creation_timestamp', 'updt_dt_tm', 'note_subject', 'note_type', 'admission_id', 'person_id']
Notes: (1602, 9)

In [8]:
# ============================================================
# SELECT PILOT PATIENTS BY LONGITUDINAL RECORD SIZE
#
# Restrict selection to the longitudinal cohort:
# patients with >= 2 admissions and ground truth for both.
# ============================================================

# ============================================================
# RECORD SIZE PER PATIENT
# ============================================================

patient_sizes = (
    notes
    .groupby("person_id")
    .size()
    .reset_index(name="note_count")
    .sort_values("note_count")
    .reset_index(drop=True)
)

display(patient_sizes)

print("\nNote-count distribution:")
print(patient_sizes["note_count"].describe())

                               person_id  note_count
0   c87e610e-ac2a-48cf-ac32-054f3e595498          10
1   58b8aad6-7327-4450-956f-b775be0f4984          11
2   96766f3f-aa50-4bcb-abbf-884328049ea9          11
3   a8629d2e-7fd8-449a-9149-e0f5045a04c4          12
4   f97ee974-67f3-4d72-9ed4-f17025da3749          13
5   c54a9649-495a-4f89-a8ca-fbb14ba70ca6          14
6   900efb9a-fb57-4f25-b2a3-0a8c6f55b2d6          15
7   028998ee-babc-4096-9b28-001bc2f9a84e          15
8   0f438665-d430-4adb-8acc-c3beed9e4942          15
9   f1538231-21af-4cfa-8b40-3303aa0d0c96          15
10  fc6268ab-ad15-4613-9d8d-12c045e2fd46          16
11  b8085350-6748-47a5-a12f-6acd07c40a82          16
12  1dbe23dc-0d1e-431b-81eb-497282b46a14          17
13  c51243b8-e3d9-4cf7-ab29-0315048f91dc          17
14  29ea304f-821d-474e-81a1-394ca3945e02          17
15  973ee9d2-7c23-4e1d-afb2-86f679b55964          17
16  94264e23-ea67-496e-b027-5dd0cc334f1e          18
17  68258b8d-7d36-4d32-9093-6170a32bf087          18
18  28570119-9cdc-4120-98c0-4edb76cf36a3          19
19  e8885d7c-b863-4c41-997e-588416d655ae          19
20  5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb          20
21  ef943dfb-1368-44e0-a946-a0be360e1d54          20
22  ce0046dc-0ad3-4710-8147-549793c58b44          21
23  ebb1ca4c-f42f-41d8-adbc-1b08949036d1          22
24  f44d4a08-4c76-4000-ad61-d1d81032e643          24
25  420df33b-0072-4124-b1c6-0589daef3677          25
26  9d8fd25d-c4fe-4343-8ff5-5da5dad4e740          26
27  d362867a-d350-4aca-82d0-a63b7e0a14c7          27
28  1705dd0f-011a-492c-b006-b27e03f2f4ed          28
29  c332ce87-7afd-4a74-9896-3fef50179bd0          29
30  51f15281-8840-4fd0-92de-89188ab8d736          32
31  a9827c1c-fb54-4e5b-8bc6-d3099869e671          35
32  6e93f9d9-213d-4f2c-a1f0-f475dacef554          35
33  136c7916-4f9b-4e5c-bf01-77e9d2c681a2          37
34  0c04d9fb-d8d0-4ee0-8fc9-0c3f7f148bdf          38
35  8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc          44
36  61699d6d-904a-4ece-9026-cd61b3fd9a50          44
37  31f9612b-5a6b-48ea-887b-895772a83b99          46
38  05192757-942f-460d-b4ff-004ec39cc5ee          46
39  b70c7ff6-c2af-4df6-bd88-889bf767a168          50
40  42149ae1-6a3c-471e-a002-cb7263e8bb8c          50
41  37b5ce4d-dcfd-4bb7-bee4-d597eb114703          52
42  5e434d78-b2f6-4d88-b327-fff6ee50b901          54
43  c50e236f-6b3d-41c8-9e16-7ec343cac820          60
44  04df53ea-55c1-48d9-84a1-1f15c133b29b          66
45  ff8c4724-b7de-4189-bccf-cffddd4d6d44          66
46  359014a1-10e6-4bd8-9ba7-513d021c971e          68
47  69bf7e25-abb2-4dde-857f-f1138d4d0d8a          70
48  137b8481-4f1d-4b7f-babd-20f7117023ad          72
49  c6c45c39-cd73-49dd-818d-0a7865fe8a7f          90

Note-count distribution:
count    50.000000
mean     32.040000
std      19.973411
min      10.000000
25%      17.000000
50%      24.500000
75%      45.500000
max      90.000000
Name: note_count, dtype: float64

In [9]:
notes_clean = notes[
    notes["clean_note_text"]
    .astype(str)
    .str.strip()
    != "#NAME?"
].copy()

notes_dedup = (
    notes_clean
    .sort_values(
        ["person_id", "creation_timestamp"]
    )
    .drop_duplicates(
        subset=[
            "person_id",
            "clean_note_text"
        ],
        keep="first"
    )
    .reset_index(drop=True)
)

print("Raw notes:", len(notes))
print("After cleaning + deduplication:", len(notes_dedup))

Raw notes: 1602
After cleaning + deduplication: 1103

In [10]:
patient_sizes_dedup = (
    notes_dedup
    .groupby("person_id")
    .size()
    .reset_index(name="note_count")
    .sort_values("note_count")
    .reset_index(drop=True)
)

display(patient_sizes_dedup)

print("\nDeduplicated note-count distribution:")
print(
    patient_sizes_dedup["note_count"].describe()
)

                               person_id  note_count
0   ef943dfb-1368-44e0-a946-a0be360e1d54          10
1   c87e610e-ac2a-48cf-ac32-054f3e595498          10
2   96766f3f-aa50-4bcb-abbf-884328049ea9          11
3   58b8aad6-7327-4450-956f-b775be0f4984          11
4   f44d4a08-4c76-4000-ad61-d1d81032e643          12
5   a8629d2e-7fd8-449a-9149-e0f5045a04c4          12
6   f97ee974-67f3-4d72-9ed4-f17025da3749          13
7   1705dd0f-011a-492c-b006-b27e03f2f4ed          14
8   c54a9649-495a-4f89-a8ca-fbb14ba70ca6          14
9   028998ee-babc-4096-9b28-001bc2f9a84e          15
10  900efb9a-fb57-4f25-b2a3-0a8c6f55b2d6          15
11  f1538231-21af-4cfa-8b40-3303aa0d0c96          15
12  0f438665-d430-4adb-8acc-c3beed9e4942          15
13  fc6268ab-ad15-4613-9d8d-12c045e2fd46          16
14  b8085350-6748-47a5-a12f-6acd07c40a82          16
15  1dbe23dc-0d1e-431b-81eb-497282b46a14          17
16  c51243b8-e3d9-4cf7-ab29-0315048f91dc          17
17  973ee9d2-7c23-4e1d-afb2-86f679b55964          17
18  94264e23-ea67-496e-b027-5dd0cc334f1e          17
19  29ea304f-821d-474e-81a1-394ca3945e02          17
20  68258b8d-7d36-4d32-9093-6170a32bf087          18
21  e8885d7c-b863-4c41-997e-588416d655ae          19
22  28570119-9cdc-4120-98c0-4edb76cf36a3          19
23  0c04d9fb-d8d0-4ee0-8fc9-0c3f7f148bdf          19
24  5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb          20
25  ce0046dc-0ad3-4710-8147-549793c58b44          21
26  8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc          21
27  61699d6d-904a-4ece-9026-cd61b3fd9a50          22
28  31f9612b-5a6b-48ea-887b-895772a83b99          22
29  ebb1ca4c-f42f-41d8-adbc-1b08949036d1          22
30  05192757-942f-460d-b4ff-004ec39cc5ee          23
31  420df33b-0072-4124-b1c6-0589daef3677          24
32  b70c7ff6-c2af-4df6-bd88-889bf767a168          25
33  42149ae1-6a3c-471e-a002-cb7263e8bb8c          25
34  9d8fd25d-c4fe-4343-8ff5-5da5dad4e740          26
35  37b5ce4d-dcfd-4bb7-bee4-d597eb114703          26
36  5e434d78-b2f6-4d88-b327-fff6ee50b901          27
37  d362867a-d350-4aca-82d0-a63b7e0a14c7          27
38  c332ce87-7afd-4a74-9896-3fef50179bd0          29
39  c50e236f-6b3d-41c8-9e16-7ec343cac820          30
40  51f15281-8840-4fd0-92de-89188ab8d736          32
41  04df53ea-55c1-48d9-84a1-1f15c133b29b          33
42  ff8c4724-b7de-4189-bccf-cffddd4d6d44          33
43  359014a1-10e6-4bd8-9ba7-513d021c971e          34
44  6e93f9d9-213d-4f2c-a1f0-f475dacef554          34
45  69bf7e25-abb2-4dde-857f-f1138d4d0d8a          35
46  a9827c1c-fb54-4e5b-8bc6-d3099869e671          35
47  137b8481-4f1d-4b7f-babd-20f7117023ad          36
48  136c7916-4f9b-4e5c-bf01-77e9d2c681a2          37
49  c6c45c39-cd73-49dd-818d-0a7865fe8a7f          45

Deduplicated note-count distribution:
count    50.000000
mean     22.060000
std       8.471826
min      10.000000
25%      15.250000
50%      20.500000
75%      27.000000
max      45.000000
Name: note_count, dtype: float64

In [11]:
pilot_patients = {
    "short": "c87e610e-ac2a-48cf-ac32-054f3e595498",
    "medium": "ce0046dc-0ad3-4710-8147-549793c58b44",
    "long": "c6c45c39-cd73-49dd-818d-0a7865fe8a7f",
}

for case, patient_id in pilot_patients.items():
    n = len(
        notes_dedup[
            notes_dedup["person_id"] == patient_id
        ]
    )
    print(f"{case}: {patient_id} | {n} notes")

short: c87e610e-ac2a-48cf-ac32-054f3e595498 | 10 notes
medium: ce0046dc-0ad3-4710-8147-549793c58b44 | 21 notes
long: c6c45c39-cd73-49dd-818d-0a7865fe8a7f | 45 notes

In [12]:
# Short: 10 notes — c87e610e-ac2a-48cf-ac32-054f3e595498
# Medium: 21 notes — ce0046dc-0ad3-4710-8147-549793c58b44
# Long: 45 notes — c6c45c39-cd73-49dd-818d-0a7865fe8a7f

In [4]:
# ============================================================
# LOAD + PREPROCESS SOURCE NOTES
# ============================================================

notes = pd.read_csv(
    PROJECT_ROOT
    / "data"
    / "raw"
    / "clinical_notes.csv"
)

notes_clean = notes[
    notes["clean_note_text"]
    .astype(str)
    .str.strip()
    != "#NAME?"
].copy()

notes_dedup = (
    notes_clean
    .sort_values(
        ["person_id", "creation_timestamp"]
    )
    .drop_duplicates(
        subset=[
            "person_id",
            "clean_note_text",
        ],
        keep="first",
    )
    .reset_index(drop=True)
)

print("Raw notes:", len(notes))
print("After cleaning + deduplication:", len(notes_dedup))
print("Patients:", notes_dedup["person_id"].nunique())

Raw notes: 1602
After cleaning + deduplication: 1103
Patients: 50

In [5]:
# Patient to inspect for the clinician-evaluation pilot
PILOT_PATIENT_ID = "028998ee-babc-4096-9b28-001bc2f9a84e"

# Get this patient's complete cleaned + deduplicated clinical record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

print("Number of source notes:", len(pilot_notes))

# Display each note chronologically, exactly as it exists after
# the frozen preprocessing used in the study.
for i, row in pilot_notes.iterrows():
    print("=" * 100)
    print("Timestamp:", row["creation_timestamp"])
    print("=" * 100)
    print(row["clean_note_text"])
    print()

Number of source notes: 15
====================================================================================================
Timestamp: 07/01/2026 08:45
====================================================================================================
 - Patient: Tomos Ellis, 15-year-old male, presented via A&E on 07/01/26 at 08:45 with severe abdominal pain over the past 3 days. - Date of birth: 2008-05-17. - NHS number: 965833270. - Triage category: 3 - Urgent. - No known allergies reported. - Current medications: None declared.- Past medical history: None documented. - Initial assessment performed by Nurse Jamie Leigh Alexander. - ED diagnosis: Constipation. - Admiting consultant: Dr. Susan Jennifer Robson. - Decision: Proceed with baseline obs and assess pain severity.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

====================================================================================================
Timestamp: 07/01/2026 09:10
====================================================================================================
Patient: Tomos Ellis, 15-year-old male, presenting with abdominal pain.

- Event date/time: 07/01/26 at 09:10.
- Performed focused abdominal assessment by Nurse Jamie Leigh Alexander.
- Findings: Mild abdo distension, tenderness in lower abdo.

- NO (No guarding, rebound tenderness).
- Advise to NPO.
- Plan: Initiate IV fluids to manage mild dehyydration pending further investigations.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

====================================================================================================
Timestamp: 07/01/2026 09:25
====================================================================================================
Patient name: Tomos Ellis, 15-year-old male. NHS number: 965833270. Date of birth: 17/05/08. Event date/time: 07/01/226, 09:25. Seen by: Nurse Jamie Leigh Alexander. Chief complaint: Abdominal pain, ongoing for 3 days. ED diagnosis: Constipation. Admission time: 08:45. Mild dehydration noted on triage. Focused abdo exam showed mipld distension and tenderness in the lower abdo, with no guarding or rebound tenderness. IV fluids (0.9% sodium chloride) initiated at 500ml over 4 hours. Patient remains NBM. Awaiting results of bloods and abdo X-ray for further management decisions.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

====================================================================================================
Timestamp: 07/01/2026 10:00
====================================================================================================
Reviewed abdominal X-ray on 2026-01-07, which confirmed significant faecal loading. Findings were communicated to the patient, Tomos Ellis, and his mother by Nurse Jamie Leigh Alexander. Decision made tk administer a single dose of 10mg bisacodyl orally to initiate bowel movement. IV fluids (0.9% NaCl) to be continued to address mild dehydration.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

====================================================================================================
Timestamp: 07/01/2026 10:30
====================================================================================================
Patient
Tomos Ellis

Age
15

Sex
Male

NHS No.:
965833270

Date/Time
07/01/26 10:30

Seen By
Dr. Aya Kobayashi

Presenting Complaint
Abdominal pain

History of Presenting Complaint
3-day hx of abdominal pain and constipation. Pain details as follows:
Site: Lower abdomen
Onset: Gradual onset over 3 dayds
Character: Dull ache
Radiates: No radiation
Associations: Reduced appetite, mild nausea (no vomiting), no fever
Timing: Constant since onset
Exacerbating factors: Worse with eating
Severity: Reported as 7/10 at presentation

Past Medical History
Nil

Medications
Nil

Allergies
NKDA

Social History
Lives at home with parents. Attends secondary school. Denies smoking, alcohol, or illicit drug use.

Family History
No significant family history of GI conditions or other chronic illnesses.

Systems Review
Gastrointestinal: Constipation for 3 day s, no haematemesis or melaena, no persistent vomiting Cardiovascular: No chest pain, no palpitations, no syncope Respiratory: No SOB, no cough Genitourinary: No dysuria, no haematuria Neurological: No heqadache, no dizziness, no weakness Musculoskeletal: No recent trauma or joint swelling

On Examination
- Alert and oriented, sitting comfortably, mild istress due to pain
- Abdomen: Milc distension, tenderness in lower quadrants, no guarding, no rebound tenderness, no peritonism
- Bowel sounds: Present, mildly hypoactive
- Hydration status: Mild dehydratino noted with slightly dry mucous membranes and reduced skin turgor
- No signs of haemodynamic instability
- No evidence of severe, sudden-onset â€œtearingâ€ pain
- Pain reduced to 5/10 after IV fluids administration
BP: 112/68
HR: 82
RR: 16
Temp: 37.1
SpO2: 99% on room air

Investigations
Abdominal X-ray: Significant faecal loading, no evidence of obs or perf

Test Results
- FBC: Normal
- U&Es: Normal
- CRP: Normal
- LFTs: Normal

Impression
Constipation with mild dehydration

Referral
Referred to paeds. Acepted by paeds under Dr. Susan Jennifer Robson. Transferring to Paeds Ward, bed C05. Handover facilitated by Dr. Yuri Matsumoto.

Plan
- Start oral laxatives: Movicol 1 sachet TID
- Encourage oral hydration: Advise increased fluid intake
- Monitor bowel movements
- No surgery requ ired
- Admission to paeds for supportive management and observation


Dr. Aya Kobayashi (ED Doctor)
GMC number: 1161504

====================================================================================================
Timestamp: 07/01/2026 11:00
====================================================================================================
Clerking Doctor
Dr. Yuri Matsumoto (FY1)

Presenting Complaint
3-day hx of abdominal pain - 3-day hx of worsening adominal pain - Site: Lower abdmoen - Onset: Gradual - Character: Dull ache - Radiates: No radiartion - Associations: Constipation, reduced appetite - Timing: Constant - Exacerbating factors: Eating - Severity: 6/10 on arrival, reduced to 5/10 after IV fluids (0.9% sodium chloride) in ED - Note: Single dose of 10mg bisacodyl administered in ED

Review of Systems
- Cardiovascular: No chest pain, palpitations, or dizziness
- Respiratory: No SOB or cough
- Gastrointestinal: Abdominal pain as described, constipation, no nausea or vomiting, no melaena, no haematochezia
- Genitourinary: No dysuria or haematuria
- Neurological: No headaches, weakness, or altered coonsciousjess
- Musculoskeletal: No joint or muscle pain
- ENT: No sore throat or ear pain
- Dermatological: No rashes or skin changes

Past Medical History
- Nil

Medications
- None

Allergies
No known drug allergies

Social History
- Lives with parents
- Attends schol full-time
- Independent in activities of daily living
- No history of smoking, alcohol, or recreational drug use

Family History
No known familial history of gastrointestinal ior other relevant conditions

On Examination
- Alert, sitting comfortably, no acute distress
- Abdominal examination:
  - Inspection: Abdomen distenedd, no visible scars or masses
  - Palpation: Mild tenderness in bilateral lower quad rants (BLQ), no guarding or rebound tenderness
  - Percussion: Tympanic over large bowel
  - Auscultation: Normakl bowel sounds (NBS)
- Hydration assessment:
  - Mildly dry mucous membranes (MM)
  - Skin turgor slightly reduced
- No other significant findings on systemic examination

Observations
HR 92
BP 110/72
RR 16
Temp 36.8
SpO2 99%

Investigations
- Abdominal X-ray: Significant faecal loaading noted, no evidence of obstruction or perforation
- Blood tests: Normal FBC, U&Es, and CRP
- No other test results pending

Impression
Constipation with associated abdominal pain and mild dehydration

Plan
- Prescribe oral macrogol 13.8g sachets, 1 sachet TID as per ED recommendation
- Encourage oral fluid intake to address dehydration
- Monitor bowel movements andabdominal symptoms
- Reassess hydration status and abdominal symptoms after 24 hours
- If no significant improvement in symptoms after 24 hours, consider aditional imaging or alternative laxatives


Dr. Yuri Matsumoto (Foundation Trainee)
GMC number: 1135214

====================================================================================================
Timestamp: 07/01/2026 13:00
====================================================================================================
Clinician Leading Ward Round
Dr. Susan Jennifer Robson (Consultant), Dr. Denis Jonathan Sullivan (SpR)

Presenting Complaint
Abdominal pain Hx noted thank you

Issues
1. Constipation
-Significant faecal loading confirmed on abdominal X-ray
-Distended but soft abdomen with mild tenderness in lower quadrants
-Abdominal discomfort rated as 5/10

On Review
Reports abdo discomfort, 5/10 in severity.

Investigations
None since admission. AXR confirmed significant faecal loading. No new test results pnding.

Observations
HR 72
BP 112/68
RR 16
Temp 36.8
SpO2 99%

On Examination
Alert and comfortable at rest. Abdomen distended but soft. Mild tenderness in the lower quadrants. No guarding, rebound tenderness, or signs of peritonitis. Normal bowel sounds. No lalpable masses or organomegaly.

Plan
1. Start orl macrogol 1 sachet BD. 2. Advise oral fluid intake of at least 2L/day. 3. Monitor for bowel movements. 4. Reassess laxative dosage if no improvement by the next AM.


Dr. Susan Jennifer Robson (Consultant)
GMC number: 1468986

====================================================================================================
Timestamp: 07/01/2026 15:30
====================================================================================================
Patient seen for initialphysio session on 07/01/26 at 15:30. Session conducted by Therapist Albert Joseph Stevenson. Main goal was to encourage gentle mobilisation to aid bowel motility and alleviate constipation symptoms. Patient performed light physical exercises, including walking short distances within the ward and seated leg lifts. Education provided on the importance of regular movement to improve digestion and relieve constipation. Tolerated session well without adverse events. Plan: Patient to engage in light walking every 2-3 hrs as tolerated. Follow-up session scheduled for 08/01/26 to assess progress.
Therapist Albert Joseph Stevenson (Physical)

====================================================================================================
Timestamp: 07/01/2026 16:00
====================================================================================================
- Nurse Jamie Leigh Alexander discussed the importance of dietary fibre and hydration with the patient and his motherr.
- Written materials on high-fibre foods and recommended fluid intake provided.
- No changes to existing treatment plan made at this time.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

====================================================================================================
Timestamp: 08/01/2026 09:00
====================================================================================================
Clinician Leading Ward Round
Dr. Denis Jonathan Sullivan (SpR)

Presenting Complaint
Abdominal pain

Issues
1. Constipation
-Partial bowel movement overnight
-Reduction in abdominal pain
-Abdomen less distended on examination

Today

On Review
Patient reports reduction in abdo pain and feeling more comfortable. No new complaints. Partial BM overnight noted.

Investigations
No additional imaging requested. No new lab results. No pending results.

Observations
HR: 82
BP: 110/70
RR: 16
Temp: 36.8
SpO2: 99%

On Examination
General appearance: Patient appears comfortable and less distended compared to yesterday. Abdomen soft, mildly distended with reduced tenderness in lower quadrants. No guarding or rebound tenderness. No rashes or other abnormalities noted. A:Patent; on stridor or signs of airway compromise. B: Breathing comfortable; no increased work of breathing. Chest clear to auscultation bilaterally. C: Warm peripheries; no oedema. CRT <2s. No tachy or hypotension. D: Alert, orientated, and interactive. No focal neurological deficits noted.

Plan
1. Continue macrogol 1 sachet TDS. 2. Encourage oral hydratioon. 3. Assess for a full BM within the next 24 hours. 4. Consider discharge if symptoms continue to improve.


Dr. Denis Jonathan Sullivan (Specialty Registrar)
GMC number: 1920684

====================================================================================================
Timestamp: 08/01/2026 10:30
====================================================================================================
Patient reviewed for physiotherapy on 08/01/26 at 10:30. Session conducted by Therapist Albert Joseph Stevenson. Focus of the session was on promoting bowel motility and aleviating residual abdo discomfort related to prior constipation symptoms. Patient guided through gentle stretching exercises and light mobility activities. Session lasted 20 mins and was well-tolerated. No adverse events noted. Patient advisd to continue light walking sessions post-discharge to support recovery and prevent symptom recurrence. No new meds prescribed during this session.
Therapist Albert Joseph Stevenson (Physical)

====================================================================================================
Timestamp: 08/01/2026 11:15
====================================================================================================
Dietitian reviewed the patient. Advised hgih-fibre diet. Recommendations included whole grains, fresh fruits, and vegetables. No changes to medications. Current plan with oral laxatives and hydration to continue.
Therapist Percy Vincent Miles (Dietary)

====================================================================================================
Timestamp: 08/01/2026 14:00
====================================================================================================
Reviewed patient for a second physiotherapy (PT) session on 08/01/26 at 14:00. Guided the patient through gentle stretching exercises and light mobility activities, lasting 20 minutes, aimed at improving bowel motility and alleviating residual abdominal discomfort. Patient participated actively and reported reduced discomfort with movement compared to 07/01/26. No adverse events observed. Recommended continuation of light mobilisation  during hospital stay. Advised gentle walking at home post-discharge to support bowel motility. Session conducted by Therapist Albert Joseph Stevenson.
Therapist Albert Joseph Stevenson (Physical)

====================================================================================================
Timestamp: 09/01/2026 08:30
====================================================================================================
Clinician Leading Ward Round
Dr. Denis Jonathan Sullivan (SpR)

Presenting Complaint
Abdominal pain

Issues
1. Constipation
-Resolved with full bowel movement overnight
-No further abdominal pain
-Discontinuing oral macrogol as symptoms resolved

Today

On Review
Patient reports full bowel movement overnight. No further abdominal pain. Feels well.

Investigations
Nonr

Observations
HR: 78
BP: 112/74
RR: 16
Temp: 36.6
SpO2: 98% on air

On Examination
General: Comfortabple, hydrated, no distress. A: Patent, no stridor. B: Non-lab oured breathing, equal air entry, no added sounds. C: Warm peripheries, CRT <2s, HS I+II+0, no murmurs. D: Alert, GCS 15, no focal deficits. E: Abdomen soft, non-tender, no masses. No guarding or rebound tenderness.

Plan
- Discontinue oral macrogol
- Prescribe take-home lactulose 10 mL BD PRN for maintenance
- Discharge pt today with advice on high-fibre diet and oral hydration to prevent recurrence


Dr. Denis Jonathan Sullivan (Specialty Registrar)
GMC number: 1920684

====================================================================================================
Timestamp: 09/01/2026 09:30
====================================================================================================
- Contact made with patient's GP, Dr. CianCian, by Nurse Jamie Leigh Alexander.
- GP informed of patient's discharge and provided details of hospital management.
- Follow-up arrangements discussed to ensure ongoing manayement for constipation prevention.
- Patient and family advised to contact GP if symptoms of constipation recur.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

In [6]:
import json
from pathlib import Path

# Patient we're using to design the clinician-evaluation format
PILOT_PATIENT_ID = "028998ee-babc-4096-9b28-001bc2f9a84e"

PROJECT_ROOT = Path.cwd().parent.parent
RESULTS_DIR = PROJECT_ROOT / "data" / "results"

# Frozen final result files
summary_files = {
    "direct": RESULTS_DIR / "direct" / "direct_summaries.json",
    "hierarchical": RESULTS_DIR / "hierarchical" / "hierarchical_summaries.json",
    "rag": RESULTS_DIR / "rag" / "final_rag_summaries.json",
    "rag_verification": RESULTS_DIR / "rag_verification" / "final_verified_summaries.json",
}

# Field containing the final summary in each workflow
summary_fields = {
    "direct": "summary",
    "hierarchical": "final_summary",
    "rag": "summary",
    "rag_verification": "final_summary",
}

# Load and print the exact frozen summary from each workflow
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    patient_result = results[PILOT_PATIENT_ID]
    summary = patient_result[summary_fields[workflow]]

    pilot_summaries[workflow] = summary

    print("\n" + "=" * 100)
    print(workflow.upper())
    print("=" * 100)
    print(summary)

====================================================================================================
DIRECT
====================================================================================================
Tomos Ellis, a 15-year-old male with no documented past medical history, medications, or allergies, presented via A&E on 07/01/2026 at 08:45 with 3 days of worsening constant lower abdominal pain and constipation. He reported reduced appetite and mild nausea without vomiting or fever. Examination showed mild abdominal distension and lower-quadrant tenderness without guarding, rebound tenderness, or peritonism. Mild dehydration was noted, with slightly dry mucous membranes and reduced skin turgor; observations were stable.

He was initially diagnosed with constipation. He was kept NPO/NBM and commenced on 0.9% sodium chloride IV fluids, 500 mL over 4 hours. Blood tests, including FBC, U&Es, CRP, and LFTs, were normal. Abdominal X-ray demonstrated significant faecal loading without obstruction or perforation. A single 10 mg oral dose of bisacodyl was given, and he was admitted to the paediatric ward for supportive management and observation.

On medical review, abdominal pain had reduced from approximately 6–7/10 to 5/10 following IV fluids. Oral macrogol (Movicol) was commenced, initially documented as one sachet three times daily, with encouragement of oral hydration and monitoring of bowel movements and symptoms. A subsequent ward round plan documented macrogol one sachet twice daily and a target fluid intake of at least 2 L/day. He received advice regarding dietary fibre and hydration, with written information provided to him and his mother. Physiotherapy sessions on 07/01 and 08/01 focused on gentle mobilisation, stretching, and walking to promote bowel motility; these were well tolerated. A dietitian recommended a high-fibre diet including whole grains, fruit, and vegetables.

By the following ward review, he had passed a partial bowel movement overnight, with reduced abdominal pain and less distension. Macrogol was continued at one sachet three times daily, with ongoing hydration advice. On the subsequent review, he had passed a full bowel movement overnight, with complete resolution of abdominal pain. He was comfortable, hydrated, and had a soft, non-tender abdomen without guarding or rebound tenderness; observations remained stable.

Macrogol was discontinued. He was discharged with lactulose 10 mL twice daily as required for maintenance, advice to maintain oral hydration and a high-fibre diet, and recommendations for gentle walking at home. His GP was informed of the admission, treatment, and discharge plan, and the patient and family were advised to contact the GP if constipation recurred.

====================================================================================================
HIERARCHICAL
====================================================================================================
On 07/01/2026, a 15-year-old male with no documented past medical history, medications, or allergies presented to A&E with 3 days of worsening constant dull lower abdominal pain, constipation, reduced appetite, and mild nausea without vomiting, fever, urinary symptoms, or gastrointestinal bleeding. He was mildly dehydrated, with mild abdominal distension, lower abdominal tenderness, and mildly hypoactive or normal bowel sounds, but no guarding, rebound, peritonism, or haemodynamic instability. Pain improved from 6–7/10 to approximately 5/10 after IV fluids.

Abdominal X-ray demonstrated significant faecal loading without obstruction or perforation. FBC, U&Es, CRP, and LFTs were normal. He received IV 0.9% sodium chloride 500 mL over 4 hours, was initially kept NBM/NPO, and was given a single oral dose of bisacodyl 10 mg. Paediatrics admitted him for supportive management and observation, with oral macrogol/Movicol, encouragement of oral fluids, and monitoring of bowel movements. Physiotherapy supported gentle mobilisation, and nursing and dietetic staff provided advice on hydration, fibre intake, and regular movement.

By 08/01/2026, he had passed a partial bowel movement with reduced pain and distension. Following a full bowel movement overnight, his abdominal pain resolved; he was clinically well with stable observations and a soft, non-tender abdomen without guarding or rebound. Oral macrogol was stopped, and lactulose 10 mL twice daily as required was prescribed for maintenance. He was discharged home with advice regarding a high-fibre diet, adequate oral hydration, and gentle walking. His GP was informed of the admission, discharge, and follow-up advice.

====================================================================================================
RAG
====================================================================================================
Tomos Ellis, a 15-year-old male with no documented past medical history, medications, or allergies, presented to the ED on 07/01/2026 with 3 days of constant dull lower abdominal pain, constipation, reduced appetite, and mild nausea without vomiting or fever. Pain was rated 6–7/10 and worsened with eating. Examination showed mild dehydration, mild abdominal distension, lower abdominal tenderness, and mildly hypoactive bowel sounds, without guarding, rebound tenderness, or peritonism. Observations were stable.

Abdominal X-ray demonstrated significant faecal loading with no obstruction or perforation. FBC, U&Es, CRP, and LFTs were normal. He was diagnosed with constipation and mild dehydration and admitted to the paediatric ward for supportive management. Treatment included IV 0.9% sodium chloride 500 mL over 4 hours, a single 10 mg dose of bisacodyl, oral macrogol/Movicol 1 sachet three times daily, oral hydration, and monitoring of bowel movements. No surgery was required.

On 07–08/01, he received advice on hydration, dietary fibre, and mobilisation. Physiotherapy sessions involved walking, stretching, and light exercises to support bowel motility; these were well tolerated, with reduced discomfort reported during movement on 08/01. Dietetic review recommended a high-fibre diet including whole grains, fruits, and vegetables. The plan on 08/01 was to continue macrogol and hydration, assess for a bowel movement, and consider discharge if symptoms improved.

On 09/01/2026, oral macrogol was discontinued. He was prescribed take-home lactulose 10 mL twice daily as required for maintenance and discharged with advice to maintain a high-fibre diet, adequate oral hydration, and ongoing light walking to help prevent recurrence.

====================================================================================================
RAG_VERIFICATION
====================================================================================================
Tomos Ellis, a 15-year-old male with no documented past medical history, medications, or allergies, presented to the ED on 07/01/2026 with 3 days of constant dull lower abdominal pain, constipation, reduced appetite, and mild nausea without vomiting or fever. Pain was rated 6–7/10 and worsened with eating. Examination showed mild dehydration, mild abdominal distension, lower abdominal tenderness, and mildly hypoactive bowel sounds, without guarding, rebound tenderness, or peritonism. Observations were stable.

Abdominal X-ray demonstrated significant faecal loading with no obstruction or perforation. FBC, U&Es, CRP, and LFTs were normal. He was diagnosed with constipation and mild dehydration and admitted to the paediatric ward for supportive management. Treatment included IV 0.9% sodium chloride 500 mL over 4 hours, a single 10 mg dose of bisacodyl, oral macrogol/Movicol 1 sachet three times daily, oral hydration, and monitoring of bowel movements. No surgery was required.

On 07–08/01, he received advice on hydration, dietary fibre, and mobilisation. Physiotherapy sessions involved walking, stretching, and light exercises to support bowel motility; these were well tolerated, with reduced discomfort reported during movement on 08/01. Dietetic review recommended a high-fibre diet including whole grains, fruits, and vegetables. The plan on 08/01 was to continue macrogol and hydration, assess for a bowel movement, and consider discharge if symptoms improved.

On 09/01/2026, oral macrogol was discontinued. He was prescribed take-home lactulose 10 mL twice daily as required for maintenance and discharged with advice to maintain a high-fibre diet, adequate oral hydration, and ongoing light walking to help prevent recurrence.

In [7]:
# ---------------------------------------------------------
# Clinician validation — Patient 01 document content
# ---------------------------------------------------------

PATIENT_LABEL = "Patient 01"

# These are presentation labels only.
# Workflow names will NOT appear in the clinician document.
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

# Build clinician-facing text
lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append("")

# Add the original cleaned/deduplicated notes chronologically
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Add the four blinded summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

patient_01_content = "\n".join(lines)

print(patient_01_content)

Patient 01

SOURCE CLINICAL RECORD

Clinical Note 1
Date/Time: 07/01/2026 08:45

- Patient: Tomos Ellis, 15-year-old male, presented via A&E on 07/01/26 at 08:45 with severe abdominal pain over the past 3 days. - Date of birth: 2008-05-17. - NHS number: 965833270. - Triage category: 3 - Urgent. - No known allergies reported. - Current medications: None declared.- Past medical history: None documented. - Initial assessment performed by Nurse Jamie Leigh Alexander. - ED diagnosis: Constipation. - Admiting consultant: Dr. Susan Jennifer Robson. - Decision: Proceed with baseline obs and assess pain severity.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 07/01/2026 09:10

Patient: Tomos Ellis, 15-year-old male, presenting with abdominal pain.

- Event date/time: 07/01/26 at 09:10.
- Performed focused abdominal assessment by Nurse Jamie Leigh Alexander.
- Findings: Mild abdo distension, tenderness in lower abdo.

- NO (No guarding, rebound tenderness).
- Advise to NPO.
- Plan: Initiate IV fluids to manage mild dehyydration pending further investigations.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 07/01/2026 09:25

Patient name: Tomos Ellis, 15-year-old male. NHS number: 965833270. Date of birth: 17/05/08. Event date/time: 07/01/226, 09:25. Seen by: Nurse Jamie Leigh Alexander. Chief complaint: Abdominal pain, ongoing for 3 days. ED diagnosis: Constipation. Admission time: 08:45. Mild dehydration noted on triage. Focused abdo exam showed mipld distension and tenderness in the lower abdo, with no guarding or rebound tenderness. IV fluids (0.9% sodium chloride) initiated at 500ml over 4 hours. Patient remains NBM. Awaiting results of bloods and abdo X-ray for further management decisions.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 07/01/2026 10:00

Reviewed abdominal X-ray on 2026-01-07, which confirmed significant faecal loading. Findings were communicated to the patient, Tomos Ellis, and his mother by Nurse Jamie Leigh Alexander. Decision made tk administer a single dose of 10mg bisacodyl orally to initiate bowel movement. IV fluids (0.9% NaCl) to be continued to address mild dehydration.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 07/01/2026 10:30

Patient
Tomos Ellis

Age
15

Sex
Male

NHS No.:
965833270

Date/Time
07/01/26 10:30

Seen By
Dr. Aya Kobayashi

Presenting Complaint
Abdominal pain

History of Presenting Complaint
3-day hx of abdominal pain and constipation. Pain details as follows:
Site: Lower abdomen
Onset: Gradual onset over 3 dayds
Character: Dull ache
Radiates: No radiation
Associations: Reduced appetite, mild nausea (no vomiting), no fever
Timing: Constant since onset
Exacerbating factors: Worse with eating
Severity: Reported as 7/10 at presentation

Past Medical History
Nil

Medications
Nil

Allergies
NKDA

Social History
Lives at home with parents. Attends secondary school. Denies smoking, alcohol, or illicit drug use.

Family History
No significant family history of GI conditions or other chronic illnesses.

Systems Review
Gastrointestinal: Constipation for 3 day s, no haematemesis or melaena, no persistent vomiting Cardiovascular: No chest pain, no palpitations, no syncope Respiratory: No SOB, no cough Genitourinary: No dysuria, no haematuria Neurological: No heqadache, no dizziness, no weakness Musculoskeletal: No recent trauma or joint swelling

On Examination
- Alert and oriented, sitting comfortably, mild istress due to pain
- Abdomen: Milc distension, tenderness in lower quadrants, no guarding, no rebound tenderness, no peritonism
- Bowel sounds: Present, mildly hypoactive
- Hydration status: Mild dehydratino noted with slightly dry mucous membranes and reduced skin turgor
- No signs of haemodynamic instability
- No evidence of severe, sudden-onset â€œtearingâ€ pain
- Pain reduced to 5/10 after IV fluids administration
BP: 112/68
HR: 82
RR: 16
Temp: 37.1
SpO2: 99% on room air

Investigations
Abdominal X-ray: Significant faecal loading, no evidence of obs or perf

Test Results
- FBC: Normal
- U&Es: Normal
- CRP: Normal
- LFTs: Normal

Impression
Constipation with mild dehydration

Referral
Referred to paeds. Acepted by paeds under Dr. Susan Jennifer Robson. Transferring to Paeds Ward, bed C05. Handover facilitated by Dr. Yuri Matsumoto.

Plan
- Start oral laxatives: Movicol 1 sachet TID
- Encourage oral hydration: Advise increased fluid intake
- Monitor bowel movements
- No surgery requ ired
- Admission to paeds for supportive management and observation


Dr. Aya Kobayashi (ED Doctor)
GMC number: 1161504

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 07/01/2026 11:00

Clerking Doctor
Dr. Yuri Matsumoto (FY1)

Presenting Complaint
3-day hx of abdominal pain - 3-day hx of worsening adominal pain - Site: Lower abdmoen - Onset: Gradual - Character: Dull ache - Radiates: No radiartion - Associations: Constipation, reduced appetite - Timing: Constant - Exacerbating factors: Eating - Severity: 6/10 on arrival, reduced to 5/10 after IV fluids (0.9% sodium chloride) in ED - Note: Single dose of 10mg bisacodyl administered in ED

Review of Systems
- Cardiovascular: No chest pain, palpitations, or dizziness
- Respiratory: No SOB or cough
- Gastrointestinal: Abdominal pain as described, constipation, no nausea or vomiting, no melaena, no haematochezia
- Genitourinary: No dysuria or haematuria
- Neurological: No headaches, weakness, or altered coonsciousjess
- Musculoskeletal: No joint or muscle pain
- ENT: No sore throat or ear pain
- Dermatological: No rashes or skin changes

Past Medical History
- Nil

Medications
- None

Allergies
No known drug allergies

Social History
- Lives with parents
- Attends schol full-time
- Independent in activities of daily living
- No history of smoking, alcohol, or recreational drug use

Family History
No known familial history of gastrointestinal ior other relevant conditions

On Examination
- Alert, sitting comfortably, no acute distress
- Abdominal examination:
  - Inspection: Abdomen distenedd, no visible scars or masses
  - Palpation: Mild tenderness in bilateral lower quad rants (BLQ), no guarding or rebound tenderness
  - Percussion: Tympanic over large bowel
  - Auscultation: Normakl bowel sounds (NBS)
- Hydration assessment:
  - Mildly dry mucous membranes (MM)
  - Skin turgor slightly reduced
- No other significant findings on systemic examination

Observations
HR 92
BP 110/72
RR 16
Temp 36.8
SpO2 99%

Investigations
- Abdominal X-ray: Significant faecal loaading noted, no evidence of obstruction or perforation
- Blood tests: Normal FBC, U&Es, and CRP
- No other test results pending

Impression
Constipation with associated abdominal pain and mild dehydration

Plan
- Prescribe oral macrogol 13.8g sachets, 1 sachet TID as per ED recommendation
- Encourage oral fluid intake to address dehydration
- Monitor bowel movements andabdominal symptoms
- Reassess hydration status and abdominal symptoms after 24 hours
- If no significant improvement in symptoms after 24 hours, consider aditional imaging or alternative laxatives


Dr. Yuri Matsumoto (Foundation Trainee)
GMC number: 1135214

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 07/01/2026 13:00

Clinician Leading Ward Round
Dr. Susan Jennifer Robson (Consultant), Dr. Denis Jonathan Sullivan (SpR)

Presenting Complaint
Abdominal pain Hx noted thank you

Issues
1. Constipation
-Significant faecal loading confirmed on abdominal X-ray
-Distended but soft abdomen with mild tenderness in lower quadrants
-Abdominal discomfort rated as 5/10

On Review
Reports abdo discomfort, 5/10 in severity.

Investigations
None since admission. AXR confirmed significant faecal loading. No new test results pnding.

Observations
HR 72
BP 112/68
RR 16
Temp 36.8
SpO2 99%

On Examination
Alert and comfortable at rest. Abdomen distended but soft. Mild tenderness in the lower quadrants. No guarding, rebound tenderness, or signs of peritonitis. Normal bowel sounds. No lalpable masses or organomegaly.

Plan
1. Start orl macrogol 1 sachet BD. 2. Advise oral fluid intake of at least 2L/day. 3. Monitor for bowel movements. 4. Reassess laxative dosage if no improvement by the next AM.


Dr. Susan Jennifer Robson (Consultant)
GMC number: 1468986

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 07/01/2026 15:30

Patient seen for initialphysio session on 07/01/26 at 15:30. Session conducted by Therapist Albert Joseph Stevenson. Main goal was to encourage gentle mobilisation to aid bowel motility and alleviate constipation symptoms. Patient performed light physical exercises, including walking short distances within the ward and seated leg lifts. Education provided on the importance of regular movement to improve digestion and relieve constipation. Tolerated session well without adverse events. Plan: Patient to engage in light walking every 2-3 hrs as tolerated. Follow-up session scheduled for 08/01/26 to assess progress.
Therapist Albert Joseph Stevenson (Physical)

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 07/01/2026 16:00

- Nurse Jamie Leigh Alexander discussed the importance of dietary fibre and hydration with the patient and his motherr.
- Written materials on high-fibre foods and recommended fluid intake provided.
- No changes to existing treatment plan made at this time.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 08/01/2026 09:00

Clinician Leading Ward Round
Dr. Denis Jonathan Sullivan (SpR)

Presenting Complaint
Abdominal pain

Issues
1. Constipation
-Partial bowel movement overnight
-Reduction in abdominal pain
-Abdomen less distended on examination

Today

On Review
Patient reports reduction in abdo pain and feeling more comfortable. No new complaints. Partial BM overnight noted.

Investigations
No additional imaging requested. No new lab results. No pending results.

Observations
HR: 82
BP: 110/70
RR: 16
Temp: 36.8
SpO2: 99%

On Examination
General appearance: Patient appears comfortable and less distended compared to yesterday. Abdomen soft, mildly distended with reduced tenderness in lower quadrants. No guarding or rebound tenderness. No rashes or other abnormalities noted. A:Patent; on stridor or signs of airway compromise. B: Breathing comfortable; no increased work of breathing. Chest clear to auscultation bilaterally. C: Warm peripheries; no oedema. CRT <2s. No tachy or hypotension. D: Alert, orientated, and interactive. No focal neurological deficits noted.

Plan
1. Continue macrogol 1 sachet TDS. 2. Encourage oral hydratioon. 3. Assess for a full BM within the next 24 hours. 4. Consider discharge if symptoms continue to improve.


Dr. Denis Jonathan Sullivan (Specialty Registrar)
GMC number: 1920684

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 08/01/2026 10:30

Patient reviewed for physiotherapy on 08/01/26 at 10:30. Session conducted by Therapist Albert Joseph Stevenson. Focus of the session was on promoting bowel motility and aleviating residual abdo discomfort related to prior constipation symptoms. Patient guided through gentle stretching exercises and light mobility activities. Session lasted 20 mins and was well-tolerated. No adverse events noted. Patient advisd to continue light walking sessions post-discharge to support recovery and prevent symptom recurrence. No new meds prescribed during this session.
Therapist Albert Joseph Stevenson (Physical)

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 08/01/2026 11:15

Dietitian reviewed the patient. Advised hgih-fibre diet. Recommendations included whole grains, fresh fruits, and vegetables. No changes to medications. Current plan with oral laxatives and hydration to continue.
Therapist Percy Vincent Miles (Dietary)

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 08/01/2026 14:00

Reviewed patient for a second physiotherapy (PT) session on 08/01/26 at 14:00. Guided the patient through gentle stretching exercises and light mobility activities, lasting 20 minutes, aimed at improving bowel motility and alleviating residual abdominal discomfort. Patient participated actively and reported reduced discomfort with movement compared to 07/01/26. No adverse events observed. Recommended continuation of light mobilisation  during hospital stay. Advised gentle walking at home post-discharge to support bowel motility. Session conducted by Therapist Albert Joseph Stevenson.
Therapist Albert Joseph Stevenson (Physical)

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 09/01/2026 08:30

Clinician Leading Ward Round
Dr. Denis Jonathan Sullivan (SpR)

Presenting Complaint
Abdominal pain

Issues
1. Constipation
-Resolved with full bowel movement overnight
-No further abdominal pain
-Discontinuing oral macrogol as symptoms resolved

Today

On Review
Patient reports full bowel movement overnight. No further abdominal pain. Feels well.

Investigations
Nonr

Observations
HR: 78
BP: 112/74
RR: 16
Temp: 36.6
SpO2: 98% on air

On Examination
General: Comfortabple, hydrated, no distress. A: Patent, no stridor. B: Non-lab oured breathing, equal air entry, no added sounds. C: Warm peripheries, CRT <2s, HS I+II+0, no murmurs. D: Alert, GCS 15, no focal deficits. E: Abdomen soft, non-tender, no masses. No guarding or rebound tenderness.

Plan
- Discontinue oral macrogol
- Prescribe take-home lactulose 10 mL BD PRN for maintenance
- Discharge pt today with advice on high-fibre diet and oral hydration to prevent recurrence


Dr. Denis Jonathan Sullivan (Specialty Registrar)
GMC number: 1920684

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 09/01/2026 09:30

- Contact made with patient's GP, Dr. CianCian, by Nurse Jamie Leigh Alexander.
- GP informed of patient's discharge and provided details of hospital management.
- Follow-up arrangements discussed to ensure ongoing manayement for constipation prevention.
- Patient and family advised to contact GP if symptoms of constipation recur.
Nurse Jamie Leigh Alexander
NMC number: 27H5222T

--------------------------------------------------------------------------------

GENERATED SUMMARIES

SUMMARY A

Tomos Ellis, a 15-year-old male with no documented past medical history, medications, or allergies, presented via A&E on 07/01/2026 at 08:45 with 3 days of worsening constant lower abdominal pain and constipation. He reported reduced appetite and mild nausea without vomiting or fever. Examination showed mild abdominal distension and lower-quadrant tenderness without guarding, rebound tenderness, or peritonism. Mild dehydration was noted, with slightly dry mucous membranes and reduced skin turgor; observations were stable.

He was initially diagnosed with constipation. He was kept NPO/NBM and commenced on 0.9% sodium chloride IV fluids, 500 mL over 4 hours. Blood tests, including FBC, U&Es, CRP, and LFTs, were normal. Abdominal X-ray demonstrated significant faecal loading without obstruction or perforation. A single 10 mg oral dose of bisacodyl was given, and he was admitted to the paediatric ward for supportive management and observation.

On medical review, abdominal pain had reduced from approximately 6–7/10 to 5/10 following IV fluids. Oral macrogol (Movicol) was commenced, initially documented as one sachet three times daily, with encouragement of oral hydration and monitoring of bowel movements and symptoms. A subsequent ward round plan documented macrogol one sachet twice daily and a target fluid intake of at least 2 L/day. He received advice regarding dietary fibre and hydration, with written information provided to him and his mother. Physiotherapy sessions on 07/01 and 08/01 focused on gentle mobilisation, stretching, and walking to promote bowel motility; these were well tolerated. A dietitian recommended a high-fibre diet including whole grains, fruit, and vegetables.

By the following ward review, he had passed a partial bowel movement overnight, with reduced abdominal pain and less distension. Macrogol was continued at one sachet three times daily, with ongoing hydration advice. On the subsequent review, he had passed a full bowel movement overnight, with complete resolution of abdominal pain. He was comfortable, hydrated, and had a soft, non-tender abdomen without guarding or rebound tenderness; observations remained stable.

Macrogol was discontinued. He was discharged with lactulose 10 mL twice daily as required for maintenance, advice to maintain oral hydration and a high-fibre diet, and recommendations for gentle walking at home. His GP was informed of the admission, treatment, and discharge plan, and the patient and family were advised to contact the GP if constipation recurred.

--------------------------------------------------------------------------------

SUMMARY B

On 07/01/2026, a 15-year-old male with no documented past medical history, medications, or allergies presented to A&E with 3 days of worsening constant dull lower abdominal pain, constipation, reduced appetite, and mild nausea without vomiting, fever, urinary symptoms, or gastrointestinal bleeding. He was mildly dehydrated, with mild abdominal distension, lower abdominal tenderness, and mildly hypoactive or normal bowel sounds, but no guarding, rebound, peritonism, or haemodynamic instability. Pain improved from 6–7/10 to approximately 5/10 after IV fluids.

Abdominal X-ray demonstrated significant faecal loading without obstruction or perforation. FBC, U&Es, CRP, and LFTs were normal. He received IV 0.9% sodium chloride 500 mL over 4 hours, was initially kept NBM/NPO, and was given a single oral dose of bisacodyl 10 mg. Paediatrics admitted him for supportive management and observation, with oral macrogol/Movicol, encouragement of oral fluids, and monitoring of bowel movements. Physiotherapy supported gentle mobilisation, and nursing and dietetic staff provided advice on hydration, fibre intake, and regular movement.

By 08/01/2026, he had passed a partial bowel movement with reduced pain and distension. Following a full bowel movement overnight, his abdominal pain resolved; he was clinically well with stable observations and a soft, non-tender abdomen without guarding or rebound. Oral macrogol was stopped, and lactulose 10 mL twice daily as required was prescribed for maintenance. He was discharged home with advice regarding a high-fibre diet, adequate oral hydration, and gentle walking. His GP was informed of the admission, discharge, and follow-up advice.

--------------------------------------------------------------------------------

SUMMARY C

Tomos Ellis, a 15-year-old male with no documented past medical history, medications, or allergies, presented to the ED on 07/01/2026 with 3 days of constant dull lower abdominal pain, constipation, reduced appetite, and mild nausea without vomiting or fever. Pain was rated 6–7/10 and worsened with eating. Examination showed mild dehydration, mild abdominal distension, lower abdominal tenderness, and mildly hypoactive bowel sounds, without guarding, rebound tenderness, or peritonism. Observations were stable.


In [8]:
# ---------------------------------------------------------
# Clinician validation — source record sizes
# ---------------------------------------------------------

# Calculate source-record size using ONLY the original
# cleaned/deduplicated notes — no evaluation scores.
patient_sizes = (
    notes_dedup
    .groupby("person_id")
    .agg(
        note_count=("clean_note_text", "size"),
        word_count=(
            "clean_note_text",
            lambda x: sum(len(str(note).split()) for note in x)
        )
    )
    .reset_index()
    .sort_values("word_count")
    .reset_index(drop=True)
)

print("Patients:", len(patient_sizes))
print()
print(patient_sizes[["person_id", "note_count", "word_count"]].to_string(index=False))

Patients: 50

                           person_id  note_count  word_count
c87e610e-ac2a-48cf-ac32-054f3e595498          10        1380
96766f3f-aa50-4bcb-abbf-884328049ea9          11        1508
973ee9d2-7c23-4e1d-afb2-86f679b55964          17        1770
ef943dfb-1368-44e0-a946-a0be360e1d54          10        1772
c54a9649-495a-4f89-a8ca-fbb14ba70ca6          14        1780
68258b8d-7d36-4d32-9093-6170a32bf087          18        1797
f97ee974-67f3-4d72-9ed4-f17025da3749          13        1800
29ea304f-821d-474e-81a1-394ca3945e02          17        1813
fc6268ab-ad15-4613-9d8d-12c045e2fd46          16        1840
028998ee-babc-4096-9b28-001bc2f9a84e          15        1903
a8629d2e-7fd8-449a-9149-e0f5045a04c4          12        1927
c51243b8-e3d9-4cf7-ab29-0315048f91dc          17        2024
f44d4a08-4c76-4000-ad61-d1d81032e643          12        2048
f1538231-21af-4cfa-8b40-3303aa0d0c96          15        2075
0f438665-d430-4adb-8acc-c3beed9e4942          15        2200
1705dd0f-011a-492c-b006-b27e03f2f4ed          14        2219
b8085350-6748-47a5-a12f-6acd07c40a82          16        2227
58b8aad6-7327-4450-956f-b775be0f4984          11        2248
94264e23-ea67-496e-b027-5dd0cc334f1e          17        2259
e8885d7c-b863-4c41-997e-588416d655ae          19        2304
900efb9a-fb57-4f25-b2a3-0a8c6f55b2d6          15        2538
28570119-9cdc-4120-98c0-4edb76cf36a3          19        2550
31f9612b-5a6b-48ea-887b-895772a83b99          22        2618
1dbe23dc-0d1e-431b-81eb-497282b46a14          17        2852
ce0046dc-0ad3-4710-8147-549793c58b44          21        2871
05192757-942f-460d-b4ff-004ec39cc5ee          23        2958
61699d6d-904a-4ece-9026-cd61b3fd9a50          22        3017
8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc          21        3051
5e434d78-b2f6-4d88-b327-fff6ee50b901          27        3100
359014a1-10e6-4bd8-9ba7-513d021c971e          34        3136
b70c7ff6-c2af-4df6-bd88-889bf767a168          25        3271
42149ae1-6a3c-471e-a002-cb7263e8bb8c          25        3342
ff8c4724-b7de-4189-bccf-cffddd4d6d44          33        3397
ebb1ca4c-f42f-41d8-adbc-1b08949036d1          22        3436
5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb          20        3452
c332ce87-7afd-4a74-9896-3fef50179bd0          29        3525
37b5ce4d-dcfd-4bb7-bee4-d597eb114703          26        3525
51f15281-8840-4fd0-92de-89188ab8d736          32        3611
04df53ea-55c1-48d9-84a1-1f15c133b29b          33        3625
0c04d9fb-d8d0-4ee0-8fc9-0c3f7f148bdf          19        3677
420df33b-0072-4124-b1c6-0589daef3677          24        3749
d362867a-d350-4aca-82d0-a63b7e0a14c7          27        3846
6e93f9d9-213d-4f2c-a1f0-f475dacef554          34        3867
c50e236f-6b3d-41c8-9e16-7ec343cac820          30        3897
a9827c1c-fb54-4e5b-8bc6-d3099869e671          35        3926
137b8481-4f1d-4b7f-babd-20f7117023ad          36        3991
136c7916-4f9b-4e5c-bf01-77e9d2c681a2          37        4278
9d8fd25d-c4fe-4343-8ff5-5da5dad4e740          26        4287
c6c45c39-cd73-49dd-818d-0a7865fe8a7f          45        5134
69bf7e25-abb2-4dde-857f-f1138d4d0d8a          35        5525

In [9]:
# ---------------------------------------------------------
# Clinician validation — Patient 02
# ---------------------------------------------------------

PILOT_PATIENT_ID = "05192757-942f-460d-b4ff-004ec39cc5ee"

# Get complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 02")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 02
Source notes: 23
Source words: 2958
direct: 582 summary words
hierarchical: 484 summary words
rag: 477 summary words
rag_verification: 458 summary words

In [10]:
# ---------------------------------------------------------
# Clinician validation — Patient 02 document content
# ---------------------------------------------------------

PATIENT_LABEL = "Patient 02"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append("")

# Exact source notes — no editing or typo correction
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

patient_02_content = "\n".join(lines)

print(patient_02_content)

Patient 02

SOURCE CLINICAL RECORD

Clinical Note 1
Date/Time: 02/01/2026 07:50

Clerking Doctor
Dr. Marcus John Whitehead (SpR)

Presenting Complaint
Admitged for elective L THR due to end-stage OA and history of HTN.

Procedure
Total left hip replacement

On Examination
Pt alert, NAD. L hip: deformity noted, no erythema or warmth, tender on palpation. Limited ROM. Unable to fully bear weight on L side. LL neuro: intact. No sensory deficits. Motor function normal. Skin over surgical site intact, no signs of infxn.

Observations
HR 75
BP 142/88
RR 16
Temp 36.8
SpO2 98%

Investigations
Pre-op ECG showed normal siuns rhythm with no ischemic changes. BP noted to be mildly elevated (142/88 mmHg), consistent with the patient's history of HTN. Imaging reports not mentioned in the provided information.

Test Results
Mild anaemia (Hb 11.3 g/dL). Other routine bloods WNL.

Plan
1. Proceed with planned L THR as sched. 2. Maintain fasting pre-op. 3. Ensure anaesthetic team notified. 4. Post-op analgesia plan to be reviewed. 5. Monitor for anaemia post-op; consider iron replacement if Hb erops further. 6. Continue Paracetamol 500mg as needed and Calcium with Vitamin D supplements. 7. Monitor BP closely during peri-operative period due to history of HTN.

changes
True

description_of_changes
Added the patient's history of HTN to the Presenting Comp laint section. Included findings from pre-op tests (ECG and BP) in the Investigations section. Updated the Plan section to include continuation of the patient's current medications and monitoring of BP during the peri-operative period.


Dr. Marcus John Whitehead (Specialty Registrar)
GMC number: 1078759

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 02/01/2026 08:15

- Patient: Hope Chinwo, DOB 23/03/1 948, NHS No. 287904478, Elective Admission ID 05192757-942f-460d-b4ff-004ec39cc5ee
- Procedure: Total left hip replacement for end-stage OA
- Date of checklist: 02/01/26, time 08:15
- Checklist completed by Nurse Deborah Eva Dickinson at bedside
- Identity confirmed via wristband and verbal confirmation
- Surgical site verification: Left hip confirmed as correct site
- Fasting status: Patient confirmed to be fasting as instructed
- Jewellery: All jewellery and removable prostheses removed
- Allergies: None reported
- Current medications reviewed and reconciled: Paracetamol 500mg PRN, Calcium with Vitamin D supplements
- Hgb optimised post ferrous sulfate course; mild anaemia noted previously but stable
- BP elevated but consistent with known HTN, no acute concerns
- Anaesthetic assessment indicated suitability for spinal anaesthesia
- Patient verbalised understanding of the procedure, includingriskas and benefits, and consent was previously obtained
- Patient in stable condition and fit to proceed
- Ward: Orthopaedic Elective Ward 3A
- Bed location: A07
- Admitting Consultant: Dr. Jennifer Jemma Hussein
- Specialty: Trauma and Orthopaedics Service
- Expected length of stay: 4 days
- Decision: Cleared to proceed to theatre for surgery at 09:00 as scheduled
Nurse Deborah Eva Dickinson
NMC number: 96S0500B

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 02/01/2026 09:00

Surgeon
Dr. Deirdre FitzGerald

Assistant
Dr. Marcus John Whitehead

Anaesthetist
Not specified

Anaesthesia Type
Spinal anaesthesia

Procedure
Total left hip replacement Posterolateral approach to the left hip - Surgical site closed in layers - Skin closed with subcuticular sutures - Covered with sterile dresskng

Diagnosis
End-stage OA of the left hip

Findings
- Severe degenerative changes in the left hip joint noted, with significant cartilage loss
- Noevidence of infection or abnormal surrounding tissue

Tissue Removed
Left femoral head

Prostheses or Implants
Cemeented prosthetic implant placed in the L hip

Estimated Blood Loss
Approximately 150 mL

Complications
No intraoperative complications

Post-Operative Care
- Enoxaparin 40 mg SC once daily for thromboprophylaxis
- Early mobilisation with physio to commence later today
- Regular paracetamol 1g every 6h for postoperative pain management

Plan
- Send the removed femoral head for histological examination
- Monitor for signs of infection, VTE, or other complications


Dr. Deirdre FitzGerald (Surgeon)
GMC number: 1637147

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 02/01/2026 11:30

Pt: Hope Chinwo, 75F. Spinal anaes. Total L hip replacwment. PACU 11:30 02/01/26. Obs stable: BP 130/85, HR 72, RR 16, SpO2 98% RA. Pt alert, orient, comm. No N/V. No significant pain, mild discomfort reported, IV Paracetamol 1g given. Sx site: clean, dry, no bleed. Cleared for transfer to Ward 3A. Early mobilisation with physio planned for later in the day. Enoxaparin 40mg SC OD for thromboprophylaxis started. Care provided by Dr. Marcus J. Whitehead (SpR) and Nurse Deborah E. Dicokinson. Written by Dr. Marcus J. Whitehead (SpR).
Dr. Marcus John Whitehead (Specialty Registrar)
GMC number: 1078759

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 02/01/2026 14:00

Clinician Leading Ward Round
Dr. Jennifer Jemma Hussein (Consultant)

Presenting Complaint
Severe left hip pain seondary to end-stage OA hx noted thank you

Issues
1. Postoperative anaemia
-Hb 104 g/L
-Likely secondary to surgical blood loss

On Review
Patient reports mild pain at the surgical site (3/10) which is well-contorlled with paracetamol. No other complaints.

Investigations
No imaging performed since admission Hb: 104 g/L Other blood tests: No abnormalities detected

Observations
HR 72
BP 130/85
RR 16
Temp 36.9
SpO2 98% on room air

On Examination
- Patient alert and oriented to time, place, and person
- Surgical site dressing clean, dry, no signs of bleeding or infection
- Mild tenderness at the aurgical site; pain rated 3/10 by the patient

Plan
1. Start ferrous sulfate 200 mg once daily for postoperative anaemia 2. Initiate physio for miobilisation later today 3. Monitor Hb levels with repeat blood tests in 48 hours 4. Continue thromboprophylaxis with Enoxaparin 40 mg SC once daily


Dr. Jennifer Jemma Hussein (Consultant)
GMC number: 1318494

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 02/01/2026 16:00

Pt 75F, POD0 post LTHR (L). Init physio sess @16:00 w/ Hazel Kayleigh Barton (Physio). Mobilised aw/ walker. Focus: safe WB, adherence to hip precautions (no >90Â° flex, no leg crossing). Pt co-op. Mobilised short dist w/ support. Plan: daily physio to progress mob, build conf w/ aids.
Therapist Hazel Kayleigh Barton (Physical)

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 02/01/2026 18:00

- Contacted patient's GP, Dr. Panashe Dhlamini, at 18:90 to provide an update on post-op progress following total left hip replacement.
- Discussed surgery outcome, current condition, and recovery progress to ensure continuity of care.
- No immediate changes to Tx plan advised by GP.
- Communication documented for record.
Nurse Deborah Eva Dickinson
NMC number: 96S0500B

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 03/01/2026 08:30

Clinician Leading Ward Round
Dr. Marcus John Whitehead (SpR)

Presenting Complaint
End stage OA L hip

Issues
1. Post-op anaemia
-Hb 105 g/L, peri-operative cause
-No acute intervention needed

Today

On Review
Pain well-controlled on paracetamol. Mobilising with walker. No new complaints.

Investigations
Hb 105 g/L, no other abnormalities.

Observations
HR: 78
BP: 134/86
RR: 16
Temp: 36.9
SpO2: 98%

On Examination
Alert, cooperative. Wound clean, dry, nil erythema or discharge. No leg swelling. Mobilising short distances with walker, good adherence to hip precautions.

Plan
1. Encourage oral hydration and iron-rich diet. No new mseds. 2. Continue daily physio for mobilisation. 3. Continue enoxaparin 40 mg SC once daily for thromboprophylaxis. 4. Review Hb trend tomorrow.


Dr. Marcus John Whitehead (Specialty Registrar)
GMC number: 1078759

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 03/01/2026 10:00

10:00 03/01/26. Physio session with Therapist Hazel Kayleigh Barton. Focus: stair navigation. The patient practiced ascending and descending two steps usign a handrail anda walker. Therapist emphasized the importance of maintaining proper posture and balance during the activity. The patient demonstrated improved confidence and strength compared to the previous session. No issues with pain or safety were observed. Plan: Continue daily physio sessions. Progress to crutch use as tolerated. No new meds required.
Therapist Hazel Kayleigh Barton (Physical)

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 03/01/2026 12:00

Next of kin, Evelyn Chinwo, contacted via telephone to provide an update on Mrs. Chniwo's post-op progress. Discussed stable condition, effective pain control, physio progress, and anticipated discharge timeline. No concerns raised. No changes to treatment plan.
Nurse Lynn Catherine Watson
NMC number: 88V6142N

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 03/01/2026 14:30

- Assessment conducted at 14:30 by OT Clifford Alan Carr on 03/01/26, following total left hip replacement on 02/01/26.
- Focused on evaluating the patientâ€™s ability to perform ADLs post-surgery.
- Observed patient practicing:
  - Safe techniques for getting in and out of bed (minimal assistance required).
  - Reaching for objects on a counter while maintaining hip precautions.
 - Safe dressing techniques using adaptive strategies and minimal assistance.
- Provided education on hip precautions, including avoiding hip flexion beyond 90 degrees, internal rotation, and adduction.
- Reinforced importance of mobility aids in maintaining safety and reducing fall risk.
- Discussed strategies for maintaining independence at home dudring recovery.
- Recommended minor home adaptations:
  - Raised toilet seat.
 - Grab bars in the bathroom.
- Arrangements made for delivery of recommended home adaptations pror to ischarge.
- Patient demonstrated understanding of education provided and was cooperative throughout the session.
- Plan: Continued OT input to suppport recovery and maintain safety. Liaise with discharge team to confirm delivery and installation of home adaptations before discharge.
Therapist Clifford Alan Carr (Occupational Therapist)

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 04/01/2026 09:00

Clinician Leading Ward Round
Dr. Marcus John Whitehead (SpR)

Presenting Complaint
Severe left hip OA

Issues
1. Post-op anaemia
-Hb 105 g/L
-Likely peri-operative blood loss
-No acute intervention necessary

Today

On Review
Reports mild stiffness with mobilisation. Pian well-controlled with paracetamol. Adhering to physio.

Investigations
Hb 105 g/L. No other abnormalities.

Observations
HR: 72
BP: 130/85
RR: 16
Temp: 36.8
SpO2: 98%

On Examination
Alert, NAD. Wound clean, dry, no erythema or swelling. Mild stiffness on mobilising but cooperative. No signs of DVT.

Plan
1. Progress to crutches for mobilisation as part of physio. 2. No changes to meds. 3. Review tomorrow for further mobilisation progress.


Dr. Marcus John Whitehead (Specialty Registrar)
GMC number: 1078759

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 04/01/2026 11:00

Pt seen by Hazel Kayleigh Barton (Physio) at 11:00. Session focused on gait training with crutches. Therapist assessed pt's progress with walker-assisted mobilisation and determined readiness to advance to crutches. Emphasis on maintaining proper weight distribution and adherence to hip precautions. Pt transitioned fro m walker to crutches. Demonstrated good balance and cordination, no issues with adherence to precautions. Pt engaged and motivated. Plan: Continue with crutches for mobility. Further physio to build strength and confidence before discharge.
Therapist Hazel Kayleigh Barton (Physical)

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 04/01/2026 13:00

Dietitian Beatrice Sarah Hopkins reviewed nutritional status. Emphasised high-protein diet for wound healing and muscle recovery. Advised inclusion of lean meat, fish, eggs, legumes. Recommended supplements if appetite reains reduced.
Therapist Beatrice Sarah Hopkins (Dietry)

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 04/01/2026 15:30

- Patient reviewed on 04/01/26 at 15:30 by Clifford Alan Carr (OT) following total left hip replacement on 02/01/26.
- A hip kit, includng a reacher, sock aid, and long-handled shoehorn, provided to support ADLs while adhering to hip precautions.
- Demonstration conducted for the use of each tool, with emphasis on maintaining hip precwutions (e.g., avoiding felxion beyond 90Â° and adduction).
- Supervised patient practicing with the provided tools; patient demonstratedunderstanding and competency with minimal asistance required.
- Observed patient practidcing ADLs, including getting in and out of bed, reaching for objects, and dressing, with minimal assistance.
- Patient advised to continue utilising the hip kit at home to promote independence and minimise strain on the prosthetic hip joint.
- Recommended minor home adaptations, including a raised toilet seat and grab bars in the bathroom, to support recovery and reduce fall risk. Arrangements for delivery of these items to the patient's home have been made.
- No adverse issues identified during the session.
- No changes made to medication or current therapy plan.
Therapist Clifford Alan Carr (Occupational Therapist)

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 05/01/2026 08:00

Clinician Leading Ward Round
Dr. Marcus John Whitehead (SpR)

Presenting Complaint
Severe left hip OA

Issues
1. Post THR
-Wound clean, no erythema/discharge/swelling
-Mobilising well with crutches
2. Postop Anaemia
-Hb 10.8 g/dL
-Prescribed ferrous sulfate 200 mg OD
-High-iron diet advised

Today

On Review
Minimal pain, controlled with PRN paracetamol. Confident with ADLs.

Observations
HR: 76
BP: 132/86
RR: 16
Temp: 37.2
SpO2: 98% on RA

On Examination
Alert, comfortable. Wound clean, no erythema/sischarge/swelling. No calf tenderness or swelling. Mobilising well with crutches.

Plan
1. Discharge tomorrow with prophylactic rivaroxaban 10 mg OD x7 days. 2. Follow-up physio arragned. 3. Prescription for ferrous sulfate 200 mg OD for post-op anaemia. 4. Advise high-iron diet.


Dr. Marcus John Whitehead (Specialty Registrar)
GMC number: 1078759

--------------------------------------------------------------------------------

Clinical Note 17
Date/Time: 05/01/2026 09:30

Patient seen at 09:30 for final physio assessment. The session focuse on assessing the patient's ability to safely use crutches for ambulation, including practicing gait,standing up from a chair, and turning safely. A simulated home environment wasused to evaluate the patient's navigation of obstacles. The patient demonstrated good balance, coordination, and adherence to post-op hip precautions throughout the session, such as avoiding bending the hip beyond 90 degrees and crossing the legs. There were no gait abnormalities noted. Based on the assessment, the patient was deemed safe for independent discharge with crutches. Plan: Continue OP physio as scheduled. No medication changes required. - Hazel Kayleigh Barton, Physio
Therapist Hazel Kayleigh Barton (Physical)

--------------------------------------------------------------------------------

Clinical Note 18
Date/Time: 05/01/2026 11:00

- Discharge planning meeting conducted with pt and next of kin (Evelyn Chinwo, daughtefr).
- Consultant reviewed recoverry progress and provided post-op care instructions.
- Follow-up physio plan and OPD clinic appointments explained.
- Emphasised importance of hip precautions and continued use of crutches.
- Pt to be discharged home on 06/01/26 with follow-up arrangements in place.
Dr. Jennifer Jemma Hussein (Consultant)
GMC number: 1318494

--------------------------------------------------------------------------------

Clinical Note 19
Date/Time: 05/01/2026 16:00

- Provided patient with d/cc medications, including Paracetamol 500mg as needed for pain.
- Educated patient on proper wound care, medication schedule, and mobility precautions post-d/c.
- Reinforced the importance of adherence to d/c instructions and follow-up care plan.
- No new medications prescribed.
Nurse Kathleen Iris Brooks
NMC number: 06D2114T

--------------------------------------------------------------------------------

Clinical Note 20
Date/Time: 21/12/2025 10:00

Pre-clerking Doctor
Dr. Brian Anthony Payne (FY1)

Presenting Complaint
Severe left hip pain due to end-stage OA.

Procedure
Total left hip replacement

History of Presenting Complaint
Site: Left hip Onset: Gradual, worsening over past 5 yrs Character: Deep, aching painRadiates: None Associations: Limited mobility, stiffnes, mild fatigue Timing: Constant, worse w/ prolonged standing/walking Exacerbating factors: Weight-bearing, activity Severity: 8/10

Past Medical History
- HTN
- OA (severe, left hip)
- Cataract surgery (2018)

Medications
- Paracetamol 500mg PRN
- Calcium w/ Vit D supplements

Allergies
None

Social History
- Lives alone in ground-floor flat
- Mobilises w/ stick indoors, frame outdoors
- Independent in ADLs but slow
- Non-smoker, noalcohol, no recreational drugs
- Retired teacher

Family History
Mother: HTN Father: T2DM

On Examination
Looks well, no distress. CVS: HS I + II + 0, no murmurs. Resp: Chest clear, good air entry bilat. No wheeze/crackkles. Abdo: Soft, non-tender, no masses. L hip: Pain on palpation and ROM. Severe restriction in flexion and int rot. No redness/swelling. LL: Pulses palpable bilat. No oedema. No signs of DVT. Neuro LLs: Power 4/5 L hip flex/ext due to pain. Sensation intact bilat.

Observations
HR 78
BP 145/85
RR 16
Temp 36.9
SpO2 97%

Investigations
ECG: NSR, no ischaemic changes

Test Results
Hb: 11.3 g/dL (mild anaemia) WCC, platelets, renal fx: Normal LFTs: Normal

Plan
- Start ferrous sulfate 200 mg OD for anaemia
- Contact GP for BP monitoring andoptimisation
- Proceed w/ elective total L hip replacement as planned
- Pre-op anaesthetic review on admission day


Dr. Brian Anthony Payne (Foundation Trainee)
GMC number: 1907255

--------------------------------------------------------------------------------

Clinical Note 21
Date/Time: 21/12/2025 11:30

Pt: Hope Chinwo, 75F (NHS: 287904478). Elective L THR for end-stage OA. Seen 221/12/25 @ 11:30.

PMHx: HTN, OA (severe L hip), cataracts (surg 2018). No recent SOB/CP. Mild fatigue noted (consistent with pre-op assessment). BP 145/85. Hb 11.3 (mild anaemia, on FeSO4). ECG: NSR, no isch changes.

Meds: Paracetamol PRN, Ca+Vit D supps, FeSO4 200mg OD.

Allergies: NKDA.

Anaest hetic plan: Pt found suitable for spinal anaesthesia; no contraindications identified. Procedure, risks, and benefits explained to pt. Pt consents. No med changes reqâ€™d.

Staff: Dr. Marcus John Whitehead (SpR).
Dr. Marcus John Whitehead (Specialty Registrar)
GMC number: 1078759

--------------------------------------------------------------------------------

Clinical Note 22
Date/Time: 21/12/2025 12:15

Patient: Hope Chinwo, 75-year-old female, DOB 23/03/48, NHS No: 287904478, MRN: 712349860.


In [11]:
# ---------------------------------------------------------
# Clinician validation — Patient 03
# ---------------------------------------------------------

PILOT_PATIENT_ID = "ebb1ca4c-f42f-41d8-adbc-1b08949036d1"

# Get complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 03")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 03
Source notes: 22
Source words: 3436
direct: 418 summary words
hierarchical: 512 summary words
rag: 326 summary words
rag_verification: 326 summary words

In [14]:
# ---------------------------------------------------------
# Clinician validation — Patient 03 document content
# ---------------------------------------------------------

PATIENT_LABEL = "Patient 03"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_03_content = "\n".join(lines)

print(patient_03_content)

Patient 03

SOURCE CLINICAL RECORD

Clinical Note 1
Date/Time: 06/01/2026 09:05

Clerking Doctor
Dr. Laurence Walter Green (Consultant)

Presenting Complaint
Elective admission for correction of left distal femoral growth plate abnormality. History of recurrent knee pain and gait abnormality.

Procedure
Hemiepiphysiodesi s of the left distal femur

On Examination
- Alert, cooperative, and well-appearing 8-year-old female. No signs of distress.
- Left knee: No erythema, swelling, or effusion. No signs of infection at the surgical site. Skin intact with no abnormal findings. No tenderness on palpation. Full passive ROM noted.
- General physical examination: CVS, resp, and abdo systems unremarkable. No pallor, jaundice, or lymphadenopathy.
- Fasting status: Cofirmed fasting as per pre-op protocol.
- No allergies or current meds as per pre-op checklist.

Observations
HR 88
BP 102/68
RR 18
Temp 36.7
SpO2 99%

Investigations
No imaging or ECG performed on admission. Pre-op imaging reviewed previously with no new imaging required at this stage. - Pre-op FBC on 04/01/26: Hb 12.3 g/dL (improved from previous 10.9 g/dL following treatment with o ral ferrous sulfate), WCC and platelets within normal limits. - U&Es: Normal. LFTs: Normal. Coagulation profile: Normal. - No pending results.

Plan
- Proceed with planned Hemiepiphysiodesis of the left distal femur as scheduled.
- Ensure administration of IV paracetamol intraoperatively for pain control.
- Administer ondansetron intraoperatively for nausea prophylaxis.
- Maintain standard postoperative monitoring and care.
- Discharge anticipated in 3 days post-op if recovery is uneventful.


Dr. Laurence Walter Green (Consultant)
GMC number: 1488588

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 06/01/2026 11:00

Surgeon
Dr. Uchenna Eze

Assistant
Dr. Laurence Walter Green

Anaesthetist
Dr. Graham Gerald Frost

Anaesthesia Type
GA

Procedure
Hemiepiphysiodesis of the left distal femur Lateral aspect, left distal femur Sterile occlusive dressnig applied over incision post-layered sutures

Diagnosis
Angular deformity, left knee

Findings
No evidence of infection or significant inflammation. Growth plate intact.

Tissue Removed


Prostheses or Implants
Guided growth plate tether

Estimated Blood Loss (EBL)
Minimal (<10 mL)

Complications
None

Post-Operative Care
Prescribe oral paracetamol 250 mg QDS for pain relief. Prescribe ibuprofen 200 mg TDS for additional analgesia. Administer enoxaparin 20 mg SC OD as DVT prophhlaxis. Plan mobilisation with physio later today.

Plan
Send the guided growth plate tether to histology for analysis. Document that the patient was extubated in the operating theatre and transferred tothe PACU in stable condition.


Dr. Uchenna Eze (Surgeon)
GMC number: 1782060

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 06/01/2026 13:30

PACU. Victoria Edith Axams (8F) was transferred post hemiepiphysiodesis (L distal femur) on 2026-01-06 at 13:30. GA uneventful. Initial SpO2 drop to 92%, resolved with O2 (NC 2L/min). CV stable throughout. Pain managed with IV paracetamol 300 mg + morphine 1 mg. Awake, alert, and communicating within 30 minutes. Prescribed oral ibuprofen 100 mg TDS for ongoing pain. Cleared for transfer to the Paediatric Orthopaedic Ward. PACU care xonucted by Dr. Ying Liu (SpR) and Nurse Edward Richard Hayes.
Dr. Ying Liu (Specialty Registrar)
GMC number: 1687711

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 06/01/2026 15:30

Clinician Leading Ward Round
Dr. Laurence Walter Green (Cons), Dr. Ying Liu (SpR)

Presenting Complaint
Gait abnormality and recurrent L knee pain

History of Presenting Complaint
hx noted thank you

Issues
1. Left distal femur angular deformity
-Post-operative recovery after hemiepiphysiodesis
-Mild drop in haemoglobin to 104 g/L attributed to minor blood loss during surgery

On Review
- Patient alert, comfortable, and cooperative
- Pain well-controlled with oral paracetamol and ibuprofen
- No additional complaints from patient or parent
- Parent present during ward round

Investigations
- No new imaging or ECG since admission
- Hb 104 g/L (mild drop post-op, pre-op 128 g/L)
- All inflammatory markers within normal limits

Observations
HR 92
BP 112/68
RR 18
Temp 36.8
SpO2 98% on room air

On Examination
- Patient alert, comfortable, afebrile
- Surgical site: clean with mild swelling, no erythema, no discharge, no signs of infection
- Surgical site dressed with sterile occlusive dressing
- Palpation: mild tenderness at surgical site, no abnormal warmth or fluctuance
- Pain: well-controlled, no significa nt discomfort during gentle assisted movement
- Left leg/knee: limited ROM post-operatively, mobilisation not yet initiated

Plan
- Prescribe oral tranexamic acid 500 mg TDS for 3 days to reduce post-op bleeding
- Initiate early physiotherapy to begin mobilisation
- Statr enoxaparin 20 mg SC OD for 2 days as DVT prophylaxis


Dr. Laurence Walter Green (Consultant)
GMC number: 1488588

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 06/01/2026 17:00

Patient Name: Victoria Edith Adams (DOB: 14/06/2015, NHS No: 730649569)

- Date of session: 06/01/26
- Timeof session: 17:00
- Therapist: Hilary Teresa Chapman (PT)
- Reason for therapy: Post-op rehab following hemiepiphysiodesis of the left distal femur.

Therapy session details:
- Focused on light mobilisation exercises to facilitate recovery and prevent complications.
- Conducted assisted leg movements and seated ROM exercises targeting the left leg.
- Incorporated deep breathing exercises to aid in circulation and reduce risk of post-op complications (e.g., DVT).
- The patient participated actively and tolerated the sessionwell without significant discomfort.
- No adverse events or complications noted during the session.

Plan:
- Initiate supervised walking with assistance during the next scheduled physio session.
- Continue current pain management plan with oral paracetamol and ibuprofen as prescribed.
- Prescribed prophylactic enoxaparin 20 mg SC once dailyfor DVT prevention.
- Monitor surgical site and overall mobility during subsequent sesions.
Therapist Hilary Teresa Chapman (Physical)

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 06/01/2026 18:30

- Educated patient's mother, Emily Jane Adams, on post-op wound care.
- Instructions included keeping surgical site clean and dry, idntifying signs of infection, and appropriate use of prescribed paracetamol.
- No changes to meds or treatment plan made during this event.
Nurse Terry Stanley Lowe
NMC number: 87E8903E

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 07/01/2026 08:30

Clinician Leading Ward Round
Dr. Ying Liu (SpR)

Presenting Complaint
Recurrdent knee pain and angular deformity of left distal femur

Issues
1. Angular deformity of left distal femur
-Post-operative day 1
-Mild Hb drop to 104 g/L (pre-op 128 g/L)
-Surgical woud clean and healing well

Today

On Review
Feels ok, mild stiffness in left knee. Pain well-controlled with oral paracetamol.

Investigations
Bedside mobilitty progress noted; able to stand briefly with assistance. Mild Hb drop to 104 g/L (pre-op 128 g/L).

Observations
HR: 92
BP: 108/72
RR: 18
Temp: 37.1
SpO2: 98% on RA

On Examination
Alert, comfortable. L knee dressing intact, no erythema or discharge. Mild swelling noted. Wound clean, dry, an d healing well. Able to bear minimal weight with assistance.

Plan
1. Transition from paraccetamol to ibuprofen 200 mg TDS. 2. Physio session later today for assisted walking. 3. Review Hb tomorrow; consider further managemenyt if no improvement. 4. Monitor wound for infection or increased swelling. 5. Update patient's mother, Emily Adams, about the condition and progress.


Dr. Ying Liu (Specialty Registrar)
GMC number: 1687711

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 07/01/2026 10:00

- Date: 07/01/26, Time: 10:00
 - Therapist: Hilary Teresa Chapman (Physio)
 - Focus of session: Supervised walking with a Zimmer frame to improve mob ility and confidence post-Hemiepiphysiodesis of the left distal femur.
 - Exercises performed:
   - Guided weight-bearing exercises to promote progressive loading of the left leg.
   - Short-distance walkin with Zimmer frame assistance, focusing on balance and coordination.
 - Observations:
   - Patient was cooperative and engaged throughout the session.
   - Demonstrated ability to bear weight on the left leg with support.
   - Balance was maintained with minimal therapist intervention, though confidence remains limited.
 - Pain assessment:
   - No significant increase in pain reported during or after the sessio.
   - Pain remains well-controlled with current analgesics (oral paracetamol and ibuprofen, continued form previous orders).
 - Recommendations:
   - Continue twice-daily physio sessions to progress towards independent mobilisation with crutches.
   - Monitor for any signs of discomgort or overuse during exercises.
 - Next steps:
   - Plan to introduce crutch-assisted walking as confidence and strength improve.
   - Reassess progress during the next session.
Therapist Hilary Teresa Chapman (Physical)

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 07/01/2026 11:30

Staff
Dr. Divya Gupta, Consultant, Infectious Diseases; Dr. Ying Liu, Specialty Registrar, Infectious Diseases

Additional Clinical History
Recurrent knee pain and gait abnormality.

Issues
1. Post-operative superficial wound infection
-Mild erythema and warmth at the surgical site
-CRP 18 mg/L (slightly elevqted)
-No evidence of deep infection

Safety Alerts
None

Medications
Flucloxacillin 250 mg TID for 5 days, Paracetamol 250 mg QDS, Ibuprofen 200 mg TDS, Enoxaparin 20 mg SC once daily, Tranexamic acid 500 mg TID for 3 days.

Physical Examination
Alert, interactive and comfortable. WSurgical site on the left distal femur shows mild erythema and warmth. No purulence, drainage, or fluctuation. No signs of systemic infection. Other systems unremarkable.

Test Results
CRP 18 mg/L. Other blood tests normal.

Investigations
No imaging studies performed. CRP result reviewed as part of the assessment.

Future Orders
Monitor wound site for progression of erythema or infection. Continue CRP monitoring if clinical condition changes.

Care Plan Outcomes
Initiated prophylactic flucloxacillin 250 mg TID for 5 days. Advised continued monitoring of the wound site for signs of infection. No further ID intervention required unless signs of deep infection develop.


Dr. Divya Gupta (Consultant)
GMC number: 1724300

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 07/01/2026 14:00

- Dietitian review conducted by Therapist Janet Sophie Abdi.
- Dietary recommendations provided to support post-op healing.
  - Emphasis on protein-rich foods, adequate hydration, and foods high in vitamin C for tissue repair.
- No changes to currrent meds.
- Advised incorporation of dietary recommendations int o meals during hospital stay.
Therapist Janet Sophie Abdi (Dietary)

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 07/01/2026 15:30

Therapy session conducted on 2026-01-07 at 15:30 by Therapist Hilary Teresa Chapman (Physical).

- Focus of session: Post-operative stair climbing practice and improving ROM in the left kne following hemiepiphysiodesis surgery.
- Activities perfotrmed:
  -Step-by-step guidance provided for safe ascent and descent of stairs using crutches post-surgery.
  - Targeted stretching exercises to improve flexibility and reduce stiffness in the left knee.
- Patient progress:
  - Demonstrated good understanding of stair climbing technique.
  - Managed partial WB on the left leg with crutches under supervision.
  - Mild stiffness noted in the left knee, which improved following stretching exercises.
- Next steps:
  - Patient encouraged to continue practicing stair climbing under supervision during subsequent sessions.
  - Plan to progress to more advanced WB exercises as tolerated.
- No new medications prescribed or dajustments made at this time.
Therapist Hilary Teresa Chapman (Physical)

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 07/01/2026 17:00

Clinician Leading Ward Round
Dr. Ying Liu (SpR)

Presenting Complaint
Recurrent knee pain

Issues
1. Post-operative recovery following hemiepiphysiodesis (left distal femur)
-Stable pain control with oral analgesics
-Good progress with assisted mobilisation
-Surgical site lean and healing well

Today

On Review
Feeling comfortable. Pain well controlled.

Investigations
None performed during the ward round. CRP elevated at 18 mg/L. Hb dropped to 104 g/L. WC normal.

Observations
HR: 92
BP: 12/68
RR: 18
Temp: 37.1
SpO2: 98% RA

On Examination
Patient alert and comf ortable. Surgical site examined and noted to beclean, dry, and healing well, with no signs of infection, erythema, swelling, or discharge. The patient showed satisfactory progress in mobility, standing briefly with assistance. Remainder of the examination was unremarkable.

Plan
1. Reduce paracetamol toPRN. 2. Continue ibuprofen 200 mg TDS for anti-inflammatory effect. 3. Encourage independent mobilisation with cutches during the next scheduled physio session. 4. Monitor wound for signs of infection and review CRP trend tomorrow. 5. Start flucloxacillin 250 mg TDS for 5 days as prophylaxis against superficial infection.


Dr. Ying Liu (Specialty Registrar)
GMC number: 1687711

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 08/01/2026 08:15

Clinician Leading Ward Round
Dr. Ying Liu (SpR)

Presenting Complaint
Gait abnormality

Issues
1. Post-operative monitoring for superficial surgical site infection (prophylactic antibiotics initiated)
-Slighr erythema and warmth at the surgical site
-CRP 18 mg/L
-Flucloxacillin 250 mg TID started

Today

On Review
Mild discomfort on movement. Feels confident mobilising with crutches.

Investigations
None

Observations
HR: 88
BP: 112/74
RR: 16
Temp: 37.2
SpO2: 97%

On Examination
Alert, comfortable. Wound site clean, dry, no discharge. Mild swelling noted at L knee with slight erythema and wramth. No tenderness beyond surgical site.

Plan
1. Cease IV paracetamol. Start oral ibuprofen 10 mg/kg TDS. 2.Final physio session today to assess independent mobilisation w/ crutches. 3. Start flucloxacillin 250 mg TID for 5 days. 4. Monitor wound for progression of erythema or other signs of infection. 5. D/C planning post-physio review if stalbe.


Dr. Ying Liu (Specialty Registrar)
GMC number: 1687711

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 08/01/2026 10:00

Patient: Victoria Edith Adams, 8-year-oldd female, post-op Hemiepiphysiodesis of left distal femur on 06/01/26.

- Final physio session conducted on 08/01/26 at 10:00 by Therapist Hilary Teresa Chapman.
- Focus of session: Ensuring safe and independent mobilisation with crutches.
- Activities included:
  - Practicing walking on flat surfaces.
  - Maneuvering around obstacles.
  - Transferring from sitting to standing without assistance.
  - Assessment of balance, strength, and confidence jn crutch use.
- Therapist provided positive feedback on tehnique and made minor adjustments to crutch handling.
- Patient demonstrated good stability, coordination, and confidence during exercises.
- No pain or discomfort reported during the session.
- Therapist confirmed patient is safs for independent mobilisation with crutches.
- Recommendation: Continued use of crutches for the next four weeks.
- Plan to arrange follow-up physio post-discharge to assess progress and determine further rehab needs.
Therapist Hilary Teresa Chapman (Physical)

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 08/01/2026 11:30

- Discharge medications provided: paracetamol 250 mg (every 6 hours as needed for pain) and ibuprofen 100 mg (every 8 hours with food) for 7 days.
- Instructions for medication use, crutch handling, and wound care explained to the patietnâ€™s mother, Emily Jane Adams.
- Patient and mother verbalised understannding of instructions.
- No additional concerns raised during this interaction.
Nurse Jason Neil Warren
NMC number: 57O5988R

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 08/01/2026 14:00

Therapist Michael Harold Morrison conducted a SALT session with Victoria Edith Adams (8-year-old female) on 08/01/26 at 14:00 to assess post-operativecommunication and swallowing function following Hemiepiphysiodesis of the left distal femur.

ABCDE Assessment:
A. Airway patent, no stridor or obstruction noted during swallowing assessment.
B. Breathing normal, no signs of distress or aspiration during oral intake trials.
C. Circulation stable, no cyanosis or other abnormalities observed.
D. Disability: Neurological function intact; able to follow instructions and communicate appropriately.
E. Exposure: No overt signs of surgical complications or o thedr systemic concerns.

Key findings: Clear articulation, no dysarthria or phonatory issues. Swallowing assessment demonstrated safe and effective oral transit with no evidence of aspiration or dysphagia. Oral motor skills were also evaluated, with no abnormalities identified.

Next steps: No further SALT sessions required. Advised mother ot monitor for any swallowing difficulties post-discharge and consult GP if concerns arise. Both Victoria and her mother were reassured regarding her progress and recovery.
Therapist Michael Harold Morrison (Speech and Language)

--------------------------------------------------------------------------------

Clinical Note 17
Date/Time: 08/01/2026 16:30

Clinician Leading Ward Round
Dr. Ying Liu (SpR)

Presenting Complaint
Gaitabnormality

Issues
1. Growth Plate Dysfunction - Left Distal Femur
-Postoperative Hremiepiphysiodesis
-Wound clean, no erythema or discharge
-Mobilising effectively with crutches

Today

On Review
Pt comfortable. Pain well-controlled with current regime. Mobilising with vrutches effectively.

Investigations



Observations
HR: 88
BP: 110/70
RR: 16
Temp: 36.7
SpO2: 98% on air

On Examination
Alert, calm, no distress. Wound clean, no erythema or discharge. Dresing intact. No excessive swelling. Mobilising safely with crutches.

Plan
1. Discharge today with 14-day supply of paracetamol 250 mg q6h PRN 2. Discharge today with 7-day supply oof ibuprofen 100 mg q8h with food 3. Advise follow-up physio as outpatient 4. Eeducate on wound care and signs of infection


Dr. Ying Liu (Specialty Registrar)
GMC number: 1687711

--------------------------------------------------------------------------------

Clinical Note 18
Date/Time: 08/01/2026 18:00

- Contacted patientâ€™s GP, Dr. Farai Nkomo, at 18:00 to provide discharge summary.
- Summary included details of Hemiepiphysiodesis procedure, post-op recovery progress, and follow-up plan.
- GP adviseed to review patient in 6 weeks following the scheduled ortho clinic appointment.
Nurse Jason Neil Warren
NMC number: 57O5988R

--------------------------------------------------------------------------------

Clinical Note 19
Date/Time: 28/12/2025 10:00

Pre-clerking Doctor
Dr. Katie Grace Begum (FY1)

Presenting Complaint
Recurrent L knee pain, gait abn.

Procedure
Hemiepiphysiodesis of the left distal femur


In [15]:
# ---------------------------------------------------------
# Clinician validation — Patient 04
# ---------------------------------------------------------

PILOT_PATIENT_ID = "6e93f9d9-213d-4f2c-a1f0-f475dacef554"

# Complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 04")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 04
Source notes: 34
Source words: 3867
direct: 453 summary words
hierarchical: 496 summary words
rag: 467 summary words
rag_verification: 467 summary words

In [16]:
# ---------------------------------------------------------
# Clinician validation — Patient 03 document content
# ---------------------------------------------------------

PILOT_PATIENT_ID = "6e93f9d9-213d-4f2c-a1f0-f475dacef554"
PATIENT_LABEL = "Patient 04"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_03_content = "\n".join(lines)

print(patient_03_content)

Patient 04

SOURCE CLINICAL RECORD

Clinical Note 1
Date/Time: 02/01/2026 09:00

Pre-clerking Doctor
Dr. Donna Hayley Harvey (SpR)

Presenting Complaint
Scoliosis requiring corrective surgery.

Procedure
Posterior spinal fusion for scoliosis.

History of Presenting Complaint
Pt initially noticed uneven shoulders ~2 yrs ago. Gradual worsening w/ noticeable curvature of spine. No pain reported. Denies weakness, numbness, or bowel/bladder sx.

Past Medical History
Juvenile idiopathic scoliosis

Medications
Ferrous sulfate 200 mg OD (started today to optimise Hb levels due to borderline Hb of 11.5 g/dL).

Allergies
- Aspirin

Social History
- Lives w/ parents.
- Fully independent in ADLs.
- Non-smoker. No alcohol. No recreational drug use.
- Active, paticipates in school sports.

Family History
- No FHx of scoliosis or connective tissue disorders.
- No significant FHx of other conditions.

On Examination
Alert, aell-appearing 13 y/o F (Katie Catherine Kaur). - Gen: NAD, well-developed, no signs of distress. - Spine: Thoracolumbar scoliosis noted, R thoracic prominence on forward bend. No tenderness. - Neuro: LL normal power, tone, reflexes. Sensation intact bilaterally. Normal gait. - Resp: Chest wall symmetrical. BS vesicular, no added sounds. - CVS: HS dual, no murmurs. - Airway: Mallampati II, normal neck ROM, good dentition.

Observations
HR 78
BP 112/68
RR 16
Temp 36.6
SpO2 99%

Investigations
CXR ordered pending.

Test Results
- FBC: BHb 11.5 g/dL, WCC and plts normal.
- U&E: Normal.
- Clotting: Normal.

Plan
1. Start ferrous sulfate 200 mg OD to optimise Hb pre-op due to borderline Hb (11.5 g/dL). 2. Await CXR results to assess lung health. 3. Proceed w/ planned posterior spinal fusion on 04/01/26. 4. Anaesthetic team to review airway pre-op.


Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 02/01/2026 10:30

Pt: Katie Catherine Kaur, 13F. NHS: 728400411. Elective PSF for JIS. Admitting cons: Dr. Z Qureshi.

Hx:JIS. No other sig PMHx. No reg meds. NKDA except aspirin (reviewed during assessment). Pre-op Hb 11.5 g/dL (borderline; on FeSO4 200 mg OD to optimize levels for surgery). Baseline RFT/clotting WNL. CXR pre-op: NAD, ordered earlier to assess lung health.

Exam: Airway Mallampati I. Good neck ROM, no sig anatomical abnormalities. CVS: HR 78, BP 110/70, dual HS, no murmurs. Resp: NAD, clear BS, sats 98% RA. Wt: 48 kg.

Plan: GA w/ intraopneuromonitoring. Premed oral midazolam 7.5 mg on morning o surgery for anxiolysis. Fasting: NBM from midnight (water until 06:30 day of surgery). Discussed anaesthetic process w/ pt & mother incl risks (PONV, sore throat, rare complications). Questions addressed.

Reviewed by: Dr. Donna Hayley Harvey (Spec Reg), 02/01/26, 10:30.
Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 02/01/2026 11:15

02/01/26, 11:15. Pt: Katie Catherine Kaur, 13F, NHS: 728400411. Dx: JIS. Ptroc: Posterior spinal fusion (04/01/26). Discussed w/ pt + mohter (legal guardian). Surgeon: Dr. Georgina Clara Johnson. Goals: improve spinal alignment, prevent scoliosis progression. Risks explained: infxn, nerve injury, blood loss. Benefits: spinal alignment, prevent scoliosis progression. Qs from mother re recovery + post-op care addressed. Written consent obtained from mother, Sukhdeep Kaur. No new meds directly prescribed during the consent meeting (note: premedication with oral midazolam 7.5 mg was previously prescribed as part of the anaesthetic plan). Proceed w/ pre-op checklist. Fasting + premed instructions reinforced. Plan: GA w/ intraop neuromonitoring. Pt aware of fasting + premed instructions.
Dr. Georgina Clara Johnson (Surgeon)
GMC number: 1248141

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 02/01/2026 11:45

Pt: Katie Catherine Kaur, 13F. NHS No: 728400411. MRN: 403643861. DoB: 14/03/10.

Proc: Posterior spinal fusion for scoliosis. Elective. Admit date: 04/01/26.

Allergies: Aspirin.

Hx: Juv idiopathic scoliosis. No other PMHx noted.

Meds: Ferrous sulfate 200 mg OD added post pre-op assess. No other reg meds.

Consent: Written consent obtained 02/01/26. Signed by legal guardin (mother, Sukhdeep Kaur). Risks/benefits discussed by Dr. G.C. Johnson.

Anaes Plan: GA w/ intraop neuromonitoring. Pre-op fasting confirmed. Premed oral midazolam (7.5 mg) prescribed for AM of surgery. No concerns noted during anaes assess (02/01/26).

Baseline Inv: FBC: Hb 11.5 g/dL. Renal fxn, clotting WNL. CXR reviewed: no abnormalities.

Fasting: Confirmed adhered to instructions. Last solids 20:00, clear fluids 06:00.

Ward:Ortho Ward - Exeter Gen Hosp. Bed loc: B03.

Saff: Pre-op checklist completed by Dr. Donna Hayley Harvey on 02/01/26 at 11:45.

Decision: Cleared for surgery. No changes to prep plan. No new meds started/stopped.
Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 04/01/2026 08:30

Clerking Doctor
Dr. Donna Hayley Harvey (SpR)

Presenting Complaint
Elective admission for scoliosis correction.

Procedure
Posterior spinal fusion for scoliosis.

On Examination
Alert, NAD. Resp: Chest clear, no wheeze, no crackles. No signs of URTI. Surg site: No erythema, swelling, or discharge in thoracic/lumbar region. MSK: Thoracic curve visible with asymmetry of shoulders, posture upright. Full ROM in upper/lower limbs. No tenderness over spine.

Observations
HR 78 bpm
BP 112/72 mmHg
RR 16 br/min
Temp 36.8Â°C
SpO2 98% on RA

Investigations
CXR reviewed: NAD.

Test Results
Pre-op bloods (FBC, U&E, clotting) from 02/01/26 reviewed: all WNL. Hb 11.5 g/dL, borderline but optimised with ferrous sulfate. CXR reviewed: NAD.

Plan
1. Proceed with posterior spinal fusion as planned.
2. Maintain fasting state.
3. Admin oral midazolam 7.5 mg pre-op.
4. Monitor postop for pain, infxn, and neuro deficits.
5. Note patientâ€™s aspirin allergy.


Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 04/01/2026 10:00

Clinician Leading Ward Round
Dr. Zainab Qureshi (Consultant)

Presenting Complaint
Planned posterior spinal fusion for scoliosis

History of Presenting Complaint
hx noted thank you

Issues
1. Juvenile Idiopathic Scoliosis
-Planned posterior spinal fusion surgery
2. Mild Anaemia
-Hb 10.5 g/dL
-Likely related to age and underlying condition

On Review
- No new complaints from patient
- Patient feeling well and ready for surgery
- Risks and benefits of the procedure were briefly reiterated to Katie and her mother, ensuring they had no further questions

Investigations
- No new imaging or special investigations since admission
- Hb 10.5 g/dL
- Othrer results within normal limits

Observations
HR 88
BP 112/70
RR 16
Temp 36.8
SpO2 98% on air

On Examination
- Alert, cooperative, and oriented
- No pallor or signs of fatigue observed
- Skin intact with no signs of infection or contraindications for surgery
- CVS and RS unremarkable
- Fit for surgery based on clinical examination

Plan
- Proceed with posterior spinal fusion surgery at 13:00
- Administer pre-op IV cefuroxime 1.5 g, as prescribed during the ward round, to reduce risk of SSI


Dr. Zainab Qureshi (Consultant)
GMC number: 1151911

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 04/01/2026 13:00

Surgeon
Dr. Georgina Clara Johnson

Assistant
Dr. Donna Hayley Harvey

Anaesthetist
Dr. Donna Hayley Harvey

Anaesthesia Type
GA with intraop neuromonitoring

Procedure
Posterior spinal fusion Midline posterior thoracolumbar Layered closurr with absorbable sutures

Diagnosis
Juvenile idiopathic scoliosis

Findings
Thoracolumbar spinal curvature consistent with pre-op imaging. Curvature was corrected during the procedure. No signs of inflammation or infection.

Tissue Removed


Prostheses or Implants
Titanium pedicle screws + rods

Estimated Blood Loss (EBL)
350 mL

Complications
None

Post-Operative Care
IV cefuroxime 1.5 g TDS x 48 hrs for infection prophylaxis. Start IV paracetamol 1 g QDS for pain mgmt. Reassess pain control + mobility in 24 hrs. Start physio next AM.

Plan
Send specimens to histology for analysis.


Dr. Georgina Clara Johnson (Surgeon)
GMC number: 1248141

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 04/01/2026 17:30

Pt: Katie Catherine Kaur, 13F. Posterior spinal fusion for scoliosis. Time in PACU: 17:30. Transferred post-GA. Drowsy but rousable to verbal stim. CVS: Stable. HR 88, BP 112/68.RR 14. SpO2 98% on 2L O2 via nasal cannula. Resp effort normal. Pain: Controlled via PCA morphine. VAS: 3/10. Sedaion score: 2. PCA instructions relayed to pt. Surgical site: Dressing dry, intact. No signs of bleed/infection or other immediate complications. IV fluids: 0.9% NaCl at 85 ml/hr running. Foley in situ, draining clear urine. Outputs WNL. Meds: PCA morphine commenced. IV Cefuroxime 750 mg TDS started. Regular IV paracetamol 1 g QDS initiated. Plan: Cont PCA for pain. Maintain IV ABx as charted. Monitor vitals 2-hrly. Mobilise w/ physio tmrw. If stable, transfer to ortho ward overnight. Staff: Dr. Donna Hayley Harvey (SpR), Obs monitored by Nurse Yan Quan.
Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 05/01/2026 08:30

Clinician Leading Ward Round
Dr. Donna Hayley Harvey (SpR)

Presenting Complaint
Juvenile Idiopathic Scoliosis

Issues
1. Post-op Pain
-Moderate pain around surgical site
-Controlled with prescribed analgesics
2. Post-op Wound Healing
-No signs of infection
-Dressing intact
-Minimal serous discharge

Today

On Review
Pt reports moderate pain around surgocal site. No other complaints.

Investigations
Focused wound inspection performed showing no signs of infection
No new lab results were available

Observations
HR: 88
BP: 112/67
RR: 14
Temp: 36.8
SpO2: 98%

On Examination
The patient was alert and appeared comfortable. The wound dressing was intact with minimal serous discharge. There wwere no signs of erythema, swelling, or infection around the surgical site. Chest was clear on auscultation. Abdomen was soft and non-tender. Neurological examination of the lower limbs showed no deficits.

Plan
1. Paracetamol 500 mg QDS + Oramorph 2.5 mg PRN for pain
2. Start physio today; encouage mobilisation
3. Review progress tomorrow


Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 05/01/2026 10:00

Patient attended their first post-op physiotherapy session at 10:00. Focus was on breathing exercises for lung expansion and prevention of post-op complications. Bed-to-chair transfer training was initiated. Patient was educated on maintaining good posture and avoiding twisting or bending to protect the surgical site. Patient was engaged and followed instructions well. Plan: Progress to assisted walking exercises during the next physio session on 2026-01-06 at 10:00. Therapist: D aniel Jesse Ashton (Physio).
Therapist Daniel Jesse Ashton (Physical)

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 05/01/2026 15:00

OT session conducted on 05/01/26 at 15:00 by Therapist Anne Audrey Field. Focused on post-op functional assessment and training.

- Patient deonstrated ability to sit upright in a chair with minimal discomfort. Maintaining good posture was emphasised.
- Reaching task assessment: Patient was able to reach for objects on bedside table with limited ROM but no major difficulty observed.
- Eating assessment: Patient successfulky used utensils for eating; no additional support required.
- Bed-to-chair transfer: Patient  managed transition with minimal assistance, adhering to post-op movement restrictions (avoiding twisting and bending).

Recommendations:
- Follow-up session to focus on practising safe transfers and other ADLs.
- No new meds prescribed.
- Encouragement provided to continue adhering to post-op movement precautions.
Therapist Anne Audrey Field (Occupational)
GMC number: 1407117

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 05/01/2026 17:00

- Provided post-op care education to patient and mother. - Covered movemwnt precautions to protect surgical site and prevent complications. - Advised adherence to movement restrictions and scheduled physio sessions. - No changes to meds or treatments made.
Nurse Martin Cecil Bell
NMC number: 71D8152I

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 06/01/2026 08:30

Clinician Leading Ward Round
Dr. Donna Hayley Harvey (SpR)

Presenting Complaint
Post-op recovery from posterior spinal fusion

Issues
1. Post-operative inflammation with mild swelling
-CRP 45 mg/L
-No erythema, discharge, or systemic signs of infection

Today

On Review
Pt reports pain controlled. No â†‘ discomfort overnight.

Investigations
None

Observations
HR: 88
BP: 112/68
RR: 16
Temp: 37.1
SpO2: 98%

On Examination
Alert, NAD. Surgical wound: mild swelling, no erythema or discharge. No systemic signs of infx.

Plan
1. Initiate oral flucloxacillin 250 mg TDS x5 days to prevent potential wound infection due to mild swelling. 2. Proceed with scheduled physio session to encourage mobility and recogvery. 3. Review wound and CRP in 48 hrs to reassess inflammation and infection risk.


Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 06/01/2026 10:00

06/01/26, 10:0. Physio session w/ Daniel Jesse Ashton (PT). Focus: 1st assisted ambulation post-op using walker. Emphasis on posture + wt distribution to protect spine. Patient, Katie Catherine Kaur (13F), ambulated short distances with assistance. Good effort and motivation noted. No adverse events. Plan: Continue daily physio. Gradually increase walking distance and progress to unassisted ambulation. No new meds.
Therapist Daniel Jesse Ashton (Physical)

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 06/01/2026 11:30

- Wound dressing changed using sterile technique.
- Mild swelling observed around the surgical site.
- No signs of infection or discharge.
- Plan to conti nue monitoring wound healing during subsequent dressing changes.
Nurse Martin Cecil Bell
NMC number: 71D8152I

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 06/01/2026 15:00

OT session conducted by Therapist Anne Audrey Field on 06/01/26 at 15:00. Focus of the session was on safe transfers and energy conservationstrategies for daily living tasks. The following activities were completed:

1. Practised bed-to-chair and chair-to-commode transfers using a transfer board. Verbal cues provided toensure adherence to spinal precautions.
2. Evaluated the patient's ability to safely transition from bed to chair with minimal assistance, taking into account post-surgical restrictions on movement.
3. Demonstrated and guided patient, KatieCatherine Kaur, on proper techniques to avoid bending, twisting, or lifting.
4. Patient educated on energy conservation methods for washing and dressing, including pacing and prioritisation.
5. Patientengaged well and demonstrated understanding of instructions provided.

ABCDE assessment:
A: Airway patent.
B: Breathing normal, no respiratory distress.
C: CVS stable; no dizzines reported during transfers.
D: Neurological status intact, alert, and oriented.
E: No signs ofskin breakdown or discomfort observed during transfers.

Plan: Continue daily OT sessions to enhance independence with ADLs. No new medications prescribed.
Therapist Anne Audrey Field (Occupational Therapist)
GMC number: 1297613

--------------------------------------------------------------------------------

Clinical Note 17
Date/Time: 07/01/2026 08:30

Clinician Leading Ward Round
Dr. Donna Hayley Harvey (SpR)

Presenting Complaint
Juvenile idiopathic scoliosis

Issues
1. Juvenile idiopathic scoliosis
-Post-operative recovery following posterior spinal fusion
-Mild anaemia (Hb 10.5 g/dL)

Today

On Review
Mild pain @ wound. Appetite and energy improving. No fever. Current pain control regimen effective.

Observations
HR: 82
BP: 112/72
RR: 16
Temp: 36.8
SpO2: 98% RA

On Examination
Alert, NAD. Wound clean, healing well, no erythema or discharge. No swelling or tenderness. Chest clear, no added sounds. Abd soft, non-tender.

Plan
1. Start ferrous sulfate 200 mg OD for anaemia.
2. Continue physiotherapy with a focus on unassisted walking.
3. Review Hb in 48 hrs.


Dr. Donna Hayley Harvey (Specialty Registrar)
GMC number: 1994748

--------------------------------------------------------------------------------

Clinical Note 18
Date/Time: 07/01/2026 10:00

07/01/26, 10:00. Physio sesion with Daniel Jesse Ashton. Focus: unassisted walking. Katie Kaur was encouraged to walk short distances without the use of mobility aids under supervision. She demonstrated improved balance and stability but required occasional verbal cues to maintain proper posture. No significantpain or fatigue was noted, and her confidence with unassisted walking has improved compared to the previous session. Plan: Progress to stair navigation in the next scheduled OT session. No medication changes were made.
Therapist Daniel Jesse Ashton (Physical)

--------------------------------------------------------------------------------

Clinical Note 19
Date/Time: 07/01/2026 15:00

0/01/26, 15:00. OT: Lee Thomas Austin. Focus: safe stair navigation. Tech niques practiced included ascending and descending stairs with a handrail and crutches, with an emphasis on maintaining proper posture and weight distribution to avoid spinal strain. The patient required minimal assistance and completed the task well, demonstrating increased confidence. Plan: Continue OT to focus on self-care activities, transfers, and home navigation. No new meds were prescribed.
Therapist Lee Thomas Austin

--------------------------------------------------------------------------------

Clinical Note 20
Date/Time: 07/01/2026 17:00

- Pain management plan discussed with patient and mother.
- Emphasised avoidance of aspirin due to known allergy.
- Prescribed oral paracetamol 500 mg every 6 hours PRN and ibuprofen 200 mg every 8 hours with fod.
- Advised monitoring for adverse effects related to analgesics.
Nurse Martin Cecil Bell
NMC number: 71D8152I

--------------------------------------------------------------------------------

Clinical Note 21
Date/Time: 08/01/2026 08:30

Clinician Leading Ward Round
Dr. Donna Hayley Harvey (SpR)

Presenting Complaint
Juvenile idiopathic scoliosis

Issues
1. Juvenile idiopathic scoliosis (post-op posterior spinal fusion)
-Pain control effective (3/10)
-Wound healing well with minimal erythema
-Improving mobility with physiotherapy

Today

On Review
Feels better, mild fatigue. Pain 3/10.

Investigations



Observations
HR: 82
BP: 1114/72
RR: 56
Temp: 36.8
SpO2: 98%

On Examination
Alert, NAD. Wound clean, dry, min erythema. Notenderness or discharge. No signs of infection. Improving strength with physio.

Plan
1. Reduce oral morphine from 5 mg to 2.5 mg 4hrly PRN 2. Continue paracetamol 500 mg QDS 3. Continue PT, monitor mobility progress 4. Review analgesia adjustment and mobility tomorrow



In [17]:
# ---------------------------------------------------------
# Clinician validation — Patient 05
# ---------------------------------------------------------

PILOT_PATIENT_ID = "137b8481-4f1d-4b7f-babd-20f7117023ad"

# Complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 05")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 05
Source notes: 36
Source words: 3991
direct: 385 summary words
hierarchical: 415 summary words
rag: 351 summary words
rag_verification: 351 summary words

In [19]:
# ---------------------------------------------------------
# Clinician validation — Patient 05 document content
# ---------------------------------------------------------

PILOT_PATIENT_ID = "137b8481-4f1d-4b7f-babd-20f7117023ad"

PATIENT_LABEL = "Patient 05"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append(f"Total clinical notes: {len(pilot_notes)}")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_05_content = "\n".join(lines)

print(patient_05_content)

Patient 05

SOURCE CLINICAL RECORD
Total clinical notes: 36

Clinical Note 1
Date/Time: 06/01/2026 11:25

Patient assessed on 06/01/26 at 11:25 by Nurse Darren Christopher Burns. Initial vital signs recorded: BP 165/92 mmHg, HR 88 bpm. Mild disorientation noted during questioning. Categorised as Cat 2 for urgent ttiage by ED team.

Chief complaint: Acute confusion after minor fall.

Past medical history: HTN, Osteoarthritis, TIA (2018).

Allergies: Pollen.

ABCDE assessment:
A: Airway patent, no stridor or obstruction.
B: Breathing unlaboured, RR within normal range, SpO2 not recorded.
C: BP165/92 mmHg, HR 88 bpm, no active haemorrhage noted.
D: Mild disorientation, GCS not formally documented.
E: No obvious external injuries noted, mild bruising on left hip reported by patient post-fall.

Directed to ED team for further urgent asssssment and management.
Nurse Darren Christopher Burns
NMC number: 19P6622C

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 06/01/2026 11:45

Patient reviewed at 11:45 on 06/01/26 by Nurse Darren Christopher Burns. Initial observations performed. BP recorded at 160/95 mmHg, HR 92 bpm. Mild right-sided headache reported by the patient during assessment. Chief complaint noted as acute confusion after minor fall. ED diagnosis of subdural hygroma documented. Decision made to monitor BP and proceed with CT head scan to assess for otential intracranial injury.

ABCDE assessment:
A: Airway patent, no concerns.
B: Breathing nomral, RR 16/min, SpO2 97% on room air.
C: BP 160/95 mmHg, HR 92 bpm, peripheral perfusion adequate. Previous iintial assessment recorded BP 165/92 mmHg and HR 88 bpm.
D: GCS 14/15 (confused), reported mild right-sided headache. Pupils equal and reactive to light.
E: No obvious injuries or external bleeding noted. Sin warm and dry.
Nurse Darren Christopher Burns
NMC number: 19P6622C

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 06/01/2026 12:10

64-year-old male, Frank Scott Bond (DOB: 18/03/59), escorted to radiology for CT head scan. Reassurance provided throughout due to ongoing confusion after a minor fall. A: Patent airway, no stridor or obsstruction noted. B: Respiratory rate 16/min, SpO2 98% on room air. C:BP 160/95 mmHg, HR 92 bpm, cap refill <2s. D: GCS 14/15 (cconfusion noted), PERL bilaterally. E: No acute distress; noted mild right-sided headache. Patient's past medical history includes HTN, osteoarthritis, and a TIA (2018). ED diagnosis: subdural hyhroma. Staff involved: Nurse Darren Christopher Burns. Patient to return to ED for imaging review by the medical team.
Nurse Darren Christopher Burns
NMC number: 19P6622C

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 06/01/2026 12:50

Date: 06/01/26
Time: 12:50
Staff: Nurse Jennifer Jemmsa Hussein
Patient Name: Frank Scott Bond
Gender: Male
CT head report reviewed with the patient. Findings: Subdural hygroma identified, no evidence of acute ICH.
Reassurance provided to the patient regarding the absence of critical injury. Explanation of imaging findings offered and acknowledged.
Context: Patient presented wiht acute confusion after a minor fall. This context was explained to the patient in relation to the CT findings.
Next steps: Patient advised to remain on stretcher for close observation while awaiting review by the ED consultant.
Nurse Jennifer Jemma Hussein
NMC number: 70K6070K

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 06/01/2026 13:15

Patient
Frank Scott Bond

Age
64

Sex
Male

NHS No.:
612043217

Date/Time
06/01/26 13:15

Seen By
Dr. Olabisi Idowu, Dr. Naomi Courtney Brooks

Presenting Complaint
Acute confusion post minor fall. Mild R-sided headache noted since the fall.

History of Presenting Complaint
Pt reports losing balance this AM, hit head on crapeted floor. No LOC. Confusion oted by partner post-fall. Mild R-sided headache noted since fall. No vomiting. No visual changes. No weakness or speech issues. Reassurance provided by staff regarding sx.

Past Medical History
- HTN
- OA
- TIA (2018)

Medications
None.

Allergies
Pollen.

Social History
Lives w/ wife. Independent ADs. Retired accountant.

Family History
No relevant FHx.

Systems Review
Neuro: Confusionbut no seizures, no focal deficit, no worsening confusion. CVS: No palpitations, no chest pain. Resp: No SOB. GI: No N/V. GU: No dysuria. ID: No fever. No neck stiffness. No photophobia.

On Examination
Confused but GCS 14 (E4, V4, M6). Mildly disoriennted to time/place. No focal neuro deficits. Pupils equal/reactive. Mild R parietal tenderness, no scalp haematoma. No neck stiffness. Gait not tested due to confusion.

Observations
BP 160/95
HR 92
RR 16
Temp 336.8
SPO2 98% RA

Investigations
CT head: Subdural hygroma, no acute bleed.

Test Results


Impression
Subdural hygroma post minor fall. Confusion likely secondary to trauma.

Referral
Accepted by AMU, bed C06.

Plan
- Admit to AMU for neuro obs.
- Conserbative Mx.
- Paracetamol 1g QDS PRN for HA.
- Monitor BP.
- Escalate if GCS drops or neuro Sx worsen.


Dr. Olabisi Idowu (ED Consultant)
GMC number: 1906484

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 06/01/2026 14:00

Clerking Doctor
Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion following minor fall.

History of Presenting Complaint
- Pt reports tripping over a loose rug at home yesterday evening (05/01/26) with a minor fall onto carpeted flooring, no LOC reported. - Initially felt wel but developed confusion later in the evening, described as difficulty recognising familiar objects and people. - No recol lection of the events leading to confusion. - Denies any vertigo, N&V, or CP. - Reports a mild R-sided headache that started after the fall, described as dull and persistent, rated 3/10 in severity, not worsening over time. - No limb weakness, visual disturbances, or incontinence reported.

Review of Systems
- CNS: Mild confusion, no focal neurological deficits, no seizures, no dysarthria.
- CVS: No chest pain, palpitations, or syncope.
- Resp: No shortness of breath, cough, or wheeze.
- GI: No nausea, vomiting, abdominal pain, or change in bowel habits.
- GU: No dysuria, haematuria, or incntinence.
- MSK: eports mild discomfort in the right hip area, no obvious swelling or deformity.
- Endocrine: No symptoms of hyperglycaemia or hypoglycaemia.

Past Medical History
- HTN
- OA
- TIA (2018)

Medications
Paracetamol 1g PRN every 6 hours for headache as prescribed in A&E.

Allergies
- Pollen

Social History
- Retired builder, lives alone in a bungalow.
- Independent with ADLs.
- Mobilises with a single walking stick due to OA affecting knees.
- Denies smoking or recreational drug use.
- Drinks aproximately 10 units of alcohol weekly (occasional beer).

Family History
- Father had a history of stroke in his 70s.
- Mother had HTN and osteoarthriti s.

On Examination
- Alert but mildly confused, disoriented to time (stated the incorrect year), oriented to place and person.
- Speech fluent, normal tone and volume.
- CNs intact.
- Power 5/5 in all muscle groups bilatreally.
- Sensation intact to light touch and pinprick in all limbs.
- Reflexes symmetrical in upper and lower limbs.
- Gait not assessed due to acute confusion.
- No scalp lacerations or haematomas observed.
- Mild tenderness over the right hip, no obvious swelling, deformity, or crepitus.
- Skin turgor slightly reduced; dry mucous membranes, indicating mild dehydration.
- No peripheral oedema or cyanosis.

Observations
HR 88
BP 160/95
RR 18
Temp 36.7
SpO2 96% on room air

Investigations
- T head: Subdural hygroma confirmed with no acute haemorrhage or mass effect.

Test Results
- Urea: 9.8 mmol/L
- All other blood test results within normal limits.

Impression
Subdural hygroma, mild dehydration, and acute confusion post minor fall. Suspected contributing factors include recent minor head trauma and possible suboptimal oral intake.

Plan
- Commence IV fluids: 0.9% sodium chloride 1L over 8 hours to address dehydration.
- Neudrological observations, including GCS monitooring and pupil responses.
- Monitor fluid input/output to assess hydration status.
- Repeat U&E tests in 24 hours.
- Prescribe paracetamol 1g PRN every 6 hours for headache as needed.
- Liaise with physio for mobility assessment when clinically appropriate.
- If confusion persists after rehydration, consider further cognitive assessment and liaise with psych if required.
- Reassess for any changes in neurological status; escalate to neurosurgery if indicated.


Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 06/01/2026 16:00

Clinician Leading Ward Round
Dr. Karl Timothy Birch (Consultant), Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion after minor fsll

History of Presenting Complaint
Hx noted thank you

Issues
1. Subdural hygroma
-No acute bleeding on CT
-Ongoing confusion without focal neurological deficits
2. Mild hyponatraemia
-Serum sodium 131 mmol/L
-Likely contributing to confusion
-Borderline inadequate hydration status

On Review
Alert but disoriented to time and place. No new symptoms were reported beyond the ongoing confusion.

Investigations
None since admission.

Test Results
Serum sodiu m 131 mmol/L. Urea 9.8 mmol/L.

Observations
HR 92
BP 160/95
RR 16
Temp 37.1
SpO2 96% on sir

On Examination
Alert but disoriented to time and place. No focal neuro deficits. Hydration status bor derline inadequate with dry mucous membranes. Motor and coordination normal. Cognitive assessment revealed impaired orientation to time and place but memory and attention grossly intact.

Plan
1. Start IV normal saline (0.9% NaCl) at 1 L over 8 hours to address mild hyponatraemia. 2. Encourage oral hydratiob. 3. Refer to therapy team for cognitive and functional assessment.


Dr. Karl Timothy Birch (Consultant)
GMC number: 1664588

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 06/01/2026 17:30

17:30 06/01/26. Cognitive and functional assessment conducted by occupational therapist Ada Jill Coleman. The assessment wasconducted in the hospital environment to evaluate ADLs including dressing, feeding, and mobility. Observations: mild short-term memory recall issues noted, requir ing prompting for task sequencing. The patient followed instructions with moderate supervision. No motor deficits were observed. Recommendation: initiate cognitive rehabilitation exercises targeting memory and attention deficits. No medications required. Plan: continue assessment and monitor progress.
Therapist Ada Jill Coleman (Physical)

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 06/01/2026 19:00

Contacted patient's next of kin, Margaret Ann Bond, at 19:00. Provided update on CT findings (subdural hygroma, no acute bleed) and admission to AMU. Explained ongoing management plan including neuro obs and supportive care. No cha nges to cur rent treatment plan. Next of kin informed and acknowledged understanding.
Nurse Darren Christopher Burns
NMC number: 19P6622C

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 07/01/2026 09:00

Clinician Leading Ward Round
Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion after minor fall

Issues
1. Subdural Hygroma
-

Today

On Review
Patient reports mild headache. Still confused but no worsening of neurological symptoms. Hydration status noted to be adequate.

Investigations
None

Test Results
Serum sodium 132 mmol/L

Observations
HR: 88
BP: 155/90
RR: 16
Temp: 36.8
SpO2: 98%

On Examination
- Alert but disoriented to time and place
- Mildly confused, no signs of agitation
- Cranial nerves intact
- No focal neurological deficits
- CVS: S1 and S2 heard, no murmurs
- Chest: Clear to auscultation bilaterally
- Abdomen: Soft, non-tender, no organomegaly
- No peripheral oedema

Plan
- Continue oral hydration with electrolyte supplementation (Dioralyte sachets, 1 sachet in water twice daily)
- Repeat serum Na levels in 24 hours
- Monitor for any signs of neurological deterioration
- Liaise with therapy team for ongoing cognitive rehab exercises
- Reassess hydration status tomorrow
- Discuss the importance of fluid balance and electrolyte corection with the patient


Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 07/01/2026 10:30

10:30, 07/01/26. Physio Ax by Ada Jill Coleman. Mobility Ax conducted to evaluate walking stability and balance. Pt mobilised w/ 4WW. Supervised walk in ward corridor. Mipd unsteadiness obs but no sig assist req. Pt able to complete exercises without sig assist. Plan: Cont use of 4WW for mob. Further bal/coord exercises sched. Monitor progress.
Therapist Ada Jill Coleman (Physical)

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 07/01/2026 13:00

Staff
Dr. Georgina Claire Gurung, Neurology Consultant

Additional Clinical History
-HTN
- OA
- TIA (2018)

Issues
1. Subdural Hygroma
-CT head confirmed subdural hygroma, no acute bleed (06/01/26)
-Mild confusion with subtle improvement compared to admission
-Intermittent mild headaches well-managed with paracetamol
-No focal neurological deficits or signs fo raised intracranial pressure
-Neurological observations remain stable

Safety Alerts
- Allergy to pollen

Medications
- Paracetamol 1g every 6 hours as needed for headache
- Dioralyte sachets, 1 sachet dissolved in water, twice daily for electrolyte suplementation

Physical Examination
- Alert but mildly confused
- No focal neurollogical deficits (FND)
- Pupils equal and reactive to light
- No neck stiffness
- Cranial nerves II-XII intact
- Normal motor strength and tone in all limbs
- No sensory deficits noted
- Normal coordination and gait with a 4WW

Investigations
- CT head (06/01/26): Subdural hygroma confirmed, no acute bleed
- Na: 132 mmol/L (mild hyponatraaemia)
- Urea: 9.8 mmol/L

Future Orders
- Continue regular neuro obs
- Encourage adequate oral fluid intake
- Monitor srum Na levels with repeat blood tests

Care Plan Outcomes
- Conservative management tk be continued
- Regular neuro obs to monitor for any deterioration
- Maintain hydration and electrolyte balance
- No new meds initiated or discontinued at this stage


Dr. Georgina Claire Gurung (Neurology Consultant)
GMC number: 1613126

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 07/01/2026 15:00

Session conducted on 07/01/26 at 15:00 by Therapist Samuel Mohammed Peters (SLT). Focus was on cognitive training exercises with patient Frank Scott Bond. Activities included memory recall tasks using visual prompts and verbal problem-solving exercises aimed at improving attention and short-term memory (STM). The patient engaged well and followed instructions, though occasional repetitions were needed for clarity. Plan to schedule the next session in two days to bui ld on progress and assess sustained improvement in cognitive function.
Therapist Samuel Mohammed Peters (Speech and Language)

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 07/01/2026 18:00

Patient reported mild headache at 18:00. Administered 1 g paracetamol PO as per PRN cchart. No changes to Tx plan. Supportive care and analgesia PRN to continue.
Nurse Darren Christopher Burns
NMC number: 19P6622C

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 08/01/2026 08:45

Clinician Leading Ward Round
Dr. Abdul Yaqoob (SpR), Dr. Alison Geraldine Reynolds (Cons)

Presenting Complaint
Acute confusion after minor fal

Issues
1. Subdural Hygroma
-Confirmed on CT head scan
-No focal neurological deficits
-Mild confusion improving

Today

On Review
- Patient reports reduced headache severity
- Occasional mild dizziness on mobilising
- Feels slightly better overal l

Investigations
No new imaging or other studies performed.

Test Results
- Serum sodium 133 mmol/L (mild hyponatremia)

Observations
HR: 84
BP: 152/88
RR: 16
Temp: 36.8
SpO2: 97% on room air

On Examination
- Alert and conversing
- Oriented to day and location, but still some confusion about time
- No signs of focal neuro deficits
- Gait unsteady but no worsening

Plan
- Adjust oral fluid intake to improve sodium levels
- Start sodium chloride tablets 600mg BD
- Continue physio to improve balance and coordination
- Monitor for further improvement in orientation and symptoms


Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 08/01/2026 10:00

8/1/26 10:00. Physio: Adda Jill Coleman. Balance and coordination exercises performed. Exercises included standing on one leg with support and stepping onto a low platform. The patient required verbal cues for safety and mod assistance but was able to complete the exercises. Plan: Continue daily physio sessions focusing on progressive balance and mobility tasks. Ressess stair navigation readiness in two days.
Therapist Ada Jill Coleman (Physical)

--------------------------------------------------------------------------------

Clinical Note 17
Date/Time: 08/01/2026 12:00

- Family meeting held with patient, spouse, and mywself to discuss patient's progress, recovery timeline, and discharge planning.
- Plan agreed to arrange home environment assessment by OT prior to discharge.
Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

--------------------------------------------------------------------------------

Clinical Note 18
Date/Time: 08/01/2026 14:30

Patient reviewed on 08/01/26 at 14:30 by Therapist Samuel Mohamed Peters (SALT). Assessment focused on speech clarity, comprehension, and ability to follow multi-step instuctions. Mild word-finding difficulties observed during conversation, particularly with complex topics. These findings are consistent with residual effects of the subdural hygroma. Patient was cooperative and engaged throughout the session. Recommended daily cognitive-linguistic exercises specifically targeting word retrieval. Plan for reassessment in two days to monitor progress in word retrieval and overall cognitive-linguistic improvement.
Therapist Samuel Mohammed Peters (Speech and Language)

--------------------------------------------------------------------------------

Clinical Note 19
Date/Time: 08/01/2026 18:30

Patient encouraged by Nurse Darrren Christopher Burns to attend evening relaxation group on the ward. Activities included ugided breathing exercises and light meditation to support cognitive recovery and reduce anxiety. Participation to be monitored, with further sessions encouraged to aid recovery and well-being.
Nurse Darren Christopher Burns
NMC number: 19P6622C

--------------------------------------------------------------------------------

Clinical Note 20
Date/Time: 09/01/2026 09:15

Clinician Leading Ward Round
Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion after minor fall

Issues
1. Subdural Hygroma
-Improvement in cognitive clarity
-Resolution of mild headache
-No focal neurological deficits
-Mild fatigue noted

Today

On Review
Patient reports improved cognitive clarity and resolution of mild headache. Expressed concerns about ability to manage stairs at home.

Investigations
No imaging or ECG investigations noted during this ward round.

Test Results
Serum sodium133 mmol/L.


In [20]:
# ---------------------------------------------------------
# Clinician validation — Patient 06
# ---------------------------------------------------------

PILOT_PATIENT_ID = "9d8fd25d-c4fe-4343-8ff5-5da5dad4e740"

# Complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 06")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 06
Source notes: 26
Source words: 4287
direct: 584 summary words
hierarchical: 597 summary words
rag: 414 summary words
rag_verification: 408 summary words

In [21]:
# ---------------------------------------------------------
# Clinician validation — Patient 06 document content
# ---------------------------------------------------------

PILOT_PATIENT_ID = "9d8fd25d-c4fe-4343-8ff5-5da5dad4e740"

PATIENT_LABEL = "Patient 06"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append(f"Total clinical notes: {len(pilot_notes)}")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_06_content = "\n".join(lines)

print(patient_06_content)

Patient 06

SOURCE CLINICAL RECORD
Total clinical notes: 26

Clinical Note 1
Date/Time: 05/01/2026 12:35

Clerking Doctor
Dr. Promise Nkosi (Consultant)

Presenting Complaint
Elective admission for total right shoulddr replacement.

Procedure
Total right shoulder replacement for end stage OA.

On Examination
The patient appears well and in no distress. General physical examination showed no pallor, cyanosis, jaundice, or oedema. CVS examination revealed normal heart sounds with no murmurs or added sounds. Resp examination showed clear breath sounds bilaterally with no wheeze or crackles. Focused MSK examination of the right shoulder revealed marked restriction in range of motion withcrepitus on movement. No joint instability was noted, and no erythema or swelling was present. The patienrt has a documented allergy to nuts.

Observations
HR 72
BP 138/85
RR 14
Temp 36.8
SpO2 98%

Investigations
No new imaging or ECG performed. Pre-op ECG from 23/12/25 showed minor age-related changes with no acute abnormalities.

Test Results
Mild anaemia noted on pre-operative blood tests (Hb 11.2 g/dL). No other abnormalities. All other results (FBC, U&E, coagulation profile) were within acceptable limits.

Plan
1. Proceed with scheduled total right shoulder replacement on 06/01/26. 2. Temporarily discontinue ibuprofen due to pre-op protocol. 3. Continue ferrous sulfate 200 mg twice daily to optimise Hb levels pre-op. 4. Administer enoxaparin 40 mg SC for thromboprophylaxis starting today. 5. Ensurefasting instructions are followed as previously advised. 6. Proceed with GA as planned for surgery.


Dr. Promise Nkosi (Consultant)
GMC number: 1767543

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 05/01/2026 15:00

Clinician Leading Ward Round
Dr. Promise Nkosi (Consultant)

Presenting Complaint
End-stage OA of the roght shoulder

History of Presenting Complaint
hx noted thank you

Issues
1. End-stage osteoarthritis of the right shoulder
-Mildly elevated BP 152/88 mmHg deemed acceptable for surgery
-Planned total right shoulder replacement

On Review
Patient feels well and ready for surgery. No acute concwerns raised. Patient asked about post-op pain management, and this was addressed by the clinical team.

Investigations
No new imaging or ECG performed since admission.

Test Results
FBC, U&E, and coagulation profile all normal. Hb 11.2 g/dL noted at pre-op assessment.

Observations
HR 78
BP 152/88
RR 16
Temp 36.8
SpO2 98%

On Examination
Patient appears comfortable and wwll. No signs of active infection. Right shoulder inspected with no erythema, swelling, or discharge. Range of motion limited due to OA but no acute deterioration noted. Neurological examination of the right upper limb revealed intact sensation and motor strength. No ab normal swelling observed in the shoulder or surrounding areas.

Plan
1. Proceed with total right shoulder replavcement as planned. 2. Administer cefuroxime 1.5 g IV at induction for abx prophylaxis. 3. Monitor intraop and postop course closely.


Dr. Promise Nkosi (Consultant)
GMC number: 1767543

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 05/01/2026 16:00

- Patient attended a pre-op physio session on 05/01/26 at 16:00 in preparation for total R shoulder replacement surgery scheduled for 06/01/26.
- Session conducted by Therapist Georgina Sophie Holmes (Physical).
- Focus of the session: education on post-op sholder rehab strategies.
- Patient was informed about the importance of early mobilisation to aid recovery and prevent complications.
- Demonstration of gentle pendulum exercises was provided and explained in detail.
- Strategies to manage post-op pain and swelling were discussed, including the use of ice packs and proper elevation techniques.
- Patieht was encouraged to ask questions and actively engagde in the discussion.
- Patient verbalised understanding of the information and demonstrated comprehension of the exercises.
- No new meds prescribed during this session.
- Patient advised to adhere to the post-op exercise plan provided post-surgery.
- No concerns noted; patient appears well-prepared for post-op rehab.
Therapist Georgina Sophie Holmes (Physical)

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 06/01/2026 08:30

Surgeon
Dr. Kiyomi Yamaguchi

Assistant
Nurse Eric George Gordon, Nurse Ifeoluwa Akinlosotu

Anaesthetist
Dr. Idris Dad

Anaesthesia Type
GA

Procedure
Total right shoulder replacement Deltopectoral approach, rightshoulder Absorbable sutures, sterile dressing applied

Diagnosis
End-stage OA, right shoulder

Findings
Severe cartilage damage and osteophyte formation in GH joint. No significant inflam mation in surrounding tissues.

Tissue Removed
Degenerated cartilage and remnantsof joint surfaces

Prostheses or Implants
Cemented shoulder prosthesis

Estimated Blood Loss
Minimal

Complications
None

Post-Operative Care
Cefuroxime 1.5g IV TDS for 48 hrs (prophylaxis). Oxycodone 5mg PO PRN for pain. Continue current analgesic regimen (paracetamol, omeprazole).

Plan
Commence physio per post-op protocol. Discharge planning to include home exercise programme. Send removed tissue to histology for analysis.


Dr. Kiyomi Yamaguchi (Surgeon)
GMC number: 1941302

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 06/01/2026 11:30

Patient transferred to PACU at 11:30 following total right shoulder replacement. Monitored by anaesthetic team and Nurse Ifeoluwa Akinlosotu. Vital signs stable throughout recovery. Post-op pain reported as 4/10 on VAS. Antiemetic and analgesia administered. Next steps documented below.

ABCDE Assessment:
A: Airway patent. No signs of obstruction post-extubation.
B: Breathing unlaboured. SpO2 98% on room air. RR 16/min.
C: BP 138/82 mmHg. HR 76 bpm. Peripheral perfusion adequate.
D: Fully awake. GCS 15. Able to communicate. Mild nausea resolved post-ondansetron.
E: Dressing clean, dry, and intact. No active bleeding from surgical site.

Interventions:
- Ondansetron 4 mg IV given for mild nausea.
- Paracetamol 1 g IV adjinistered for pain relief.

Next Steps:
- Prescribe co-codamol 30/50 mg two tablets every six hours PRN for pain.
- Continue ondansetron 4 mg every eight hours PRN for nausea.
- Transfer to Ward 3B for further post-op care.

Note: Patient has a known allergy to nuts, which should be considered in ongoing care.

Documented by: Dr. Idris Dad (Specialty Registrar).
Dr. Idris Dad (Specialty Registrar)
GMC number: 1734342

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 06/01/2026 14:00

Clinician Leading Ward Round
Dr. Idris Dad (SpR)

Presenting Complaint
End-stage OA of the right shoulder

Issues
1. End-stage osteoarthritis of the right shoulder
-Post-operative day 0 following total right shoulder replacement
-Moderate discomfort controlled by analgesia

Today

On Review
Patient reports moderate discomfort but states pain is controlled with current medication.

Investigations
No imaging performed. Survgical wound inspected and found to be clean and healing well with no signs of infection. No new lab results available at this time.

Observations
HR: 78
BP: 138/84
RR: 16
Temp: 37.0
SpO2: 98% on room air

On Examination
The patient appeared comfortable and in no acute distress. A: Patent, no stridor or airway obstruction. B: Respiratory effort normal, clear breath sounds bilaterally. C: Peripheral perfusion intact, capillary refill <2 seconds. D: Alert and orientated, no new neuro deficits. E: Dressing clean, dry, and intact. Surgical wound healing well with no erythema, swelling, or d/c noted.

Plan
1. Commence oral co-codamol 30/500 mg every 6 hours PRN for pain. 2. No antibiotics requiredd as no signs of infxn. 3. Continue wound care as per standard protocol.


Dr. Idris Dad (Specialty Registrar)
GMC number: 1734342

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 06/01/2026 15:30

- Patient attended first post-op physiotherapy session on 06/01/26 at 15:30, guided by Therapist Georgina Sophie Holmes (Physical).
- This session followed the patientâ€™s total R shoulder replacement surgery.
- Focus fo session: gentle passive-assisted shoulder movements to prevent stiffness and promote circulation in the operated R shouder joint.
- Patient educated on the importance of maintaining correct posture while using the arm sling.
- Patient demonstrated good understanding of the posture advice and exercise techniques.
- No adverse events or significant pain exacerbation reported during the session.
- Patient advised to continue passive shoulder exercises three times daily under nursing supervision until the next scheduled physio session.
Therapist Georgina Sophie Holmes (Physical)

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 06/01/2026 17:00

Patient provided with verbal and written education on wound care, including cleaning techniques, dressing changes, and recognising early signs of infection. Advised to report any infection signs to ward staff immediately. No changes to treatment plan.
Nurse Eric George Gordon
NMC number: 25L3886P

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 07/01/2026 09:00

Clinician Leading Ward Round
Dr. Idris Dad (SpR)

Presenting Complaint
End-stage OA of right shoulder

Issues
1. End-stage Osteoarthritis
-Post-operative day 1 following total right shoulder replacement
-Moderate pain managed with analgesics
-Wound showing mild swelling but no signns of infection

Today

On Review
Patient reports moderate pain but tolerable with current analgesic regimen. Mobilising with assistance.

Investigations
No new imaging or other investigations perfored. No new lab test results available or pending.

Observations
HR: 78
BP: 136/82
RR: 16
Temp: 37.2
SpO2: 98% on air

On Examination
Patiebnt appears comfortable and is alert. A: Patent airway, no stridor or hoarseness. B: Breathing unlaboured, good air entry bilaterally. C: CVS stable, capillary refill <2s, no peripheral oedema. D: GCS 15, alert and orientated. No new neurological deficits noted. E: Surgical site clean, mild swelling, no erythema, no discharge.

Plan
1. Continue physiotherapy as planned to promote mobilisation of the right shoylder. 2. Prescribe codeine 30 mg PO PRN for breakthrough pain in addition to the current analgesic regimen. 3. Monitor wound for any signs of infection or increased swelling.


Dr. Idris Dad (Specialty Registrar)
GMC number: 1734342

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 07/01/2026 10:30

- Patient attended a physiotherapy session at 10:30 on 07/01/26 with Therapist Georgina Sophie Holmes (Physical).
- Focus of the session was on active-asisted range of motion (ROM) exercises for the right shoulder following total shoulder replacement (TSR) surgery on 06/01/26.
- Guided movements were performed to enhance flexibility and prevent joint stiffness.
- Patient instructed to use the left hand to assist with getle, controlled movements of the right arm, ensuring all exercises remained within a pain-free range.
- Verbal cues and corrections were provided throughout the session to ensure proper technique and avoid compensatory movements.
- Patient engaged well with the exercises and demonstrated good understanding of the techniques explained.
- The patient was also educated on maintaining proper posture while using the arm sling to support the operated shoulder.
- No adverse reactions or complications reported during the session.
- Advised to continue active-assisted ROM exercises three times daily at home, gradually increasing the range as tolerated.
- No new medications were prescribed.
- Plan to review progress in  the next scheduled physiotherapy session.
Therapist Georgina Sophie Holmes (Physical)

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 07/01/2026 12:00

Blood samples taken to assess for post-op complications (FBC, CRP, electrolytes). No changes to meds. Awaiting results to evaluate for infectiob or electrolyte imbalance.
Dr. Rebecca Penelope Lucas (Foundation Trainee)
GMC number: 1126037

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 07/01/2026 14:00

Patien: Brian William Morris, 76-year-old male, NHS number: 695592370, admitted for total right shoulder replacement surgery on 05/01/26.

- Therapy session conducted on 07/01/26 at 14:00 by Therapist Georgina Sophie Holmes (PT).
- Focus of session: Education on correct use of shoulder sling for support and training in safe mobility techniuqes.
- Mobility techniques addressed: Safely getting in and out of bed, using a bedside chair with minimal strain on the operated shoulder. Patient was also encouraged to use the left hand to assist with gentle movements of the right arm within a pain-free range.
- Patient demonstrated ability to independently perform tasks with guidance; confidence in mobility noted to require improvement.
- Verbal and physical gujdance provided to refine technique and build confidence.

- Post-session advice:
  - Continue use of sling for shoulder support during ambulation and rest.
  - Attend scheduled physio session on 08/01/26 to focus on further improving shoulder mobility, including active-assisted ROM exercises.

- No new meds or additional interventions recommended at this stage.
Therapist Georgina Sophie Holmes (Physical)

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 07/01/2026 17:00

Clinician Leading Ward Round
Dr. Idris Dad (SpR)

Presenting Complaint
End-stage OA of the right shoulder

Issues
1. Post-operative recovery from total right shoulder replacement
-Right shoulder dressing  clean and intact
-Mild localised swelling, no erythema or discharge
2. Possible post-operative infection (suspected)
-CRP 65 mg/L
-WBC 11.5 x10^9/L
-Awaiting next set of inflammatory marker trends

Today

On Review
Patient reports adequate pain control with current regimen but is concerned about restricted shoulder mobility. Reassurance was provided, explaining that gradual recovery is expected. No other complaints.

Investigations
None

Observations
HR: 82
BP: 138/84
RR: 16
Temp: 36.8
SpO2: 98% on air

On Examination
- Alert, sitting comfortably in bed, no acute distress
A. Airway patent, speaking in full sentences
B. Chest clear to auscultation bilaterally, no added sounds
C. Heart sounds dual, no murmurs. CRT <2 seconds
D. No focal neurological deficits. GCS 215. Moving all limbs. No sensory deficits
E. Right shoulder dressing clean and intact. Mild localised swelling. No erythema or discharge.

Plan
1. Start co-amoxiclav 625 mg TDS for 5 days as prophylaxis for suspected early post-op infection due to elevated inflammatory markers. 2. Continue physio as per schedule to improve sho ulder mobility. 3. Review inflammatory markers in 48 hours. 4. Reassess mobility concerns during next ward round.


Dr. Idris Dad (Specialty Registrar)
GMC number: 1734342

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 08/01/2026 08:45

Clinician Leading Ward Round
Dr. Idris Dad (SpR)

Presenting Complaint
End-stage OA of the right shoulder

Issues
1. Post-operative inflammatory markers elevation
-CRP 65 mg/L
-WBC 11.5 x10^9/L
-Prophylactic antibiotics prescribed (co-amoxiclav)

Today

On Review
Patient reports mild shoulder discomfort, controlled with analgesia. No other symptoms reported.

Investigations
None

Observations
HR: 78
BP: 136/82
RR: 16
Temp: 36.8
SpO2: 97% on air

On Examination
- Alert, comfortable at rest.
- A: Patent, no stridor or wheeze.
- B: Chest clear bilaterally, no added sounds.
- C: Peripheral perfusion normal; capillary refill <2s; no oedema.
- D: GCS 15/15, no focal neuro deficit.
- E: Right shoulder woundclean, sutures intact, no erythema or discharge.

Plan
1. Prescribe oral co-amoxiclav 625 mg TID for 5 days due to elevated inflammatory markers (CRP 65 mg/L, WBC 11.5 x10^9/L). 2. Continue physio as planned, focusing on passive and active-assisted range of motion exercises. 3. Review inflammatory markers in 48 hours. 4. Assess for discharge readiness in the next 24-48 hours.


Dr. Idris Dad (Specialty Registrar)
GMC number: 1734342

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 08/01/2026 10:00

Patient: Brian William Morris, NHS Number: 695592370, 76-year-old male, post-total right shoulder replacement.

- Date: 08/01/26
- Time: 10:00
- Therapist: Georgina Sophie Holmes (Physical)

- Focus of session: Improving active-assisted ROM in the right shoulder following surgery.
- Exercises performed: Pendulum swings, assisted arm lifts, and external rotations with minimal resistance.
- Feedback: Provided guidance on form and technique to ensure proper movement patterns. Patient demonstrated understanding of the importance of adhering to the prescribed HEP for gradual progression of shoulder mobility.
- Monitoring: Checked for discomfort or undue strain during exercises; session conducted within pain-free limits, and patient tolerated the session well.
- Education: Reinforced importance of adherencee to the prescribed HEP for gradual progression of shoulder mobility.

- Plan: Patient to continue with HEP post-discharge. Emphasis placed on gradual shoulder mobility improvement within pain-free limits.
- Medications: No new prescriptions issued
- Follow-up: Patient to attend subsequent ph ysio sessions as per rehab plan.
Therapist Georgina Sophie Holmes (Physical)

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 08/01/2026 11:30

- OT session conducted by TTherapist Andrew Anthony Lamb.
- Assessment of patientâ€™s home environment completed.
- Recommendations provided for post-discharge modifications:
  - Raised toilet seat.
  - Grab bars in the bathroom.
- Aim to ensure safety and ease of mobility post-discharge.
- Patient informed and verbalised understanding of recommendations.
Therapist Andrew Anthony Lamb (Occupational Therapist)
GMC number: 1059066

--------------------------------------------------------------------------------

Clinical Note 17
Date/Time: 08/01/2026 14:00

- Final physio session conducted on 08/01/26 at 14:00 by Therapist Georgina Sophie Holmes.
- Session focused on educating the  patient on a tailored home exercise program post-total right shoulder replacement.
- Exercises included pendulum swings, wall climbs, and passive-assisted movements using the contralateral arm. The therapist emphasized proper movement patterns during exercises and monitored for any signs of discomfort or undue strain.
- Pt reported mild discomfort during exercises but no significant pain.
- Pain levels assessed and deemed manageable with current analgesjic egimen (paracetamol and ibuprofen).
- Advised to perform prescribed exercises three times daily at home, ensuring gradual progression of ROM.
- Pt instructed to avoid lifting heavy objects with the right arm for six weeks.
- No new meds prescribed.
- Pt demonstrated understanding of the exercise regimen and precautions to be followed post-discharge.
- Additionally, Therapist Andrew Anthony Lamb conducted an OT session on the same day to assess the pt's home environment and provided recommendations for post-discharge modifications, including the use of a raised toilet seat and grab bars in the bathroom to ensure safety and ease of mobility.
Therapist Georgina Sophie Holmes (Physical)


In [22]:
# ---------------------------------------------------------
# Clinician validation — Patient 07
# ---------------------------------------------------------

PILOT_PATIENT_ID = "c6c45c39-cd73-49dd-818d-0a7865fe8a7f"

# Complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 07")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 07
Source notes: 45
Source words: 5134
direct: 448 summary words
hierarchical: 468 summary words
rag: 336 summary words
rag_verification: 317 summary words

In [23]:
# ---------------------------------------------------------
# Clinician validation — Patient 07 document content
# ---------------------------------------------------------

PILOT_PATIENT_ID = "c6c45c39-cd73-49dd-818d-0a7865fe8a7f"

PATIENT_LABEL = "Patient 07"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append(f"Total clinical notes: {len(pilot_notes)}")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_07_content = "\n".join(lines)

print(patient_07_content)

Patient 07

SOURCE CLINICAL RECORD
Total clinical notes: 45

Clinical Note 1
Date/Time: 03/01/2026 01:35

Patient Abena Bonsu, a 43-year-old female, was assessed on arrival at 01:35 on 03/01/26 by Nurse Audrey Phyllis Gill. Chief complaint: Progressive breathlessness. Triage category: Category 2 - Higy risk, potentially life-threatening condition requiring urgent attention. ED diagnosis: Chronic thromboembolic pulmonary HTN. Vital signs recorded: Oxygen saturation 89% on room air, indicating mild hypoxia. Past medical history includes HTN and asthma. Allergy to nuts noted. No current medications reported by the patient. Patient placed on low-flow oxygen therapy to improve oxygenation as an immediate intervention. Admission to Respiratory High Dependency Unit (HDU) under care of Dr. Elizabeth Kathryn Singh (Consultant) planned for further management of chronic thromboembolic pulmonary HTN.
Nurse Audrey Phyllis Gill
NMC number: 75Q7413G

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 03/01/2026 02:15

Patient presented with progressive breathlessness and was diagnosed with chronic thromboembolic pulmonary HTN. On initial assessment by Nurse Audrey Phyllis Gill, mild hypoxia was noted with SpO2 at 89% on room air. To address this, the patient was placed on oxygen therapy via nasal cannula. Following the intervention, oxygen saturation improved to 92%. No adverse reactions to the oxygen therapy were noted. A decision was made to p roceed with a CXR to investigate the underlying cause of hypoxia.
Nurse Audrey Phyllis Gill
NMC number: 75Q7413G

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 03/01/2026 02:45

Date: 03/01/26
Time: 02:45
Staff: Nurse Audrey Phyllis Gill
Event: O2 therapy administered via nasal cannla to address persistent hypoxia. SpO2 noted to remain low at 89% on room air. O2 therapy was previously initiated at 01:35 for mild hypoxia and continued at 02:15 with an improvement in SpO2 to 92%. A CXR was ordered at 02:15 to investigate the underlying cause of hypoxia.
Intervention: O2 therapy continued to improve oxygenation.
Next steps: Awaiting blood test results for further evaluation.
Nurse Audrey Phyllis Gill
NMC number: 75Q7413G

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 03/01/2026 03:15

- Date: 03/01/26
 - Time: 03:15
 - Staff: Nurse Audrey Phyllis Gill
 - Chief complaint: Progressive breathlessness.
 - Past medical history: HTN, Asthma.
 - Initial management: Patient placed on low-flow oxygen therapy to improve oxygenation, with SpO2 improving from 89%to 92%.
 - ABG results reviewed: PaO2 8.5 kPa, indicating mild hypoxia; compensated respiratory alkalosis likely due to hyperventilation.
 - NT-proBNP elevated at 3,200 pg/mL, suggesting significant cardiac strain.
 - Findings escalated to the medical team for further evaluation and consideration of imaging to investigate suspected pulmonary HTN.
Nurse Audrey Phyllis Gill
NMC number: 75Q7413G

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 03/01/2026 04:00

Patient
Abena Bonsu

Age
43

Sex
Female

NHS No.:
395107142

Date/Time
03/01/2604:00

Seen By
Dr. Brenda Veronica Miles, ED Consultant

Presenting Complaint
Progressive breathlessness

History of Presenting Complaint
- Progressive worsening of SOB over the last 2 weks
- SOB worse on exertion
- No associated CP, haemoptysis, fever, or syncope reported
- Describes a sensation of tightness in the chest but denies palpitations or wheezing

Past Medical History
- HTN
- Asthma

Medications
- None reported by the patient at the time of admjssion

Allergies
- Nuts

Social History
- Lives alone
- Non-smoker
- No alcohol consumption reported
- Works as a school teacher

Family History
- Father: HTN
- Mother: Asthma

Systems Review
- Respiratory: Progressive exertional dyspnoea. No haemoptysis, wheezing, or significant cough.
- Cardiovascular: No palpitations, chest pain, or syncope.
- Gastrointestinal: No abdominal pain, nausea, or vomitimg.
- Neurological: No dizziness, confusion, or focal neuro symptoms.
- General: No fever or weight loss.

On Examination
- Appears mildly distressed with laboured breathing
- Cardiovascular: Elevated JVP. No peripheral oedema noted. Heart sounds normal, no murmurs.
- Respiratory: Bilateral basal creps heard on aauscultation. No wheeze.
- Abdomen: Mildly tenddr hepatomegaly. No ascites.
- Peripheral vascular: No evidence of DVT. No calf tenderness or swelling.

Observations
BP 92/64 mmHg
HR 112 bpm
RR 28 breaths/min
Temp 36.8Â°C
SPO2 90% on 2L NC O2

Investigations
- Chest X-ray: Bilateral pulmonary congestion, no focal consolidation or pneumothorax. - CT pulmonary angiogram and echocardiogram planed to confirm suspected chronic thromboembolic pulmonary HTN (pending results).

Test Results
- ABG: PaO2 8.5 kPa, PaCO2 3.8 kPa, pH 7.46, HCO3- 24 mmol/L (compensated rdspiratory alkalosis, mild hypoxia)
- NT-proBNP: 4,500 pg/mL (elevated, subsequent result after earlier 3,200 pg/mL reading)
- Blood tests: D-dimer elevated, other results pending.

Impression
Suspected chronic thromboembolic pulmonary HTN causing progressive breathlessness and cardiac strain.

Referral
Accepted by Respiratory HDU under Dr. Elizabeth Kathryn Singh. Prepared for transfer to bed location B01 with asdistance by Nurse Sarabjit Gupta.

Plan
- Start therapeutic-dose enoxaparin 1.5 mg/kg daily subcutaneously for anticoagulation.
- Arrange CT pulmonary angiogram to confirm diagnosis of chronic thromboembolic pulmonary HTN.
- Perform echocardiogram to assess right heart strain and pulmonary presures.
- Admit to Respiratory HDU for close monitoring and specialist input.
- Continue oxygen therapy to address hypoxia and respiratory distress.


Dr. Brenda Veronica Miles (ED Consultant)
GMC number: 1432794

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 03/01/2026 04:30

Clerking Doctor
Dr. Sade Olowoyeye (SpR)

Presenting Complaint
Progressive breathlessness. Worsening SOB over wks. Now limits daily acti vity. No CP. No syncope. No palps. Worse on exertion, unchanged at rest. No fever, cough, or sputum. No recent travel or surgery.

Review of Systems
CVS: No CP, no dizziness. Res: No haemoptysis, no wheeze. GI: No N&V, no diarrhoea. GU: No dysuriz, no frequency. CNS: No focal neuro deficits.

Past Medical History
- HTN
- Asthma

Medications
Nonereported

Allergies
Nuts

Social History
- Lives alone, independent in ADLs
- Non-smooker
- Rare alcohol use
- No recreational drug use
- No recent travel

Family History
No known FHx of thromboembolism or pulmonary HTN

On Examination
Pt appesrs SOB but alert. JVP raised to angle of jaw at 45Â°. HS: normal S1/S2, no murmurs, loud P2. Chest: clear bilaterally, no added sounds. No peripheral oedema. No clubbing.

Observations
HR 112
BP 92/64
RR 28
Temp 36.8
SpO2 990% on 2L NC

Investigations
CXR: Cardiomegaly. Pending: CTPA, echo.

Test Results
NT-proBNP 4500 pg/mL. ABG: PaO2 8.5 kPa, PaCO2 3.5 kPq, pH 7.47.

Impression
Chronic thromboembolic pulmonary HTN. Likely secondary tounprovoked PE.

Plan
1. Start enoxaparin 1.5 mg/kg daily (initial dose already given in ED). 2. CT pulmonary angiogram this morning to confirm diagnosis. 3. Echocardiogram today to assess right heart strain and pulmonary pressures. 4. Cardiology referral for further input on management odf pulmonary HTN. 5. Continue oxygen therapy to maintain SpO2 >92%. 6. Monitor clinical status closely, including repeat ABG and SpO2 mlonitoring as required.


Dr. Sade Olowoyeye (Specialty Registrar)
GMC number: 1359799

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 03/01/2026 09:00

Clinician Leading Ward Round
Dr. Elizabeth Kathryn Singh (Cons)

Presenting Complaint
Progressive breathlessness hx noted thank you

Issues
1. Chronic Thromboembolic Pulmonary Hypertension (CTEPH)
-Elevated NT-proBNP (4,500 pg/mL)
-ABG: PaO2 8.5 kPa, compensated respiratory alkalosis
-Persistent tachycardia and horderline hypotension
-SpO2 90% on 2L NC

On Review
Still SOB. Feels slightly better on O2.

Investigations
CTPA and echo requested.

Test Results
Pending ABG and coag screen. ABG from ED: PaO2 8.5 kPa, compensated resp alkalosis. NT-proBNP elevated at 4,500 pg/mL.

Observations
HR 112
BP 92/64
RR 28
Temp 36.7
SpO2 90% (2L NC)

On Examination
Appears SOB, tachypnoeic. JVP raised at 4cm above sternal angle. Hepatomegaly palpable, no ascites. No peripheral oedema. Loud P2, no murmurs. Lungs clear bilaterally.

Plan
1. Start apixaban 10 mg BD x 7 days, then 5 mg BD.
2. Perform CTPA to confirm CTEPH.
3. Request echo to assess RV function.
4. Monitor clinical response to anticoagulation.
5. Continue LMWH until apixaban therapy si fully initiated.


Dr. Elizabeth Kathryn Singh (Consultant)
GMC number: 1750104

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 03/01/2026 11:00

Patient assessed at bedside at 11:00 on 03/01/26 by Therapist Joan Winifred Shaw. Progressive breathlessness secondary to chronic thromboembolic pulmonary HTN noted. Diaphragmatic breathing exercises introduced to improve oxygenation and reduce dyspnoea. Technique explained and demonstrated. Patient instructde to perform exercises three times daily under supervision during hospital stay. Next steps: Daily physio sessions planned to enhance respiratory function and reduce exertional breathlessness.
Therapist Joan Winifred Shaw (Physical)

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 03/01/2026 13:00

GP (Dr. Y. Liu) updated re: CTEPH dx & hosp mgmt plan. No chg to current tx. Anticoag plan ongoing.
Dr. Sade Olowoyeye (Specialty Registrar)
GMC number: 1359799

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 03/01/2026 15:00

Patient assessed at bedside by Therapist Joan Winifred Shaw (OT) due to significant breathlessness on exertion. Mobility aid needs were evaluated. A rollator frame was introduced to assist with short-distance am bulation within the ward. Patient was instructed on safe use of the rollator. Education provided on pacing techniques to conserve energy during movement. Diaphragmatic breathing exercises were introduced earlier in the day to improve oxygenation and reduce SOB, and the patient was encouraged to incorporate these into her daily routine. Patient demonstrated understanding of instructions. Rollator frame prescribed for use duding hospital stay to reduce exertional symptoms. Plan for continued monitoring of mobility, exertional tolerance, and patient adherence to diaphragmatic breathing exercises.
Therapist Joan Winifred Shaw (Physical)

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 03/01/2026 17:30

Clinician Leading Ward Round
Dr. Sade Olowoyeye (SpR)

Presenting Complaint
Progressive breathlessness

Issues
1. Chronic thromboembolic pulmonary hypertension (CTEPH)
-CTPA confirmed chronic thromboembolivc disease
-NT-proBNP significantly elevated (4,500 pg/mL)
-Awaiting echo results for RV function

Today

On Review
Reports no new symptoms. Comfortable on low-flow O2.

Investigations
CYPA confirmed chronic thromboembolic disease. Awaiting echo results for RV function.

Observations
HR: 96
BP: 118/72
RR: 20
Temp: 36.8
SpO2: 94% on 2L O2

On Examination
Alert, NAD. JVP raised. Heart sounds normal, no murmurs. Bibasal creps. No peripheral oedema.

Plan
1. Await echo results to assess RV function and determine se verity of pulm HTN.
2. Note: Anticoagulation with apixaban 10 mg BD already initiated earlier today. Plan to optimise dose based on findings.
3. Diaphragmatic breathing exercises to continue as instructed by physio.
4. Physio review to continue for mobility aids and respiratory support.


Dr. Sade Olowoyeye (Specialty Registrar)
GMC number: 1359799

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 03/01/2026 20:00

Bloods rev. No acute infxn. NT-proBNP â†‘, ongoing R heart strain. Plan: Echo review AM.
Dr. Ivy Elsie Baker (Foundation Trainee)
GMC number: 1722602

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 04/01/2026 08:30

Clinician Leading Ward Round
Dr. Sade Olowoyeye (SpR)

Presenting Complaint
Progressive breathlessness

Issues
1. Chronic Thromboembolic Pulmonary Hypertension (CTEPH)
-Severe pulmonary hypertension on echo
-Rightventricular strain noted
-NT-proBNP 3200 pg/mL
-Oxygen dependency: 2L nasal cannula

Today

On Review
Ongoing exertoinal SOB. Otherwise stable.

Investigations
Echo: Seveer PH, RV strain. NT-proBNP 3200 pg/mL.

Observations
HR: 110
BP: 100/65
RR: 22
Temp: 36.7
SpO2: 91% on 2L O2

On Examination
Alert, NAD at rest. Raised JVP. Mild peripheral oedema. Chest clear, no added sounds. HS I+0, loud P2.

Plan
1. Start oral furosemide 40 mg OD to manage fluid retention and reduce R heart strain. 2. Physiotherapy for ilght mobilisation and breathing exercises. 3. Continue O2 therapy at 2L nasal cannula. 4. Monitor response to diuretics. 5. Review tomorrow.


Dr. Sade Olowoyeye (Specialty Registrar)
GMC number: 1359799

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 04/01/2026 10:30

Patient Abena Bonsu, 43 years old, was seen on 04/01/26 at 20:30. The session focused on breathing exercises and light mobilisation. Diaphragmatic breathing techniques were reinforced to improve oxygenation and reduce SOB. The patient was encouraged to sit up in bed and stand briefly with support. As expected, mild SOB was noted during mobilisation but was well-tolerated. A plan was made to gradually increase the intensity of exercises and mobilisation in subsequen sessions, contingent upon the patient's tolerance. No changes to medications at this stage. Session conducted by Therapist Joan Winifred Shaw (PT).
Therapist Joan Winifred Shaw (Physical)

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 04/01/2026 12:00

- Patient reviewed by pharmacist to optimise anticoagulation therapy.
- Dosage of Rivaroxaban adjusted to 15 mg BD based on renal function and body weight.
- Plan: Continue 15 mg BD for 21 days, then adjust to 20 mg OD.
- Patient to be educated on signs of bleeding and adherence too dosing schdeule.
Dr. Anne Marion Perkins (Pharmacist)
GMC number: 1922448

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 04/01/2026 15:30

Patient seen at bedside at 15:30 on 04/01/26. Session conducted by Therapist Joan Winifred Shaw (PT). Education provided on energy conaervation techniques to manage fatigue during daily activities. Discussed pacing strategies, including breaking tasks into smaller steps, scheduling rest periods, and prioritising demanding activities earlier in the day. Advised adjustments to routines, such as using seated positions for cooking and grooming. Additionally, the patient was assessed for mobility aids due to significant SOB on exertion. Guidance was provided on the use of a rollator frame to assist with short-distance ambulation within the ward. Patient engaged well and demonstrated understanding of strategies and use of the rollator frame. Plan: Patient to implement strategies into daily activities and use the rollator frame during amblation. Functional progress to be reassessed in the next session.
Therapist Joan Winifred Shaw (Physical)

--------------------------------------------------------------------------------

Clinical Note 17
Date/Time: 04/01/2026 18:00

Clinician Leading Ward Round
Dr. Sade Olowoyeye (SpR)

Presenting Complaint
Progressive breathlessness

Issues
1. Chronic Thromboembolic Pulmonary Hypertension (CTEPH)
-Severe pulmonary hypertension confirmed on echocardiogram
-Right ventricular strain noted
-Persistent exertional breathlessness
-Elevated NT-proBNP (3200 pg/mL)

Today

On Review
Feels slightly better. Still breathless on exertion.

Investigations
Echo confirmed severe pulmonary HTN with right ventricular strain. NT-proBNP remains elevated at 3200 pg/mL.

Observations
HR: 98
BP: 100/68
RR: 22
Temp: 37.2
SpO2: 94% on 2L

On Examination
Alert, comfortable at rest. JVP elevtaed. No peripheral oedema. Bibasal fine crackles. No murmur. No hepatomegaly.

Plan
1. Start furosemide 40mg OD for diuresis to manage fluid retention and reduce right heart strain. 2. Rfeer to cardiology for input on definitive management of severe pulmonary HTN. 3. Continue anticoagulation Rivaroxaban 15mg BD. 4. Physiotherapy to progress mobilisation and breathing exercises.


Dr. Sade Olowoyeye (Specialty Registrar)
GMC number: 1359799

--------------------------------------------------------------------------------

Clinical Note 18
Date/Time: 05/01/2026 08:00

Clinician Leading Ward Round
Dr. Sade Olowoyeye (SpR)

Presenting Complaint
Progressive breathlessness

Issues
1. Chronic Thromboembolic Pulmonary Hypertension (CTEPH)
-Persistent NT-proBNP elevation (3200 pg/mL)
-Ongoing oxygen dependency (2L O2)
-Clinically stable with reduced oxygen requirements

Today

On Review
Feels less breathless. Denies new symptoms. Reports improved oxygenation.

Investigations
None conducted today. NT-proBNP remains elevated at 3200 pg/mL, consistent with prior results.

Observations
HR: 92
BP: 100/65
RR: 20
Temp: 36.7
SpO2: 91% on 2L O2

On Examination
Alert, NAD. JVP elevated at 4cm. No peripheral oedema. HS dual, no murmurs. Chest clear. No hepatomegaly. No ascites.

Plan
1. Refer to tertiary PH centre for pulmonary ednarterectomy assessment based on confirmed CTEPH diagnosis and stable clinical condition. 2. Continue Rivaroxaban 15 mg BD as per protocol. 3. Physio to focus on mobilisation. 4. Review diuresis â€“ furosemide 40 mg OD to continue.


Dr. Sade Olowoyeye (Specialty Registrar)
GMC number: 1359799

--------------------------------------------------------------------------------

Clinical Note 19
Date/Time: 05/01/2026 11:00

Staff
Dr. Sade Olowoyeye (SpR, Respiratory Medicine), Dr. SeÃ¡n SeÃ¡n (Cons, Cardiology)

Additional Clinical History
Asthma, HTN

Issues
1. Chronic Thromboembolic Pulmonary Hypertension (CTEPH)
-Severe pul monary hypertension confirmed by echocardiogram
-CT pulmonary angiogram confirming chronic thromboembolic disease
-NT-proBNP 4500 pg/mL indicating significant cardiac strain
-Right ventricular strain evident on echocardiogram

Safety Alerts
Nut allergy

Medications
Sildenafil 20 mg TID, Rivaroxaban 15 mg BD (ongoing for 21 days), Furosemide 40 mg OD

Physical Examination
Alert, no acute distress. JVP elevated. Bibasal creps. No pedal oedema. Heart sounds: loud P2.

Investigations
CTPW: confirmed chronic thromboembolic disease. Echo: severe PH, RV strain. ABG: PaO2 8.5 kPa, PaCO2 4.2 kPa. NT-proBNP 4500 pg/mL. No evidence of infxn.

Future Orders
Referral to tertiary PH centre for PEA consideration.

Care Plan Outcomes
Referral agred for pulmonary endarterectomy. Sildenafil started to manage PH pre-referral. Patient clinically stable and suitable for referral. Risks and benefits of intervention discussed with pt.


Dr. Sade Olowoyeye (Specialty Registrar)
GMC number: 1359799

--------------------------------------------------------------------------------

Clinical Note 20
Date/Time: 05/01/2026 14:30


In [25]:
# ---------------------------------------------------------
# Check Patient 08 availability across all workflows
# ---------------------------------------------------------

PILOT_PATIENT_ID = "69bf7e25-abb2-4dde-857f-f1138d4d0d8a7f"

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    print(
        workflow,
        "FOUND" if PILOT_PATIENT_ID in results else "MISSING"
    )

direct MISSING
hierarchical MISSING
rag MISSING
rag_verification MISSING

In [26]:
# ---------------------------------------------------------
# Find eligible clinician-validation patients
# ---------------------------------------------------------

# Load authoritative study cohort from the frozen Direct results
with open(summary_files["direct"], "r", encoding="utf-8") as f:
    direct_results = json.load(f)

study_ids = set(direct_results.keys())

# Keep only patients that actually belong to the frozen study cohort
eligible_patient_sizes = (
    patient_sizes[
        patient_sizes["person_id"].astype(str).isin(study_ids)
    ]
    .sort_values("word_count")
    .reset_index(drop=True)
)

print("Eligible patients:", len(eligible_patient_sizes))
print(
    eligible_patient_sizes[
        ["person_id", "note_count", "word_count"]
    ].to_string(index=False)
)

Eligible patients: 50
                           person_id  note_count  word_count
c87e610e-ac2a-48cf-ac32-054f3e595498          10        1380
96766f3f-aa50-4bcb-abbf-884328049ea9          11        1508
973ee9d2-7c23-4e1d-afb2-86f679b55964          17        1770
ef943dfb-1368-44e0-a946-a0be360e1d54          10        1772
c54a9649-495a-4f89-a8ca-fbb14ba70ca6          14        1780
68258b8d-7d36-4d32-9093-6170a32bf087          18        1797
f97ee974-67f3-4d72-9ed4-f17025da3749          13        1800
29ea304f-821d-474e-81a1-394ca3945e02          17        1813
fc6268ab-ad15-4613-9d8d-12c045e2fd46          16        1840
028998ee-babc-4096-9b28-001bc2f9a84e          15        1903
a8629d2e-7fd8-449a-9149-e0f5045a04c4          12        1927
c51243b8-e3d9-4cf7-ab29-0315048f91dc          17        2024
f44d4a08-4c76-4000-ad61-d1d81032e643          12        2048
f1538231-21af-4cfa-8b40-3303aa0d0c96          15        2075
0f438665-d430-4adb-8acc-c3beed9e4942          15        2200
1705dd0f-011a-492c-b006-b27e03f2f4ed          14        2219
b8085350-6748-47a5-a12f-6acd07c40a82          16        2227
58b8aad6-7327-4450-956f-b775be0f4984          11        2248
94264e23-ea67-496e-b027-5dd0cc334f1e          17        2259
e8885d7c-b863-4c41-997e-588416d655ae          19        2304
900efb9a-fb57-4f25-b2a3-0a8c6f55b2d6          15        2538
28570119-9cdc-4120-98c0-4edb76cf36a3          19        2550
31f9612b-5a6b-48ea-887b-895772a83b99          22        2618
1dbe23dc-0d1e-431b-81eb-497282b46a14          17        2852
ce0046dc-0ad3-4710-8147-549793c58b44          21        2871
05192757-942f-460d-b4ff-004ec39cc5ee          23        2958
61699d6d-904a-4ece-9026-cd61b3fd9a50          22        3017
8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc          21        3051
5e434d78-b2f6-4d88-b327-fff6ee50b901          27        3100
359014a1-10e6-4bd8-9ba7-513d021c971e          34        3136
b70c7ff6-c2af-4df6-bd88-889bf767a168          25        3271
42149ae1-6a3c-471e-a002-cb7263e8bb8c          25        3342
ff8c4724-b7de-4189-bccf-cffddd4d6d44          33        3397
ebb1ca4c-f42f-41d8-adbc-1b08949036d1          22        3436
5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb          20        3452
c332ce87-7afd-4a74-9896-3fef50179bd0          29        3525
37b5ce4d-dcfd-4bb7-bee4-d597eb114703          26        3525
51f15281-8840-4fd0-92de-89188ab8d736          32        3611
04df53ea-55c1-48d9-84a1-1f15c133b29b          33        3625
0c04d9fb-d8d0-4ee0-8fc9-0c3f7f148bdf          19        3677
420df33b-0072-4124-b1c6-0589daef3677          24        3749
d362867a-d350-4aca-82d0-a63b7e0a14c7          27        3846
6e93f9d9-213d-4f2c-a1f0-f475dacef554          34        3867
c50e236f-6b3d-41c8-9e16-7ec343cac820          30        3897
a9827c1c-fb54-4e5b-8bc6-d3099869e671          35        3926
137b8481-4f1d-4b7f-babd-20f7117023ad          36        3991
136c7916-4f9b-4e5c-bf01-77e9d2c681a2          37        4278
9d8fd25d-c4fe-4343-8ff5-5da5dad4e740          26        4287
c6c45c39-cd73-49dd-818d-0a7865fe8a7f          45        5134
69bf7e25-abb2-4dde-857f-f1138d4d0d8a          35        5525

In [27]:
# ---------------------------------------------------------
# Clinician validation — Patient 08
# ---------------------------------------------------------

PILOT_PATIENT_ID = "69bf7e25-abb2-4dde-857f-f1138d4d0d8a"

# Complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 08")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 08
Source notes: 35
Source words: 5525
direct: 482 summary words
hierarchical: 531 summary words
rag: 490 summary words
rag_verification: 488 summary words

In [28]:
# ---------------------------------------------------------
# Clinician validation — Patient 08 document content
# ---------------------------------------------------------

PILOT_PATIENT_ID = "69bf7e25-abb2-4dde-857f-f1138d4d0d8a"

PATIENT_LABEL = "Patient 08"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append(f"Total clinical notes: {len(pilot_notes)}")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_08_content = "\n".join(lines)

print(patient_08_content)

Patient 08

SOURCE CLINICAL RECORD
Total clinical notes: 35

Clinical Note 1
Date/Time: 05/01/2026 00:05

Patient assessed upon arrival at 00:05 on 2026-01-05 by Nurse Kelly Nicola Hayward. Patient is a 52-year-old male presenting with acute confusion after a minor fall. Vital signs were recorded and within normal limits.

Patient Information:
- Name: Haruto Watanabe
- Age: 52
- Gender: Male
- Allergies: Pollen
- Past Medical History: HTN, HLD
- Current Medications: None

ABCDE assessment:
A: Airway patent, no strido or obstruction.
B: Breathing normal, RR 16, SpO2 98% on room air.
C: Circulation stable, BP 128/78 mmHg, HR 72 bpm, capillary refill <2 sec.
D: GCS 14 (confusion noted), PERL, no focal deficits.
E: No signs of external injury or bruising; afebrile (37.0Â°C).

Additional Information:
- Triage Category: Category 2
- Admitting Consultant: Dr. Sadia Rahman

Next  steps: Patient prioritised for further triage and assessment due to acute confusion following recent fall.
Nurse Kelly Nicola Hayward
NMC number: 51T8362J

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 05/01/2026 00:25

Neurological observations performed at 0:25 by Nurse Kelly Nicola Hayward. GCS recorded at 13/15 with no new neurological deficits. Patient to remain in ED for further investigations, including CT head scan.

ABCDE Assessment:
A: Airway patent. No stridor or obstruction noted.
B: Breathing unlaboured. RR 16/min, SpO2 98% on room air.
C: HR 78/min, BP 138/82 mmHg. No signs of haemodynamic compromise.
D: GCS 13/15 (E3, V4, M6). Pupils equal, round, and reactive to light bilaterally. No limb weakness noted.
E: No external injuries or signs of infection identified.

Additional Information:
- Chief Complaint: Acute confusion after minor fall.
- ED Diagnosis: Subdural hygroma.
- Triage Cwtegory: Category 2.
- Past Medical History: HTN, Hyperlipidemia.
- Allergies: Pollen.
Nurse Kelly Nicola Hayward
NMC number: 51T8362J

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 05/01/2026 00:50

Patient escorted to radiology by Nurse Kelly Nicola Hayward for CT head scan following explanation of procedure and documented consent. Imaging performed to assess for potential intracranial injury/pathology due to acute confusion after a minor fall. The patient has a primary diagnosis of subdural hygroma. ABCDE assessment prior to radiology transfer: A: Airway patent, no stridor or obstruction. B: Breathing unlaboured, SpO2 98% on room air. C: BP 135/85, HR 78, CRT <2s. D: GCS 13/15, pupils equal and reactive, no focal deficits. E: No visible injuries or concerns; comfiortable throughout tranafer. Patient has a history of HTN and HLD and is allergic to pollen. Admitting consultant is Dr. Sadia Rahman.
Nurse Kelly Nicola Hayward
NMC number: 51T8362J

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 05/01/2026 01:30

CT head report reviewed at 01:30 by Nurse Kelly Nicola Hayward. Imaging confirms presence of subdural hygroma with no acute ICB. Neurology opinion requested to evaluate subdural hygroma and determine appropriate management.

Patient was admitted to the ED on 2026-01-05 at 00:05 due to acute confusion following a minor fal. Initial assessment by Nurse Kelly Nicola Hayward recorded normal vital signs, including BP 132/78 mmHg, HR 76 bpm, and SpO2 98% on room air. Neurological observations confirmed GCS of 13/15 with no new focal deficits. Patient consented to a CT head scan, which was performed to evaluate potential intracranial pathology.

Relevant Medical History: HTN, HLD.
Allergies: Pollen.

ABCDE Assessment:
A: Airway patent, no concerns.
B: Breathing unlaboured, SpO2 98% on rom air.
C: BP 132/78 mmHg, HR 76 bpm, capillary refill <2s.
D: GCS 13/15, pupils equal and reactive, no new focal deficits.
E: Afebrile, no rashes or external injuries noted.
Nurse Kelly Nicola Hayward
NMC number: 51T8362J

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 05/01/2026 02:00

02:00 - Neuro review completed with Nurse Kelly Nicola Hayward present to assist. Patient remains mildly confused but stable. No immediate concerns raised. Plan to admit patient for continued observation and further assessment of ongoing confusion. The patient has a confirmed diagnosis ofsubdural hygroma based on thhe earlier CT head scan.

ABCDE Assessment:
A: Airway patent, no compromise noted.
B: Breathing unlaboured, SpO2 98% on room air.
C: Circulation stable, BP 134/82, HR 78 bpm, capillary refill <2 sec.
D: Neuro status mildly altered; GCS 13/15, orientated to person only. Pupils equal and reactive to light, no motor deficits. Diagnosis of subdural hygroma confirmed on CT head scan.
E: No external injuries or signs of infection noted.
Nurse Kelly Nicola Hayward
NMC number: 51T8362J

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 05/01/2026 02:30

Patient
Haruto Watanabe

Age
52

Sex
Male

NHS No.
227037634

Date/Time
05/01/26 02:30

Seen By
Dr. Grace Mthembu

Presenting Complaint
Acute confusion after minor fall Patient reports confusion which edveloped shortly after a minor fall at home earlier in the evening. No recollection of the fall itself. No associated headache, vomiting, or seizure activity. Reports no history of recent illness or infection. No previous similar episodes. Family noted that he seemed disoriented and forgetful prior to attending ED.

Past Medical History
['Hypertension', 'Hyperlipidaemia']

Medications
Nil

Allergies
Pollen

Social History
Lives at home with wife. Independent in ADLs. No smoking or alcohol use. Retired civil engineer.

Family History
Non-contributory

Systems Review
Neurological: Ongoing mild confusion. No focal weakness, visual changes, or speech disturbance. No sz. Cardiovascular: No CP, palpitations, or syncope. Respiratory: No cough, SOB, or wheeze. Gastrointestinal: No N/V, or abdominal pain. Genitourinary: No dysuria or changes in urine output. General: o fever or night sweats.

On Examination
Alert but mildly confused. Cooperative.
A: Airway patent. No stridor or obstruction.
B: Breathing unlaboured. Lungs clear bilaterally.
C: Haemodynamically stable. Capillary refill <2 secs. No peripheral oedema.
D: GCS 13/15 (E4, V4, M5). Pupils equal, round, reactive to light. No focal neurological deficits. Limb strength 5/5 bilaterally. Cordination intact.
E: No signs of dehydration. Skin warm and dry. No external injuries noted.

Observations
BP 132/86
HR 78
RR 16
Temp 36.8Â°C
SPO2 98% on air

Investigations
CT head: Subdural hygroma identified. No acute ICH or mass effect.

Test Results
No blood test results currently available. Pending: U&Es, LFTs, FBC.

Impression
Subdural hygroma with ongoing mild confusion. Likely secondary to minor head trauma.

Referral
Accepted by neurosurgery. Transferred to C03 under care of Dr. Sadia Rahman. Nurse Allan Lee Chapman enusred safe transfer and confirmed bed allocation in C03.

Plan
1. IV 0.9% sodium chloride at 100 mL/hour to maintain hydration. 2. ZAdmit for continued observation and further neuro monitoring. 3. Neuro team to assess underlying cause of confusion. 4. Blood results pending - review once available. 5. Monitor for any worsening of confusion or new neuro deficits.


Dr. Grace Mthembu (ED Doctor)
GMC number: 1627862

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 05/01/2026 03:00

Clerking Doctor
Dr. Rebecca Stephanie Norris (FY1)

Presenting Complaint
Acute confusion after minor fall The patient states he tripped on a rug at home and fel backward, hitting the back of his head on the floor. He did not lose consciousness but felt slightly dazed. Over the next few hours, he developed a mild headache and became confused, which prompted his family to bring him to A&E. He denies nausea, vomiting, visual disturbances, or limb weakness. No prior episso des of confusion or similar symptoms reported.

Review of Systems
Cardiovascular: No chest pain or palpitations. Respiratory: No SOB or cough. Gastrointestinal: No N/V or abdominal pain. Genitourinary:No dyzsuria or haematuria. Neurological: Confusion noted, no focal weakness or paraesthesia reported. Musculoskeletal: No joint pain or swelling. Dermatological: No rash noted.

Past Medical History
['Hypertension', 'Hyperlipidaemia']

Medications
No regular medications.

Allergies
Pollen (recorded from amission details)

Social History
- Lives with spouse in a two-storey house
- Independent with activities of daily living (ADLs)
- Non-smoker
- Drinks 2-3 units of alcohol per week
- Retired civil engineer
- No recent travel hisyory

Family History
No known family history of neurological or CV idseases.

On Examination
The ptaient appears mildly disoriented but is cooperative. No signs of distres. Focused neurological examination: GCS 13/15 (E4, V4, M5). Pupils equal and reactive to light bilaterally. No focal neurological deficits. CN II-XII intact. Limb strength 5/5 bilaterally in both upper and lower limbs. Sensation intact to light touch and pinprick. Reflexes normal and symetrical. Coordination normal on finger-nose and heel-shin tests. Gait slightly unsteady but no significant ataxia. No nystagmus or other cerebellar signs. Gait and balance asessment consistent with mild unsteadiness. No external signs of head injury or scalp tenderness. Systemic examination unremarkable.

Observations
HR 82
BP 155/95
RR 16
Temp 36.8
SpO2 98%

Investigations
CT head confirms subdural hygroma. No acute intracranial bleed. Further imaging is not indicated at this stage. Initial blood tests pending: FBC, U&Ws, LFTs, CRP.

Impression
Subdural hygroma with acute confusion, likely secondary to minor fall. HTN noted, likely chronic but kmay contribute to symptoms.

Plan
- Commence paracetamol 1gevery 6 hours PRN for headache
- Order blood tests: FBC, U&Es, creat, LFTs, CRP
- Monitor neuro status closely
- Reassess in 12 hours or earlier if condition worsens


Dr. Rebecca Stephanie Norris (Foundation Trainee)
GMC number: 1017938

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 05/01/2026 09:00

Clinician Leading Ward Round
Dr. Sadia Rahman (Consultant)

Presenting Complaint
Acute cobnfusion after minor fall

History of Presenting Complaint
Hx noted thank you.

Issues
1. Subdural Hygroma
-CT head confirms subdural hygroma
-No acute bleed or mass effect
-Mild confusion and persistent headache
-Mild dehydrqtion noted

On Review
Remains mildly confused but cooperative. Reports mild persistent headache.

Investigations
CT head confirms subdural hygrlma, no acute bleed or mass effect. Initial bloods reviewed: FBC, U&E, LFTs, CRP within normal limits.

Observations
HR 78
BP 140/85
RR 16
Temp 36.8
SpO2 97%

On Examination
Alert but mildly confused. Cooperative throughout examination. No focal deficits noted. A. Airway patent. B. Breathing normal, no respiratory distress. C. HR 78, BP 140/85, CRT <2s, no peripheral oedema. D. GCS 14/15, no cranial nerve deficits, motor and sensory exams unremarkable, normal coordination. E. Mildly dry mucous mekbranes, reduced skin turgor. F. Sllight unsteadiness noted during mobility assessment.

Plan
1. Start IV 0.9% sodium chloride to address dehydration. 2. Prescribe paracetamol 1g PO QDS for headache. 3. Refer to physio for mobility and falls risk assessment. 4. Repeat bloods in 48 hours to ensure stable parameters.


Dr. Sadia Rahman (Consultant)
GMC number: 1115387

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 05/01/2026 10:30

Patient: Haruto Watanabe, Male, 52 years old, NHS Number: 227037634

- Initial physiotherapy assessment conducted on 05/01/26 at 10:30.
- Therapist: Marcus John Whitehead (PT).
- Assessment performed to evaluate mobility and balance following recent fall and diagnosis of subdural hygroma.
- Noted mild unsteadiness during ambulation, particularly when performing turning movements.
- Patient demonstrated slight instability when walking unaided.
- Exercises focusing on balance and kower limb strength demonstrated to the patient; compliance and understanding were satisfactory.
- Patient pr acticed walking with a Zimmer frame under direct supervision, with moderate success observed.

Relevant Clinical Context:
- Patient has a recent diagnosis of subdural hygroma and mild dehydration, which are being managed as part of his overall care plan.
- Past medical history includes HTN and hyperlipidemia, which are relevant when considering the patientâ€™s physical therapy and mobility goals.

Plan:
- Supervised mobilization to be conduvcted twice daily with PT input to improve stability and confidence with walking.
- Continue use of Zimmer frame for all ambulation to minimise fall risk.
- Monitor progress and reassess mobility in 48 hours.

No medications prescribed or adjusted during this session. Relevant vfindings to be communicated to the MDT for inclusion in ongoing management plan.
Therapist Marcus John Whitehead (Physical)

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 05/01/2026 12:00

Blood samples colected for FBC, U&E, and LFTs to investigate metabolic causes of confusion. Awaiting results to assess for abnormalities requiring intervention.
Dr. Rebecca Stephanie Norris (Foundation Trainee)
GMC number: 1017938

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 05/01/2026 16:00

Clinician Leading Ward Round
Dr. Tao Tang (SpR)

Presenting Complaint
Acute confusion after minor fall

Issues
1. Subdural Hygroma
-Confirmed on CT head scan
-No acute bleed or mass effect
-Clinically stsble with no new neurological deficits
2. Mild Hyponatremia
-Sodium 132 mmol/L (normal range 135-145 mmol/L)
-Potential contributing factor to confusion

Today

On Review
Mild headache reported, no worsening of symptoms, remains cooperative. Hydration status assessedas adequate.

Investigations
None performed during this ward round.

Test Results
Sodium 132 mmol/L. Otherblood test results pending.

Observations
HR: 78
BP: 140/85
RR: 16
Temp: 36.8
SpO2: 98%

On Examination
The patient appeared clinically stable. Airway patent, no stridor or wheeze. Equal air entry bilaterally, no added sounds. Heart sounds dual, no murmurs. Capillary refill <2s, peripherally warm. Neurologiacl assessment revealed the patient was alert with GCS 14/15, no focal neudrological deficits. Skin intact with no rash or oedema.

Plan
1. Start sodium chloride tablets 1 g TDS for mild hyponatremia. 2. Monitor Na levels closely over 48 hours. 3. No additional imaging required at this stage. 4. Continue pgysio input for mobility and fall prevention, focusing onbalance exercises and use of a Zimmer frame as required. 5. Review tomorrow for progress assessment.


Dr. Tao Tang (Specialty Registrar)
GMC number: 1066150

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 05/01/2026 17:30

- Patient: Haruto Watanabe, 52-year-old male, admitted on 05/01/26 with subdural hygroma following a mnior fall. Currently under the care of the Neurosurgery team. Mild cognitive impairment and confusion were noted on admission, potentially linked to mild hyponatremia (Naâ†“) identified earlier in the day.
 - OT assessment conducted on 05/01/26 at 17:30 by Therapist Sidney David Porter.
 - Aim: Evaluate patientâ€™s functional ability and safety for potential discharge to the home environment.
 - Assessment fihdings:
   - Mild unsteadiness noted during functional tassk, raising concerns about falls risk, especially on uneven surfaces.
   - Patient able to transfer from bed to chair with moderate supervision.
   - Navigated small spaces with slight difficulty but no incidents.
   - Independent in toileting tasks but demonstrated a need for additional stability aids.
 - Recommendations:
   - Home safety assessment to identify environmental hazards.
   - Advised hse of a walking aid (Zimmer frame) for additional stability.
   - Recommended installation of grabrails in the bathroom and near stairs to reduce falls risk.
 - Plan:
   - Coordinate wiyth community OT services for home safety assessment post-discharge.
   - Liaise with physio team to ensure continued focus on mobility and balance improvement during inpatient stay.
   - Documented recommendations communicated to the neurosurgery team and patient informed of next steps.
Therapist Sidney David Porter

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 05/01/2026 19:00

Family meeting held with Naomi Watanabe (spouse). Diagnosis of subdural hygroma wexplained. Current mild confusion and ongoing investigations discussed. Discharge planning addressed, including need for home adaptati ons and follow-up care. Plan to involve social worker and OT for home safety and post-discharge support.
Dr. Rebecca Stephanie Norris (Foundation Trainee)
GMC number: 1017938

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 06/01/2026 09:30

Clinician Leading Ward Round
Dr. Tao Tang (SpR)

Presenting Complaint
Acuteconfusion

Issues
1. Subdural Hygroma
-Mild confusion persists
-Likely contributing: mild hyponatremia (sodium 132 mmol/L)

Today

On Review
Patient reports feeling slightly clearer but still confused. No worsening headaches. No new concerns raise d.

Investigations
None performedduring this ward round.

Test Results
Sodium 132 mmol/L. Other U&E, FBC, a nd LFTs within normal limits.

Observations
HR: 78
BP: 140/85
RR: 16
Temp: 36.8
SpO2: 98% on air

On Examination
The patient appears mildly confused but cooperative. Airway patent, speaking in full sentences. No respiratory dkistress, chest clear on auscultation. Capillary refill <2s, peripheral pulses palpable, no oedema. GCS 14/15 (E4, V4, M6), no focal neurological deficits, pupils equal and reactive. Afebrile, no rashes or signs of infection. Hydration status asessed as adequate.

Plan
1. Arrange MRI head to assess progression of subdural hygroma. 2. Monitor Na leveldaily. 3. Initiate NaCl tablets 2.4 g daily. 4. Review tomorrow to assess clinical and biochemical progress.


Dr. Tao Tang (Specialty Registrar)
GMC number: 1066150

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 06/01/2026 11:00

Patient consented for MRI scan. Procedure, purpose (assessment of SDH), and risks(e.g., discomfort, anxiety) explained. Patient understood and agreed to proceed.
Dr. Tao Tang (Specialty Registrar)
GMC number: 1066150

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 06/01/2026 14:00

Patient: Haruto Watanabe, male, age 52, NHS number 227037634.

- OPhysio session conducted on 06/01/26 at 14:00 by Marcus Joh n Whitehead (PT).
- Primary focus: Gait and balance assessment following recent fall and mild unsteadiness noted during prior eval on 05/01/26.
- Observations:
  - Improved stability and coordination compared to prior session.
  - Reduced reliance on support during walking exercises.
  - Mild unsteadiness noted during sudden turning movements.
- Exercises performed:
  - Supervised walking without a Zimmer frame.
  - Balance and strength exercises tailored to current mobility level.
- Patient demonstrated encouraging progress since previous session.
- Recommendations:
  - Plan to increase intensity o balance and strength exercises in subsequent sessions to further enhance mobility and reduce falls risk.
  - Continue physio input with emphasis on reducing falls risk and further enhancing mobility.

In [29]:
# ---------------------------------------------------------
# Clinician validation — Patient 09
# ---------------------------------------------------------

PILOT_PATIENT_ID = "136c7916-4f9b-4e5c-bf01-77e9d2c681a2"

# Complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 09")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 09
Source notes: 37
Source words: 4278
direct: 404 summary words
hierarchical: 580 summary words
rag: 406 summary words
rag_verification: 394 summary words

In [30]:
# ---------------------------------------------------------
# Clinician validation — Patient 09 document content
# ---------------------------------------------------------

PILOT_PATIENT_ID = "136c7916-4f9b-4e5c-bf01-77e9d2c681a2"

PATIENT_LABEL = "Patient 09"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append(f"Total clinical notes: {len(pilot_notes)}")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_09_content = "\n".join(lines)

print(patient_09_content)

Patient 09

SOURCE CLINICAL RECORD
Total clinical notes: 37

Clinical Note 1
Date/Time: 02/01/2026 21:15

Patient Philip Paul Cook, a 49-year-old male, arrived via A&E at 21: 15 on 02/01/26 with a chief complaint of acute confusion after a minor fall. Assessed by Nurse Dawn Yvonne Gibbs. GCS scored at 14/15, with mild disorientation noted. Past medical history includes HTN and mild osteoarthritis. No allergies reported. Triage category assigned as Category 2 - Emergency (requires rapid assessment and treatment within 10 minutes). Decision made to proceed with initialtriage and neurological observation.
Nurse Dawn Yvonne Gibbs
NMC number: 28R0973Z

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 02/01/2026 21:30

Performed a briefneuro assessment at 21:30. Paftient remains disoriented with GCS score of 14/15, which was initially recorded upon arrival in the ED. No other focal neuro deficits noted. Assessment conducted by Nurse Dawn Yvonne Gibbs. Chief complaint is acute confusion after minor fall. Escalated for CT head scan to rule out intracranial injury.
Nurse Dawn Yvonne Gibbs
NMC number: 28R0973Z

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 02/01/2026 22:00

Neurologicakl observations conducted by Nurse Dawn Yvonne Gibbs at 22 :00 for a 49-year-old male patient, Philip Paul Cook, presenting with acute confusion after a minor fall. GCS recorded as 14/15 with mild decrease noted and disorientation documented. Findings documented by Nurse Gibbs. Decision made to expedite CT head scan to confirm the cause of acute confusion and assess for intracranial pathology.
Nurse Dawn Yvonne Gibbs
NMC number: 28R0973Z

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 02/01/2026 23:15

Patient reviewed on 2026-01-02 at 23:15 by Nurse Dawn Yvone Gibbs. Routine neurological observations were completed, with GCS score recorded as 14/15. Mild disorientation was noted, and pupillary response to light was slightly delayed bilaterally. No acute deterioration observed. Patient to be handed over to the medical team for admission and further neurologicaal monitoring.
Nurse Dawn Yvonne Gibbs
NMC number: 28R0973Z

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 02/01/2026 23:45

Patient
Philip Paul Cook

Age
49

Sex
Male

NHS No.
457031170

Date/Time
02/01/26 23:45

Seen By
Dr. Kareem Ahmed

Presenting Complaint
Acuteconfusion post minor fall Pt reports confusion following an unwitnessed minor afll earlier today. No LOC. No c/o of headache, nausea, or limb weakness. States he felt unsteady but denies vertigo. Unable to recall details of fall. No prior confusion or similar events. The fall occurred earlier on the same day as the ED presentation.

Past Medical History
- HTN
- Mild osteoarthritis

Medications
Nil

Allergies
Nil known

Social History
Lives alone. Independent with ADLs. No carers.

Family History
Nil significant.

Systems Review
CNS: Noh/o seizures, severe headache, or focal deficits. No recent visual changes. CVS: No CP or palpitations. Resp: No SOB or cough. GI: No N/V or abdo pain. GU: No dysuria or haematuria. MSK: Reports joint stiffness secondary to OA but no acute issues.

On Examination
Alert but disoriented to time/place. GCS 14/15 (E4V4M6). Pupils equal, reactive bilaterally, with slightly delayed reaction to light. No focal neuro deficits. Normal ton e/power/sensation bilaterally. Gait unassessed in ED due to confusion. No signs of trauma to head. No papilledema. No neck stiffness. CVS/Resp/Abdo exam unremarkable.

Observations
BP 132/84
HR 78
RR 16
Temp 36.8Â°C
SPO2 97% onn RA

Investigations
CThead: Subdural hygroma, no MLS. No acute bleed.

Test Results
FBC, U&Es, LFTs, CRP all WNL.

Impression
Subdural hygroma causing acute confusion, likely secondary to minor fall.

Referral
Accepted by Neuro Ward (Bed A01). Detailed handover provided to Dr. Kenneth Brian Lamb from the neuro team, sumarizing ED findings, including mechanism of injury, CT results, and initial management.

Plan
- IV paracetamol 1g QID for pain control.
- Monitor neuro obs closely for any signs of deterioration.
- No ABx. No surg intervention required.
- Transfer to Neuro Ward for further care and obs.


Dr. Kareem Ahmed (ED Consultant)
GMC number: 1695439

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 03/01/2026 00:15

Clerking Doctor
Dr. Kelly Nicola Hayward (SpR)

Presenting Complaint
Acute confusion following minor fall

History of Presenting Complaint
- Pt reports tripping over a loose carpet edge at home earlier in the day (02/01/26)
- No LOC reported but recalls feeling dazed afterward
- Developed pprogressive confusion over the following hours
- Unable to remember recent events clearly
- Denies headache, visual changes, N&V, or limb weakness
- No reported CP, palpitations, or SOB

Review of Systems
- CNS: Mild confusion, denies heaadche, no visual disturbances, no speech difficulti es, no limb weakness, denies seizures
- CVS: Denies chest pain, palpitations, or syncope
- Resp: No breathlessness or cough
- GIT: No abdominal pain, nausea, vomiting, or changes in bowel habit
- Renal: No dysuria or haematuria
- MSK: Reports mild right knee pain following the fall
- Endo: No polyuria, polydipsia, or heat/cold intolerance
- Other: No recent fever or weight changes

Past Medical History
- HTN
- Mild osteoarthritis

Medications
- No regular medications
- IV paracetamol 1g QID prescribed during ED stay to manage pain and prevent discomfort

Allergies
None

Social History
- Lives alone in a ground-floor flat
- Independent with activities of daily living
- Retired accountant
- Non-smoker
- Drinks alcohol occasionally, approximately 6 units per week
- No recreational drug use

Family History
- Father: Deceased, history of MI at age 67
- Motherr: Deceased, history of HTN and stroke
- No known family history of neurodegenerative or psychiatric disorders

On Examination
- Alert but mildly confused, GCS 14/15 (disoriented to time)
- Appears dehydrated with dry mucous membranes
- No obvious signs of head trauma or external injuries
- Neurological examination:
   - Cranial nerves: Intact, pupils equal and reactive to light bilaterally
  - Motor: Normal power (5/5) in all limbs
  - Sensory: No deficits detected in light touch, pinprick, or vibratkion sensation
  - Reflexes: Normal and symmetrical in all limbs, plantar reflexes downgoing bilaterally
 - Coordination: No dysmetria or intention tremor on finger-nose testing
  - Gait: Unsteady, requires assistance to walk; no gross abnormalities in stance or heel-to-toe walking
- Cardiovascular: Heart sounds dual, no murmurs, no peripheral oedema
- Respiratory: Equal air entry bilaterally, no added sounds
- Abdomen: Soft, non-tender, no organomegaly
- No meningeal signs

Observations
HR 88
BP 142/86
RR 16
Temp 36.8
SpO2 98% on room air

Investigations
- CT head (02/01/26): DSubdural hygroma noted, no MLS
- No further imaging performed or currently planned

Test Results
- FB: Normal
- U&E: Mild hyponatremia (Na 132 mmol/L)
- CRP: Normal
- LFTs: Normal
- Coagulation profile: Normal
- Blood glucose: Normal
- Pending: None

Impression
Acute confusion secondary to subdural hygroma and mild hypoNa, likely exacerbated by dehydration

Plan
- Commence IV 0.9% sodium chloride, 1L over 8 hours, to correct dehydration and mild hyponatremia
- Prescribe IV paracetamol 1g QID to mnaage pain and prevent discomfort
- Continue monitoring neurological status with GCS assessments every 4 hours
- Repeat U&E in 24 hours to assess resposne to fluid resuscitation
- Ensure adequate oral hydration once IV fluids are discontinued
- Monitor for any progression of symptoms or development of focal neurological deficits
- Liaise with neurology team for ongoing care and management
- Document any further findings during the patientâ€™s stay

Admitting Consultant
Dr. Ismel Siddique (Neurology Consultant)


Dr. Kelly Nicola Hayward (Specialty Registrar)
GMC number: 1746274

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 03/01/2026 08:30

Clinician Leading Ward Round
Dr. Ismel Siddique (Consultant)

Presenting Complaint
Acute confusion after minor fall Hx noted thank you

Issues
1. Subdural Hygroma
-CT head confirmed subdural hygroma
-No midline shift
-Mild gait instability likely related to fall

On Review
Patient reports feeling confused but denies headache or significant pain.

Investigations
CT head confirmedsubdural hygroma without midline shift. Mild hyponatraemia (Na 132 mmol/L). Patient noted to be slightly dehydrated. Sodium correction plan initiated with IV 0.9% NaCl.

Observations
HR 84
BP 132/78
RR 16
Temp 36.8
SpO2 98% on air

On Examination
PPatient alert but mildly disoriented. General appearance unremarkable. A: Patent airway, no stridor or obstruction. B: Resp effort normal, equal air entry, no added sounds. C: Warm peripheries, cap refill <2s, reg pulse. D: GCS 14/15 (E4, V4, M6); CNs intact; mild gait instability. E: No skin changes, no oedema noted.

Plan
1. Start ceftriaxone 2g IV OD for 5 days (prophylactic). 2. Refer to physio for mobility and balance assesment. 3. Continue IV 0.9% sodium chloride to manage mild hyponatraemia and dehydration. 4. Monitor hydration status and repeat U&Es in 48 hours.


Dr. Ismel Siddique (Consultant)
GMC number: 1430645

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 03/01/2026 10:00

10:00 03/01/2026. Physio assessment conducted by Judith Ada Wells for Philip Cook. Focus: post-fall mobility and balance. Guided exercises included sit-to-stand transitions, tandem walking, and balance drills. Mild unsteadiness on tandem walking was noted. Tasks were comlpleted with minimal assistance. No acute neuro signs were observed. Plan: daily physio sessions focusing on balance and gait training. Goal: improve stability and reduce fall risk.
Therapist Judith Ada Wells (Physical)

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 03/01/2026 11:30

Assessed by OT Sylvia Gwendoline Field at 11:30. Mild difficulty noted with fine motor tasks (e.g., fastening buttons). Patient managed ADLs with verbal prompts. Button hook tool recommended. Follow-up OT session scheduled to monitor progress.
Therapist Sylvia Gwendoline Field (Occupational Therapist)

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 03/01/2026 14:00

Clinician Leading Ward Round
Dr. Kelly Nicola Hayward (SpR)

Presenting Complaint
Acute confusion after minor fall

Issues
1. Subdural Hygroma
-Confirmed on CT scan with no midline shift
-Neurological status stable with no tfocal deficits
-Mild fatigue reported by the patient

Today

On Review
Patient reports mild fatigue but denies new or worsening symptoms. No headache, nausea, or vision changes.

Investigations
None

Observations
HR: 82
BP: 128/78
RR: 16
Temp: 36.7
SpO2: 98% on air

On Examination
- Alert, mildly fatigued but engaging well during review
- CN II-XII grossly intact
- No focal neurological deficits identified
-Limb power 5/5 bilaterally with normal tone and reflexes
- Gait not formally assessed during WR but no obvious instability noted

Plan
- Encourage oral fluid intake to address mild hyponatremia
- Repeat U&Es in 24 hours to monitor Na levels
- Continue prophylactic ceftriaxone 2g IV OD (day 2 of 5)
- Daily physio to focus on balance and gait training
- OT follow-upp to assess progress with fine motor tasks
- Provide button hook tool to assist with dressing as recommended by OT


Dr. Kelly Nicola Hayward (Specialty Registrar)
GMC number: 1746274

--------------------------------------------------------------------------------

Clinical Note 11
Date/Time: 03/01/2026 16:30

16:30 03/01/26. Pt seen for 2nd physio session post-adm. Focus: gait stability. Exercises: slow walking w/ Zimmer frame; emphasis on wt distribution + step coordination. Req mod assist but showed slight improvement vs 1st session. No acute neuro sx observed. Plan: cont 2x daily physio sessions to improve balance + mobility. No new meds. Therapist: Judith Ada Wels.
Therapist Judith Ada Wells (Physical)

--------------------------------------------------------------------------------

Clinical Note 12
Date/Time: 03/01/2026 18:00

Provided education on fall prevention. Discussed home safety, safe use of assistive devices, and identifying environmental hazards. No changes to treatment or meds. Theerapy sessions to continue as planned.
Nurse Dawn Yvonne Gibbs
NMC number: 28R0973Z

--------------------------------------------------------------------------------

Clinical Note 13
Date/Time: 04/01/2026 09:00

Clinician Leading Ward Round
Dr. Kelly Nicola Hayward (SpR)

Presenting Complaint
Acute confusion after minor fall

Issues
1. Subdural Hygroma
-
2. Mild Hyponatremia
-Sodium 132 mmol/L
-Decision to start sodium chloride supplementation

Today

On Review
Patient reports feling well and denies new symptoms. No confusion or new complaints noted.

Investigations
Sodium remains slightly low at 132 mmol/L. Other blood tests within normal limits.

Observations
HR: 78
BP: 128/82
RR: 16
Temp: 36.8
SpO2: 98% on air

On Examination
- Pt alert, oriented, and cooperative
- No focal neurological deficits observed
- Gait remains mildly unsteady; no acute worsening
- CVS , resp, and abdo examinations unremarkable

Plan
- Initiate oral sodium supplementation with NaCl 1 g tablets TID
- Encourage increased oral fluid intake
- Repeat blood Na levels in 24 hours to monitor progress


Dr. Kelly Nicola Hayward (Specialty Registrar)
GMC number: 1746274

--------------------------------------------------------------------------------

Clinical Note 14
Date/Time: 04/01/2026 10:30

Pt seen 10:30 for physio. Focus: lower limb strength. Ex: seated leg raides, resistance band work. Guidance given on posture to prevent strain. Pt tolerated ex well. No acute distress or neuro Sx. Goal: improve mobility in preparation for independnet mobility. Plan: progress to dynamic balance ex next session to further enhance mobility. Judith Ada Wells (PT).
Therapist Judith Ada Wells (Physical)

--------------------------------------------------------------------------------

Clinical Note 15
Date/Time: 04/01/2026 12:00

Social worker Sylvia Gwendoline Field met with the patient to discuss discharge planning. Assessed home safety and identified potential support needs. Next step: Social worker to coordinate with OT for a bhome safety visit prior to discharge.
Social Worker Sylvia Gwendoline Field

--------------------------------------------------------------------------------

Clinical Note 16
Date/Time: 04/01/2026 15:00

Patient Philip Paul Cook was seen on 2026-01-04 at 15:00 for an OT session. The focus of the session was on adaptations for ADLs. The patient practiced bed-to-chair transfers and the use of utensils to address reduced dexterity. Energy conservation techniques were demonstrated and practiced. The patient was engaged and able to follow instructions, though mild difficulty with fine mootr tasks was noted. To support independence, a long-handled reacher and adaptive cutlery will be proivded. The next session will build on the skills practiced and assess the need for home adaptations. - Sylvia Gwendoline Field (OT)
Therapist Sylvia Gwendoline Field

--------------------------------------------------------------------------------

Clinical Note 17
Date/Time: 04/01/2026 17:00

Clinician Leading Ward Round
Dr. Kelly Nicola Hayward (SpR)

Presenting Complaint
Acute confusion after minor fall

Issues
1. Subdural Hygroma
-No midline shift on CT scan
-Stable neurological status
2. Mild Hyponatremia
-Serum sodium 133 mmol/L
-Previosly noted as 132 mmol/L

Today

On Review
Patient reports mild evening headaches. No other concerns. Feeling otherwise stable.

Investigations
None

Observations
HR: 74
BP: 126/78
RR: 16
Temp: 36.7
SpO2: 97% (room air)

On Examination
- Alert and oriented. Appears comfortable at rest.
- Neurological examination: Cranial nerves II-XII intact. No motor or sensory deficits. Normal coordination and reflexes. Gait unassessed during this encounter.
- Cardiovascular examination: Dual heart sounds, no murmurs.
- Respiratory examination: Clearr breath sounds bilaterally, no added sounds.
- Abdominal examination: Soft, non-tender, no organomegaly.

Plan
- Restrict fluid intake to 1.5L per day to address hyponatremia.
- Prescribe paracetamol 1g PO PRN (maximum 4 doses per day) for headache management.
- Start oralsodium supplementation with NaCl 1g tablets TID.
- Repeat serum Na levels in 24 hours.
- Review progress in the next WR.


Dr. Kelly Nicola Hayward (Specialty Registrar)
GMC number: 1746274

--------------------------------------------------------------------------------

Clinical Note 18
Date/Time: 05/01/2026 09:30

05/01/26, 09:30. Physio session with Judith Ada Wells. Focus: balance training using balance boards and parallel bars. Session included guided weight-shifting exercises aimed at improving stability and reducing fall risk. The patient, Philip Cook, required minimal assistance and demonstratedsteady progress in maintaining postureduring dynamic movements. Plan: Next session to include more advanced balance tasks, such as single-leg stance exercises, to further improve stability.
Therapist Judith Ada Wells (Physical)

--------------------------------------------------------------------------------

Clinical Note 19
Date/Time: 05/01/2026 11:00

Clinician Leading Ward Round
Dr. Kelly Nicola Hayward (SpR)

Presenting Complaint
Acute confusion after minor fall

Issues
1. Subdural Hygroma
-Confirmed on CT scan
-No midline shift
-Mild evening headaches reported
2. Hyponatremia
-Serum sodium 133 mmol/L
-Mild imbalance likely due to overhydration
-Fluid restriction initiated

Today

On Review
Patient reports feeling more confident in mobility after physio. No new complaints.

Investigations
No new imaging or ECG conducted during thhis ward round. Serum Na 133 mmol/L

Observations
HR: 78
BP: 132/84
RR: 16
Temp: 36.8
SpO2: 97%

On Examination
- Alert and oriented
- No focal neurological deficits
- Gait slightly unsteadg but improving with physio
- Mild residual balance issues noted during tandem walking

Plan
- Implement fluid restriction to 1.5L/day to address mild hyponatremia
- Prescribe sodium chloride tablets 600 mg TID for electrolyte cprrection
- Continue physio to improve mobility and balance
- Recheck serum Na levels in 24 hours
- PRN paracetamol 1g PO (up to 4 doses/day) for mild headaches


Dr. Kelly Nicola Hayward (Specialty Registrar)
GMC number: 1746274

--------------------------------------------------------------------------------

Clinical Note 20
Date/Time: 05/01/2026 13:30

05/01/26, 13:30. OT session with Sylvia Gwendoline Field. Focus: cognitive rehabilitation post-SDH. Philip Cook engaged in memory exercises, problem-solving tasks, and attention training. Mild cognitive difficulties noted; no significant fatigue or distress. Strategies introduced for daily planning and organisatuon. Next steps: continue daily cognitive rehab sessions. Plan: progressively increase task complexity to enhance cognitive function.
Therapist Sylvia Gwendoline Field

--------------------------------------------------------------------------------

Clinical Note 21
Date/Time: 05/01/2026 16:00

16:00 - Dr. Hasan met pt's spouse (Maria Cook). Updated on pt's cond, tx progress, and therapy outcomes. Discussed d/c options incl home care + f/u plans. Tentative d/c: 09/01/26, dep on stable neuro status + completion of therapy.
Dr. Lynn Beverley Hassan (Consultant)
GMC number: 1229817


In [31]:
# ---------------------------------------------------------
# Clinician validation — Patient 10
# ---------------------------------------------------------

PILOT_PATIENT_ID = "ef943dfb-1368-44e0-a946-a0be360e1d54"

# Complete cleaned/deduplicated source record
pilot_notes = (
    notes_dedup[
        notes_dedup["person_id"].astype(str) == PILOT_PATIENT_ID
    ]
    .sort_values("creation_timestamp")
    .copy()
)

# Load the four exact frozen summaries
pilot_summaries = {}

for workflow, path in summary_files.items():
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    pilot_summaries[workflow] = (
        results[PILOT_PATIENT_ID][summary_fields[workflow]]
    )

print("Patient 10")
print("Source notes:", len(pilot_notes))
print(
    "Source words:",
    sum(len(str(x).split()) for x in pilot_notes["clean_note_text"])
)

for workflow, summary in pilot_summaries.items():
    print(f"{workflow}: {len(summary.split())} summary words")

Patient 10
Source notes: 10
Source words: 1772
direct: 471 summary words
hierarchical: 415 summary words
rag: 503 summary words
rag_verification: 490 summary words

In [32]:
# ---------------------------------------------------------
# Clinician validation — Patient 10 document content
# ---------------------------------------------------------

PILOT_PATIENT_ID = "ef943dfb-1368-44e0-a946-a0be360e1d54"

PATIENT_LABEL = "Patient 10"

# Fixed blinded mapping
blinded_summaries = {
    "A": pilot_summaries["direct"],
    "B": pilot_summaries["hierarchical"],
    "C": pilot_summaries["rag"],
    "D": pilot_summaries["rag_verification"],
}

lines = []

lines.append(PATIENT_LABEL)
lines.append("")
lines.append("SOURCE CLINICAL RECORD")
lines.append(f"Total clinical notes: {len(pilot_notes)}")
lines.append("")

# Exact source notes — unchanged
for note_number, (_, row) in enumerate(pilot_notes.iterrows(), start=1):
    lines.append(f"Clinical Note {note_number}")
    lines.append(f"Date/Time: {row['creation_timestamp']}")
    lines.append("")
    lines.append(str(row["clean_note_text"]).strip())
    lines.append("")
    lines.append("-" * 80)
    lines.append("")

# Exact frozen summaries
lines.append("GENERATED SUMMARIES")
lines.append("")

for label, summary in blinded_summaries.items():
    lines.append(f"SUMMARY {label}")
    lines.append("")
    lines.append(summary.strip())
    lines.append("")
    lines.append("-" * 140)
    lines.append("")

patient_10_content = "\n".join(lines)

print(patient_10_content)

Patient 10

SOURCE CLINICAL RECORD
Total clinical notes: 10

Clinical Note 1
Date/Time: 02/01/2026 18:15

Clerking Doctor
Dr. Risha Mandal (Consultant)

Presenting Complaint
End-stage OA of the left hip.

Procedure
Total left hip replacement.

On Examination
Patient appears well and comfortable at rest, with no signs of distress. Focused examination of the left hip reveals marked restriction in ROM with pain on flexion, internal rotation, and abduction. No erythema, swelling, or skin lesions observed over the surgical site. Neurological examination of the lower limbs demonstrates intact motor and sensory function bilaterally. Reflexes are preserved and dsymmetrical. Assessment of mobility indicates significant limitations in ambulation; patient uses a single walking stick for support. No calf tenderness or swelling noted bilaterally, and no signs suggestive of DVT. Mild hearing loss and a history of lower back pain are noted from the patient's PMH.

Observations
HR 76
BP 136/84
RR 14
Temp 36.8
SpO2 98%

Investigations
No new imaging requested. Pre-op X-ray of the left hip from 22/12/25 contirms severe degenerative changes consistent with end-stage OA. Pre-op ECG from 22/12/25 shows normal sinus rhythm.

Test Results
Pre-op blood tests conducted on 22/12/25: Hb 10.8 g/dL (mild anaemia), WCC 6.2 x10^9/L, platelets 237 x10^9/L, creatinine 75 Âµmol/L, eGFR >90 mL/min/1.73mÂ², INR 1.0. No new tests pending.

Plan
- Proceed with total left hip replacement surgery on 03/01/2026 at 08:00 as scheduled.
- Continue pre-op fasting as instructed.
- Administer pre-op prophylactic antibiotics as per protocol.
- Ensure anaesthetic team is informed and prepared for GA.
- Recheck Hb levels post-op and consider ufrther management if required.
- Post-op DVT prophylaxis as per local guidelines.


Dr. Risha Mandal (Consultant)
GMC number: 1357243

--------------------------------------------------------------------------------

Clinical Note 2
Date/Time: 03/01/2026 08:00

Surgeon
Dr. Joanna Cheryl Wright

Assistant
Dr. Chantelle Ann Clarke

Anaesthetist
Dr. Chantelle Ann Clarke

Anaesthesia Type
General anaesthesia

Procedure
Total left hip replacement

Incision
Left laeral hip

Diagnosis
End-stage OA of the left hip

Findings
Severe cartilage loss and osteophyte formation in the left hip joint. No surrounding softtissue inflammation observed.

Tissue Removed
Damaged cartilage and bone from the left hip joint

Prostheses or Implants
Total hip prosthetic implant

Closure Technique
Absorbable sutures with sterile dressing applied

Estimated Blood Loss
200 mL

Complications
None

Post-Operative Care
1. IV cefuroxime 1.5 g every 8 hours for 24 hours to minimise infection risk. 2. Initiated PCA with morphine for pain mansagement.

Plan
1. Monitr wound healing and assess for signs of infection. 2. Commence physio to aid mobilisation as per post-op protocol. 3. Patient transferred to the recovery room in stable condition.


"Dr. Joanna Cheryl Wright (Surgeon)"
GMC number: 1623645

--------------------------------------------------------------------------------

Clinical Note 3
Date/Time: 03/01/2026 10:30

Patient: Sharon Christina Campbell, 75-year-old female, post-total left hip replacement surgery under GA. Reviewed in PACU at 10:30 on 03/01/26. Care provided by anaesthetist and Nurse Fiona Penelope Powell.

AABCDE assessment:
A: Airway patent. No stridor or obstruction noted. Braething transitionef from facemask oxygen to RA without desaturation.
B: RR 16/min, SpO2 98% on RA. No signs of respiratory distress.
C: BP 132/78 mmHg, HR 76 bpm, sinus rhythm. Peripheral perfusion adequate. No active bleeding from surgical site; minimal oozing noted.
D: Drowsy but responsive to verhbal stimuli upon arrival. GCS 14/15 (E4V4M6). No focal neurological deficits observed.
E: Dressing clean and dry over left hip. No signs of erythema or haematoma.

Pain management: IV paracetamol 1g and IV morphine2mg administered as per protocol; pain controlled effectively.

Next steps: SC dalteparin 5000 units once daily to commence this evening for VTE prophylaxis. Deemed stable for transfer to Orthopaedic Ward B for continued post-operative care.
"Dr. Joanna Cheryl Wright (Surgeon)"
GMC number: 1623645

--------------------------------------------------------------------------------

Clinical Note 4
Date/Time: 03/01/2026 14:00

Clinician Leading Ward Round
Dr. Chantelle Ann Clarke (SpR)

Presenting Complaint
Post-op recovery following total left hip replacement

Issues
1. Post-operative anaemia following total left hip replacement
-Hb 105 g/L (pre-op 132 g/L)

Today

On Review
Moderate pain at the surgical sjte, well-controlled with current analgesia regimen. Feels stable otherwise.

Investigations
None

Test Results
Hb 105 g/L (pre-op 132 g/L). No other abnormalities.

Observations
HR: 84
BP: 134/78
RR: 16
Temp: 36.8
SpO2: 98% RA

On Examination
Alert, NAD. Wound clean, dry, no erythema. No swelling or d/c around site. No signs of infection.

Plan
1. Start ferrous sulfate 200 mg BD for anaemia. . Physio to assist mobilisation today. 3. Review Hb and clinical status tomorrow.


Dr. Chantelle Ann Clarke (Specialty Registrar)
GMC number: 1402114

--------------------------------------------------------------------------------

Clinical Note 5
Date/Time: 04/01/2026 09:00

Clinician Leading Ward Round
Dr. Chantelle Ann Clarke (SpR)

Presenting Complaint
End-stage left hip OA, post total leeft hip replacement

Issues
1. Post-op anaemia
-Hb 10.5 g/dL
-Pre-op Hb 12.8 g/dL
-No clinical signs of significant anaemia

Today

On Review
Pt reports mild pain, maangeable on current regime. Feels well otherwise.

Investigations


Test Results
Hb 10.5 g/dL. Pending repeat Hb check in 48 hrs.

Observations
HR: 82
BP: 138/78
RR: 16
Temp: 36.8
SpO2: 98% RA

On Examination
Alert, NAD. Wound clean, dry, no erythema/swelling. Mobilising well with physio support. No clinical signs of significant anaemia.

Plan
1. Continue ferrous sulfate 200 mg TDS. 2. Progress to full weight-bearjing ambulation with physio. 3. Review Hb in 48 hrs.


Dr. Chantelle Ann Clarke (Specialty Registrar)
GMC number: 1402114

--------------------------------------------------------------------------------

Clinical Note 6
Date/Time: 05/01/2026 08:30

Clinician Leading Ward Round
Dr. Chantelle Ann Clarke (SpR)

Presenting Complaint
End-stage OA L hip

Issues
1. Post-THR recovery
-Wound site healing well with no signs of infection
-Pain adequately controlled with oral paracetamol and ibuprofen
-Mild postoperative anaemkia (Hb 108 g/L) stable, no intervention needed

Today

On Review
Feeling better. Pain controlled with oral paracetamol and ibuprofen. Mobilising short distances.

Investigations
None

Test Results
Hb 108 g/L. No intervention needed.

Observations
HR: 84
BP: 132/78
RR: 16
Temp: 36.8
SpO2: 98%on RA

On Examination
Alert, comfortable. Wound site clean, dry, no erythema/swelling. No calf tenderness. Mobilising with zimmer frame.

Plan
1. Stop enoxaparin on discharge. 2. Start aspirin 75 mg daily for VTE prophylaxis. 3. Physio to review today and emphasize the importance of continued physio and aeherence to a home exercise program. 4. Discharge planned for tomorrow.


Dr. Chantelle Ann Clarke (Specialty Registrar)
GMC number: 1402114

--------------------------------------------------------------------------------

Clinical Note 7
Date/Time: 22/12/2025 10:00

Pre-clerking Doctor
Dr. Rodney Leslie Kay (FY1)

Presenting Complaint
Pain and stiffness in L bip due to end-stage OA

Procedure
Total left hip replacement

History of Presenting Complaint
Site: L hip Onset: Gradual over last 3-4 yrs Character: Persistent ache, worsening with activity Radiates: No Axssociations: Occasional night pain, limping Timing: Daily, worse in PM Exacerbating factors: Walking, climbing stairs Severity: 8/10 at worst

Past Medical History
- HTN
- Mild hearing loss
- Cataract surgery
- History of lower back pain

Medications
Ferrous sulfate 200 mg BD (recently prescribed for anaemia)

Allergies
NKDA

Social History
- 75- year-old retired teacher living alone, independent with ADLs
- Uses stick for walking
- No smoking or alcohol use
- Limited mobility due to hip pain
- Advised to remain active within limits and ensure hydration pre-op

Family History
Non-contributory

On Examination
Alert, NAD MSK: L hip â†“ ROM (flexion 0-90Â°, ext limited), pain on int rot. No swelling/redness Neuro: LLs intact, norm sensation & motor Spine: Mild tenderness L4-L5, no deformity Cardio: HS I+II+0, no murmrs Resp: Clear BS, no added sounds Abdo: Soft, non-tender, no masses/organomegaly

Observations
HR 76
BP 138/82
RR 16
Temp 36.8
SpO2 98%

Investigations
ECG: SR, no acute ischaemic changes FBC: Hb 10.8, WCC 6.2, Plt 210 U&E: Cr 78, eGFR 65, Na 138, K 4.2 Coag: INR 1.1, APTT norm Pending: G&S

Plan
1. Start ferrous sulfate 200 mg BD for anaemia 2. Ensure G&S completed 3. Anaesthetic review for HTN and anaemia post-consultation 4. Encourage mobility, hydration pre-op 5. Proceed with surgery as planned on 02/01/26


"Dr. Rodney Leslie Kay (Foundation Trainee)"
GMC number: 1596940

--------------------------------------------------------------------------------

Clinical Note 8
Date/Time: 22/12/2025 11:30

Sharon Christina Campbell, 75F, planned L THR for end-stage OA. Seen 22/12/25 at 11:30. Anaesthetic assessment performed by Dr. Chantelle Ann Clarke (SpR).

Airway: Mallampati I, good neck mobility, no hx of difficult intubation. Mouth opening adeqate. Dentition intact.

PMHx: HTN, mild hearing loss, cataract surgery (2018), hx lower back pain. No known allergies. Pre-op labs: Hb 10.8 g/dL (mild anaemia, on ferrous sulfate). ECG NAD.

Cardiopulm: Exercise tolerance god. No SOB, CP, or recent exacerbations. BP well controlled.

Plan: GA appropriate. Discussed induction, maintenance, and recovery process. Risks incl PONV, sore throat, and DVT explained. Addressd pt questions and concerns about potential side effects. Pt consented. No new meds prescribed.

Optimisation: Continue ferrous sulfate. Adequate hydration pre-op. No further anaesthetic concerns.
"Dr. Chantelle Ann Clarke (Specialty Registrar)"
GMC number: 1642995

--------------------------------------------------------------------------------

Clinical Note 9
Date/Time: 22/12/2025 13:00

Patient: Sharon Christina Campbel (DOB: 15/03/48, NHS No: 440395845) was seen on 22/12/25 at 13:00 for pre-op consent for scheduled total left hip replacement on 03/01/26. Discussion led by Dr. Joanna Cheryl Wright (Surgeon).

Procedure details explained, including steps involved, expected outcomes, and post-op recovetry process. Surgery planned for management of end-stage OA. Risks discussed: infection, DVT, PE, implant dislocation, and anaesthetic risks. Potential benefits: improved mobility and pain reduction. Alternatives reviewed: physiotherapy and pharmacological pain management. Patient's questions addressred, including recovery time and functional outcomes post-surgery.

Patient provided informed consent after all concerns were clarified. Consent documented in medical records.

ABCDE examination:
A: Airway patent, no concerns raised.
B: RR within normal limits, nosigns of respiratory distress.
C: BP stable (previously managed HTN), HR regular. No oedema or chest pain reported.
D: Alert, orientated, GCS 15. No neurological deficits noted.
E: No rashes, wounds, or signs of infection. Skin intact around surgical site.

Additional notes: Patient previously noted to have mild anemia (Hb: 10.8 /dL) during the pre-op assexsment earlier the same day. Oral ferrous sulfate 200 mg twicedaily was initiated as part of pre-op management.

Plan: Proceed with pre-op checklist and preparation for surgery as scheduled.
"Dr. Joanna Cheryl Wright (Surgeon)"
GMC number: 1623645

--------------------------------------------------------------------------------

Clinical Note 10
Date/Time: 22/12/2025 14:00

Patient: Sharon Christina Campbell. DOB: 15/03/48. NHS No: 440395845. MRN: 773566781. Scheduled procedure: Total left hip replacement for end-stage OA. Admitting consultant: Dr. Risha Mandal. Ward: Orthopae dic Ward B. Bed: A03.

Checklist completed on 22/12/25 at 14:00 by Nurse Eleanor Judith Davis. Blood tests reviwwed. FBC, renal function, and coagulation profile completed. Mild anaemia (Hb: 10.8 g/dL) noted during prior pre-operative assessmenr on the same day, and patient was commenced on oral ferrous sulfate 200 mg BD as per prior plan. ECG reviewed, no abnormalities. No allergies or contraindications reported.

Consent form signed and documented by Dr. Joanna Cheryl Wright on 22/12/25. Patient informed of risks (e.g., infection, blood clots, implant dislocation), benefits (e.g., improved mobility, pain relief), and alternatives (e.g., physiotherapy, pain management strategies). Questions addressed, including recovery time and post-operative mobility . Consent valid and confirmed.

Pre-surgical fasting instructions reviewed with the patient. Patient instructed to adhere strictly. No new medications prescribed at this event. Patient fit for surgery. Past medical history includes HTN, mild hearing loss, cataract surgery (2018), and a history of lower back pain. No issues identified.
"Nurse Eleanor Judith Davis"
NMC number: 86L4310D

--------------------------------------------------------------------------------

GENERATED SUMMARIES

SUMMARY A

Sharon Christina Campbell, 75-year-old woman with end-stage left hip osteoarthritis, hypertension, mild hearing loss, previous cataract surgery, and chronic lower back pain, had a 3–4 year history of progressive left hip pain, stiffness, restricted mobility, and use of a walking stick. She was independent with activities of daily living, lived alone, and had no known drug allergies.

**22/12/2025 – Pre-operative assessment:**
Examination showed marked restriction and pain of left hip movement, without skin changes or neurovascular deficit. ECG showed normal sinus rhythm. Pre-operative investigations documented mild anaemia (Hb 10.8 g/dL), normal WCC and platelets, creatinine 75–78 µmol/L, eGFR reported as >90 and 65 mL/min/1.73 m² in separate results, and INR 1.0–1.1. Pre-operative radiograph confirmed severe degenerative changes consistent with end-stage osteoarthritis. Anaesthetic assessment found no airway or cardiopulmonary concerns, and general anaesthesia was considered appropriate. Oral ferrous sulfate 200 mg twice daily was commenced, hydration and mobility were encouraged, and informed consent was obtained after discussion of surgical risks, benefits, and alternatives. Surgery was scheduled for early January 2026.

**03/01/2026 – Surgery:**
A total left hip replacement was performed under general anaesthesia by Dr Joanna Cheryl Wright, with Dr Chantelle Ann Clarke as assistant/anaesthetist. Findings included severe cartilage loss and osteophyte formation without surrounding soft-tissue inflammation. Damaged cartilage and bone were removed and a total hip prosthesis implanted. The wound was closed with absorbable sutures and a sterile dressing. Estimated blood loss was 200 mL, with no complications. Post-operatively, IV cefuroxime was prescribed for 24 hours and morphine PCA was commenced.

**03/01/2026 – PACU review:**
The patient was drowsy but responsive, with GCS 14/15, patent airway, stable cardiovascular observations, and oxygen saturation 98% on room air after weaning from facemask oxygen. The dressing was clean and dry with minimal oozing and no haematoma. Pain was controlled with IV paracetamol and morphine. Dalteparin 5000 units subcutaneously daily was planned for VTE prophylaxis, and she was transferred in stable condition to the orthopaedic ward.

**Post-operative ward course:**
She developed mild postoperative anaemia, with haemoglobin documented as 105 g/L compared with a stated pre-operative value of 132 g/L, and subsequently 10.5 g/dL compared with 12.8 g/dL. She had no clinical signs of significant anaemia and was treated with oral ferrous sulfate, documented as 200 mg twice daily and later three times daily. Pain remained mild to moderate and controlled with analgesia. The wound remained clean and dry without erythema, swelling, discharge, or infection. Physiotherapy supported mobilisation, progressing to weight-bearing ambulation with a Zimmer frame.

At the latest review, haemoglobin was stable at 108 g/L and no further intervention was required. She was mobilising short distances, had no calf tenderness, and remained clinically stable. Enoxaparin was planned to stop at discharge, with aspirin 75 mg daily for VTE prophylaxis. Continued physiotherapy and a home exercise programme were advised, with discharge planned for the following day.

--------------------------------------------------------------------------------------------------------------------------------------------

SUMMARY B

- **Preoperative course (December 2025):** A 75-year-old woman had 3–4 years of progressive left hip pain and stiffness from end-stage osteoarthritis, with activity-related pain up to 8/10, occasional night pain, limping, markedly restricted range of motion, and ambulation limited to a single stick. Examination showed painful restriction of left hip movement without swelling or erythema; lower-limb neurology was intact and there were no clinical signs of DVT. Radiographs on 22/12/2025 confirmed severe degenerative changes.
- Her history included well-controlled hypertension, mild hearing loss, cataract surgery in 2018, and lower back pain. Preoperative ECG showed sinus rhythm without acute changes. Blood tests demonstrated mild anaemia (Hb 10.8 g/dL), with otherwise documented acceptable blood counts, renal function, and coagulation results. Ferrous sulfate 200 mg twice daily was started. Anaesthetic assessment found no airway concerns, good exercise tolerance, and suitability for general anaesthesia. Risks, benefits, alternatives, and postoperative expectations were discussed, and informed consent was documented.
- **03/01/2026:** Under general anaesthesia, Dr Joanna Cheryl Wright performed a total left hip replacement for end-stage osteoarthritis. Severe cartilage loss and osteophyte formation were found without surrounding soft-tissue inflammation. The damaged cartilage and bone were removed and a total hip prosthesis implanted. The wound was closed with absorbable sutures and a sterile dressing. Estimated blood loss was 200 mL, with no operative complications.
- **Immediate postoperative period:** In PACU, she was drowsy but responsive, with a patent airway and stable observations; she transitioned to room air without desaturation. The dressing was clean and dry with minimal oozing and no erythema or haematoma. Pain was controlled with IV paracetamol and morphine. She was transferred in stable condition to the orthopaedic ward. IV cefuroxime was prescribed for 24 hours, morphine PCA was initiated, and dalteparin 5000 units subcutaneously daily was planned for VTE prophylaxis.
- **Postoperative progression:** She remained clinically stable with mild-to-moderate, manageable pain and consistently clean, dry wound findings without infection or swelling. Postoperative haemoglobin decreased to approximately 10.5–10.8 g/dL (reported as 105–108 g/L) without clinical signs requiring intervention; ferrous sulfate was continued, documented as 200 mg twice daily initially and later three times daily. Physiotherapy supported mobilisation, progressing from assisted mobilisation to short-distance walking with a Zimmer frame and planned full weight-bearing ambulation.
- Pain subsequently became controlled with oral paracetamol and ibuprofen. There was no calf tenderness. Physiotherapy review and reinforcement of home exercises were planned. Enoxaparin was to be stopped at discharge and aspirin 75 mg daily commenced for VTE prophylaxis, with discharge planned for the following day.


In [ ]:
| Patient | Source notes | Source words | Direct words | Hierarchical words | RAG words | RAG+V words |
| ------- | -----------: | -----------: | -----------: | -----------------: | --------: | ----------: |
| 01      |           15 |        1,903 |            — |                  — |         — |           — |
| 02      |           23 |        2,958 |          582 |                484 |       477 |         458 |
| 03      |           22 |        3,436 |          418 |                512 |       326 |         326 |
| 04      |           34 |        3,867 |          453 |                496 |       467 |         467 |
| 05      |           36 |        3,991 |          385 |                415 |       351 |         351 |
| 06      |           26 |        4,287 |          584 |                597 |       414 |         408 |
| 07      |           45 |        5,134 |          448 |                468 |       336 |         317 |
| 08      |           35 |        5,525 |          482 |                531 |       490 |         488 |
| 09      |           37 |        4,278 |          404 |                580 |       406 |         394 |
| 10      |           10 |        1,772 |          471 |                415 |       503 |         490 |