In [29]:
import os

# Find where you are right now
print("Current directory:", os.getcwd())

# List everything in current folder
print("\nFiles here:")
for item in os.listdir('.'):
    print(item)

Current directory: /Users/pallavi_chandanshive/projects/clinical-summarization-eval/notebooks

Files here:
01_data_exploration.ipynb
02_workflow_1_direct_generation.ipynb
.ipynb_checkpoints

In [30]:
# Search for CSV files anywhere in your project
for root, dirs, files in os.walk('.'):
    # Skip venv folder
    if 'venv' in root:
        continue
    for file in files:
        if file.endswith('.csv'):
            print(os.path.join(root, file))

In [31]:
import pandas as pd

# Update these paths to match where your files are
notes = pd.read_csv('../data/raw/clinical_notes.csv')
patients = pd.read_csv('../data/raw/patients.csv')
admissions = pd.read_csv('../data/raw/admissions.csv')

In [32]:
# Basic shape
print("=== NOTES ===")
print(notes.shape)
print(notes.columns.tolist())
print(notes.head(2))

print("\n=== PATIENTS ===")
print(patients.shape)
print(patients.columns.tolist())

print("\n=== ADMISSIONS ===")
print(admissions.shape)
print(admissions.columns.tolist())

=== NOTES ===
(1602, 9)
['ingest_timestamp', 'clinical_note_id', 'clean_note_text', 'creation_timestamp', 'updt_dt_tm', 'note_subject', 'note_type', 'admission_id', 'person_id']
   ingest_timestamp                      clinical_note_id  \
0  07/01/2026 14:35  17bf845b-88f8-4604-8983-6e74453aada5
1  07/01/2026 14:50  e5d9c0a4-299a-425e-abbc-27fabe9cb742

                                     clean_note_text creation_timestamp  \
0  Patient Name: Judith Ada Wells\n- Patient ID: ...   07/01/2026 14:05
1  Patient reviewed at 14:20 on 07/01/26 by Nurse...   07/01/2026 14:20

         updt_dt_tm         note_subject note_type  \
0  07/01/2026 14:35            ED Triage        ED
1  07/01/2026 14:50  ED Triage Follow-Up        ED

                           admission_id                             person_id
0  63720303-3c1b-4356-befd-eea5438da62e  28570119-9cdc-4120-98c0-4edb76cf36a3
1  63720303-3c1b-4356-befd-eea5438da62e  28570119-9cdc-4120-98c0-4edb76cf36a3

=== PATIENTS ===
(69, 6)
['age', 'date_of_birth', 'full_name', 'gender_identity', 'nhs_number', 'person_id']

=== ADMISSIONS ===
(69, 15)
['admission_id', 'admission_method', 'admission_timestamp', 'admission_title', 'bed_location', 'date_of_birth', 'nhs_number', 'patient_id', 'patient_name', 'site_id', 'site_name', 'ward', 'full_name', 'first_name', 'surname']

In [33]:
print("\n=== NOTE TYPES ===")
print(notes['note_type'].value_counts())

=== NOTE TYPES ===
note_type
Orthopaedics Inpatients                      263
Physiotherapy Documentation                  262
Medicine Inpatients                          242
ED                                           155
Neurology Inpatients                         104
Therapies Inpatients                          81
Paediatrics Inpatients                        66
Anaesthetic Documentation                     62
Respiratory Inpatients                        62
ED Depart Summary                             39
Respiratory Medicine Inpatients               37
Pre-op Checklist                              35
Pre-op Consent                                31
Theatre notes                                 31
Neurosurgery Inpatients                       26
Orthopaedics Outpatients                      24
Occupational Therapy Documentation            24
Surgery Inpatients                            21
Dietetics Documentation                       14
Speech and Language Therapy Documentation      8
Surgery Outpatients                            6
Respiratory Therapy Documentation              2
Cardiology Inpatients                          2
Paediatric Respiratory Inpatients              2
Pediatrics Inpatients                          2
General Medicine Inpatients                    1
Name: count, dtype: int64

In [34]:
# How many notes per admission?
notes_per_admission = notes.groupby('admission_id')['clinical_note_id'].count()
print("\n=== NOTES PER ADMISSION ===")
print(notes_per_admission.describe())
print(notes_per_admission.value_counts().head(10))

# How many admissions per patient?
admissions_per_patient = admissions.groupby('patient_id')['admission_id'].count()
print("\n=== ADMISSIONS PER PATIENT ===")
print(admissions_per_patient.describe())
print(admissions_per_patient.value_counts().head(10))

=== NOTES PER ADMISSION ===
count    69.000000
mean     23.217391
std       8.709139
min      10.000000
25%      16.000000
50%      22.000000
75%      30.000000
max      45.000000
Name: clinical_note_id, dtype: float64
clinical_note_id
22    5
25    5
33    4
17    4
23    4
19    4
35    4
15    4
12    3
26    3
Name: count, dtype: int64

=== ADMISSIONS PER PATIENT ===
count    50.000000
mean      1.380000
std       0.490314
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       2.000000
Name: admission_id, dtype: float64
admission_id
1    31
2    19
Name: count, dtype: int64

In [35]:
# Pick first patient and show all their notes in order
first_patient = notes['person_id'].iloc[0]
patient_notes = notes[notes['person_id'] == first_patient].sort_values('creation_timestamp')

print(f"\n=== FULL JOURNEY FOR PATIENT {first_patient} ===")
for _, row in patient_notes.iterrows():
    print(f"\nDate: {row['creation_timestamp']}")
    print(f"Type: {row['note_type']}")
    print(f"Text preview: {str(row['clean_note_text'])[:200]}")
    print("---")

=== FULL JOURNEY FOR PATIENT 28570119-9cdc-4120-98c0-4edb76cf36a3 ===

Date: 07/01/2026 14:05
Type: ED
Text preview: Patient Name: Judith Ada Wells
- Patient ID: 28570119-9cdc-4120-98c0-4edb76cf36a3
- NHS Number: 272733208
- Date of Birth: 15/05/84 (39 years old)
- Gender: Female
- Allergies: NKA
- Current Medicatio
---

Date: 07/01/2026 14:20
Type: ED
Text preview: Patient reviewed at 14:20 on 07/01/26 by Nurse Chukwuebuka Okafor. Patient presented with a severe headache rated 8/10 in intensity. BP measured at 160/90 mmHg. HR recorded at 88 bpm. Brief neurologic
---

Date: 07/01/2026 14:45
Type: ED
Text preview: - Patient: Judith Ad a Wells, 39-year-old female, DOB: 15/05/84, NHS Number: 272733208.
 - Date/Time: 07/01/26, 14:45.
 - Staff involved: Nurse Jasmine Freda Murray.
 - Chief Complaint: Severe headach
---

Date: 07/01/2026 15:15
Type: ED
Text preview: Patient: Judith Ada Wells, 39-yer-old female, presenting with severe headache rated 8/10 in intensity after exertion. Current triage category: Category 2 (Urgent - potentially serious condition requir
---

Date: 07/01/2026 16:30
Type: ED Depart Summary
Text preview: Patient
Judith Ada Wells

Age
39

Sex
Female

NHS No.
272733208

Date/Time
07/01/26 16:30

Seen By
Dr. Victoria Ellen Holmes (with Dr. Rebecca Stephanie Norris, ED Consultant)

Presenting Complaint
Se
---

Date: 07/01/2026 17:00
Type: Neurology Inpatients
Text preview: Clerking Doctor
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

History of Presenting Complaint
Site: Generalised headache Onset: Sudden, described as 'thun
---

Date: 07/01/2026 18:30
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Kevin Richard Martin (Consultant), accompanied by Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

History of Presenting Com
---

Date: 07/01/2026 20:00
Type: Neurology Inpatients
Text preview: - Contacted patient's GP, Dr. Ethel Joanne Duffy, at 20:00 on 07/21/26.
- Provided update on admission and preliminary diagnosis of RCVS.
- No immediate changes to treatment plan following communicati
---

Date: 08/01/2026 10:00
Type: Medicine Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Confirmed by MR
---

Date: 08/01/2026 16:00
Type: Neurology Inpatients
Text preview: - Provided patient with educational materials on RCVS.
- Emphasised importance of avoiding triggers including intense physical exertion, stress, and medications such as triptans or ergotamines.
- Addr
---

Date: 09/01/2026 10:30
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Mild hyponatrem
---

Date: 09/01/2026 15:00
Type: Neurology Inpatients
Text preview: - Rehab team completed initial assessment of physical mobility and strength. - Mild residual neck stiffness noted; no significant functional impairments. - Decision made to arrange outpatient lhysio p
---

Date: 10/01/2026 09:15
Type: Medicine Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Diagnosis confi
---

Date: 10/01/2026 17:45
Type: Neurology Inpatients
Text preview: - Provided patient with discharge planning booklet covering RCVS management. - Reviewed booklet contents with the patient, including lifestyle modifications, warning signs, and follow-up card. - Patie
---

Date: 11/01/2026 08:45
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR), Dr. Glenn Robert Cartwright (Cons)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstrict
---

Date: 11/01/2026 10:30
Type: Neurology Inpatients
Text preview: - Repeat MRA performed at 10:30 on 11/01/26. Significant improvdment in cerebral vasoconstriction observed.
- Diagnosis of RCVS confirmed.
- Decision made to proceed with discharge planning on 12/01
---

Date: 12/01/2026 09:00
Type: Neurology Inpatients
Text preview: Clinician Leading Ward Round
Dr. Barbara Beatrice Williamson (SpR)

Presenting Complaint
Severe headache after exertion

Issues
1. Reversible Cerebral Vasoconstriction Syndrome (RCVS)
-Confirmed diagn
---

Date: 12/01/2026 12:00
Type: Neurology Inpatients
Text preview: - GP, Dr. Ethel Joanne Duffy, contacted by Nurse Jasmine Freda Murray on 12/01/26 at 12:00.
- Summary of patientâ€™s hospit al stay provided, including diagnosis of RCVS.
- Discharge medication (amlod
---

Date: 12/01/2026 13:30
Type: Medicine Inpatients
Text preview: - Contacted patient's GP, Dr. Ethel Joanne Duffy, to provide an update on discharge.
- OP follow-up arranged for 4 weeks.
- No changes to meds or treatment plan made during this event.
Nurse Jasmine
---

In [36]:
# Check duration of admissions
notes['creation_timestamp'] = pd.to_datetime(
    notes['creation_timestamp'], 
    format='%d/%m/%Y %H:%M',
    dayfirst=True
)

date_range = notes.groupby('admission_id')['creation_timestamp'].agg(['min', 'max'])
date_range['duration_days'] = (date_range['max'] - date_range['min']).dt.days

print("=== ADMISSION DURATION ===")
print(date_range['duration_days'].describe())

# Check patients with 2 admissions
admissions_per_patient = admissions.groupby('patient_id')['admission_id'].count()
two_admission_patients = admissions_per_patient[admissions_per_patient == 2].index.tolist()
print(f"\nPatients with 2 admissions: {len(two_admission_patients)}")

# Check note types for multi-admission patients
multi_notes = notes[notes['person_id'].isin(two_admission_patients)]
print(f"Total notes for multi-admission patients: {len(multi_notes)}")

# Find discharge summary note type
print("\n=== DISCHARGE SUMMARY NOTES ===")
discharge_notes = notes[notes['note_type'].str.contains('Depart|Discharge|Summary', 
                                                          case=False, na=False)]
print(f"Count: {len(discharge_notes)}")
print(discharge_notes['note_type'].value_counts())

=== ADMISSION DURATION ===
count    69.000000
mean      8.869565
std       6.216470
min       0.000000
25%       4.000000
50%       7.000000
75%      15.000000
max      20.000000
Name: duration_days, dtype: float64

Patients with 2 admissions: 19
Total notes for multi-admission patients: 988

=== DISCHARGE SUMMARY NOTES ===
Count: 39
note_type
ED Depart Summary    39
Name: count, dtype: int64

In [37]:
# First confirm column names in both tables
print("Notes columns:", notes.columns.tolist())
print("Admissions columns:", admissions.columns.tolist())

# Check if person_id and patient_id contain same values
print("\nSample person_id from notes:", notes['person_id'].iloc[0])
print("Sample patient_id from admissions:", admissions['patient_id'].iloc[0])

Notes columns: ['ingest_timestamp', 'clinical_note_id', 'clean_note_text', 'creation_timestamp', 'updt_dt_tm', 'note_subject', 'note_type', 'admission_id', 'person_id']
Admissions columns: ['admission_id', 'admission_method', 'admission_timestamp', 'admission_title', 'bed_location', 'date_of_birth', 'nhs_number', 'patient_id', 'patient_name', 'site_id', 'site_name', 'ward', 'full_name', 'first_name', 'surname']

Sample person_id from notes: 28570119-9cdc-4120-98c0-4edb76cf36a3
Sample patient_id from admissions: 28570119-9cdc-4120-98c0-4edb76cf36a3

In [38]:
import pandas as pd

admissions_per_patient = admissions.groupby('patient_id')['admission_id'].count()
two_admission_patients = admissions_per_patient[admissions_per_patient >= 2].index.tolist()
print(f"Patients with 2 admissions: {len(two_admission_patients)}")

Patients with 2 admissions: 19

In [39]:
multi_admission_with_gt = notes[
    (notes['person_id'].isin(two_admission_patients)) & 
    (notes['note_type'] == 'ED Depart Summary')
].groupby('person_id')['admission_id'].nunique()

both_admissions_have_gt = multi_admission_with_gt[
    multi_admission_with_gt == 2
].index.tolist()

print(f"Patients with ground truth for both admissions: {len(both_admissions_have_gt)}")

Patients with ground truth for both admissions: 10

In [40]:
# How many admissions do these 10 patients have total?
print(admissions[admissions['patient_id'].isin(both_admissions_have_gt)].groupby('patient_id')['admission_id'].count())

patient_id
04df53ea-55c1-48d9-84a1-1f15c133b29b    2
137b8481-4f1d-4b7f-babd-20f7117023ad    2
359014a1-10e6-4bd8-9ba7-513d021c971e    2
5e434d78-b2f6-4d88-b327-fff6ee50b901    2
61699d6d-904a-4ece-9026-cd61b3fd9a50    2
69bf7e25-abb2-4dde-857f-f1138d4d0d8a    2
8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc    2
c50e236f-6b3d-41c8-9e16-7ec343cac820    2
c6c45c39-cd73-49dd-818d-0a7865fe8a7f    2
ff8c4724-b7de-4189-bccf-cffddd4d6d44    2
Name: admission_id, dtype: int64

In [41]:
import json

with open('../data/patients/longitudinal_patient_ids.json', 'w') as f:
    json.dump(both_admissions_have_gt, f)

print(f"Saved {len(both_admissions_have_gt)} patient IDs")

Saved 10 patient IDs

In [42]:
# Basic counts from the notes table
print("Number of notes:", len(notes))
print("Number of patients:", notes["person_id"].nunique())
print("Number of admissions:", notes["admission_id"].nunique())

# Check whether each patient has one or multiple admissions
admissions_per_patient = (
    notes.groupby("person_id")["admission_id"]
    .nunique()
)

print("\nAdmissions per patient:")
print(admissions_per_patient.describe())

print("\nPatients with more than one admission:")
print((admissions_per_patient > 1).sum())


# Calculate approximate note length in words
notes["word_count"] = (
    notes["clean_note_text"]
    .fillna("")
    .str.split()
    .str.len()
)

print("\nNote length statistics:")
print(
    notes["word_count"].describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

Number of notes: 1602
Number of patients: 50
Number of admissions: 69

Admissions per patient:
count    50.000000
mean      1.380000
std       0.490314
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       2.000000
Name: admission_id, dtype: float64

Patients with more than one admission:
19

Note length statistics:
count    1602.000000
mean      129.997503
std        83.061291
min         1.000000
25%        60.250000
50%       124.500000
75%       174.000000
90%       228.900000
95%       280.000000
max       561.000000
Name: word_count, dtype: float64

In [43]:
notes_per_admission = (
    notes.groupby("admission_id")
    .size()
)

print("\nNotes per admission:")
print(
    notes_per_admission.describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

Notes per admission:
count    69.000000
mean     23.217391
std       8.709139
min      10.000000
25%      16.000000
50%      22.000000
75%      30.000000
90%      35.000000
95%      36.000000
max      45.000000
dtype: float64

In [44]:
longest_notes = notes.nlargest(10, "word_count")

for _, row in longest_notes.iterrows():
    print("=" * 80)
    print("Words:", row["word_count"])
    print("Subject:", row["note_subject"])
    print("Type:", row["note_type"])
    print()
    print(row["clean_note_text"])
    print()

================================================================================
Words: 561
Subject: Medical Clerking
Type: Neurology Inpatients

Clerking Doctor
Dr. Kelly Nicola Hayward (SpR)

Presenting Complaint
Acute confusion following minor fall

History of Presenting Complaint
- Pt reports tripping over a loose carpet edge at home earlier in the day (02/01/26)
- No LOC reported but recalls feeling dazed afterward
- Developed pprogressive confusion over the following hours
- Unable to remember recent events clearly
- Denies headache, visual changes, N&V, or limb weakness
- No reported CP, palpitations, or SOB

Review of Systems
- CNS: Mild confusion, denies heaadche, no visual disturbances, no speech difficulti es, no limb weakness, denies seizures
- CVS: Denies chest pain, palpitations, or syncope
- Resp: No breathlessness or cough
- GIT: No abdominal pain, nausea, vomiting, or changes in bowel habit
- Renal: No dysuria or haematuria
- MSK: Reports mild right knee pain following the fall
- Endo: No polyuria, polydipsia, or heat/cold intolerance
- Other: No recent fever or weight changes

Past Medical History
- HTN
- Mild osteoarthritis

Medications
- No regular medications
- IV paracetamol 1g QID prescribed during ED stay to manage pain and prevent discomfort

Allergies
None

Social History
- Lives alone in a ground-floor flat
- Independent with activities of daily living
- Retired accountant
- Non-smoker
- Drinks alcohol occasionally, approximately 6 units per week
- No recreational drug use

Family History
- Father: Deceased, history of MI at age 67
- Motherr: Deceased, history of HTN and stroke
- No known family history of neurodegenerative or psychiatric disorders

On Examination
- Alert but mildly confused, GCS 14/15 (disoriented to time)
- Appears dehydrated with dry mucous membranes
- No obvious signs of head trauma or external injuries
- Neurological examination:
   - Cranial nerves: Intact, pupils equal and reactive to light bilaterally
  - Motor: Normal power (5/5) in all limbs
  - Sensory: No deficits detected in light touch, pinprick, or vibratkion sensation
  - Reflexes: Normal and symmetrical in all limbs, plantar reflexes downgoing bilaterally
 - Coordination: No dysmetria or intention tremor on finger-nose testing
  - Gait: Unsteady, requires assistance to walk; no gross abnormalities in stance or heel-to-toe walking
- Cardiovascular: Heart sounds dual, no murmurs, no peripheral oedema
- Respiratory: Equal air entry bilaterally, no added sounds
- Abdomen: Soft, non-tender, no organomegaly
- No meningeal signs

Observations
HR 88
BP 142/86
RR 16
Temp 36.8
SpO2 98% on room air

Investigations
- CT head (02/01/26): DSubdural hygroma noted, no MLS
- No further imaging performed or currently planned

Test Results
- FB: Normal
- U&E: Mild hyponatremia (Na 132 mmol/L)
- CRP: Normal
- LFTs: Normal
- Coagulation profile: Normal
- Blood glucose: Normal
- Pending: None

Impression
Acute confusion secondary to subdural hygroma and mild hypoNa, likely exacerbated by dehydration

Plan
- Commence IV 0.9% sodium chloride, 1L over 8 hours, to correct dehydration and mild hyponatremia
- Prescribe IV paracetamol 1g QID to mnaage pain and prevent discomfort
- Continue monitoring neurological status with GCS assessments every 4 hours
- Repeat U&E in 24 hours to assess resposne to fluid resuscitation
- Ensure adequate oral hydration once IV fluids are discontinued
- Monitor for any progression of symptoms or development of focal neurological deficits
- Liaise with neurology team for ongoing care and management
- Document any further findings during the patientâ€™s stay

Admitting Consultant
Dr. Ismel Siddique (Neurology Consultant)


Dr. Kelly Nicola Hayward (Specialty Registrar)
GMC number: 1746274

================================================================================
Words: 537
Subject: Medical Clerking
Type: Medicine Inpatients

Clerking Doctor
Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion following minor fall.

History of Presenting Complaint
- Pt reports tripping over a loose rug at home yesterday evening (05/01/26) with a minor fall onto carpeted flooring, no LOC reported. - Initially felt wel but developed confusion later in the evening, described as difficulty recognising familiar objects and people. - No recol lection of the events leading to confusion. - Denies any vertigo, N&V, or CP. - Reports a mild R-sided headache that started after the fall, described as dull and persistent, rated 3/10 in severity, not worsening over time. - No limb weakness, visual disturbances, or incontinence reported.

Review of Systems
- CNS: Mild confusion, no focal neurological deficits, no seizures, no dysarthria.
- CVS: No chest pain, palpitations, or syncope.
- Resp: No shortness of breath, cough, or wheeze.
- GI: No nausea, vomiting, abdominal pain, or change in bowel habits.
- GU: No dysuria, haematuria, or incntinence.
- MSK: eports mild discomfort in the right hip area, no obvious swelling or deformity.
- Endocrine: No symptoms of hyperglycaemia or hypoglycaemia.

Past Medical History
- HTN
- OA
- TIA (2018)

Medications
Paracetamol 1g PRN every 6 hours for headache as prescribed in A&E.

Allergies
- Pollen

Social History
- Retired builder, lives alone in a bungalow.
- Independent with ADLs.
- Mobilises with a single walking stick due to OA affecting knees.
- Denies smoking or recreational drug use.
- Drinks aproximately 10 units of alcohol weekly (occasional beer).

Family History
- Father had a history of stroke in his 70s.
- Mother had HTN and osteoarthriti s.

On Examination
- Alert but mildly confused, disoriented to time (stated the incorrect year), oriented to place and person.
- Speech fluent, normal tone and volume.
- CNs intact.
- Power 5/5 in all muscle groups bilatreally.
- Sensation intact to light touch and pinprick in all limbs.
- Reflexes symmetrical in upper and lower limbs.
- Gait not assessed due to acute confusion.
- No scalp lacerations or haematomas observed.
- Mild tenderness over the right hip, no obvious swelling, deformity, or crepitus.
- Skin turgor slightly reduced; dry mucous membranes, indicating mild dehydration.
- No peripheral oedema or cyanosis.

Observations
HR 88
BP 160/95
RR 18
Temp 36.7
SpO2 96% on room air

Investigations
- T head: Subdural hygroma confirmed with no acute haemorrhage or mass effect.

Test Results
- Urea: 9.8 mmol/L
- All other blood test results within normal limits.

Impression
Subdural hygroma, mild dehydration, and acute confusion post minor fall. Suspected contributing factors include recent minor head trauma and possible suboptimal oral intake.

Plan
- Commence IV fluids: 0.9% sodium chloride 1L over 8 hours to address dehydration.
- Neudrological observations, including GCS monitooring and pupil responses.
- Monitor fluid input/output to assess hydration status.
- Repeat U&E tests in 24 hours.
- Prescribe paracetamol 1g PRN every 6 hours for headache as needed.
- Liaise with physio for mobility assessment when clinically appropriate.
- If confusion persists after rehydration, consider further cognitive assessment and liaise with psych if required.
- Reassess for any changes in neurological status; escalate to neurosurgery if indicated.


Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

================================================================================
Words: 537
Subject: Medical Clerking
Type: Medicine Inpatients

Clerking Doctor
Dr. Abdul Yaqoob (SpR)

Presenting Complaint
Acute confusion following minor fall.

History of Presenting Complaint
- Pt reports tripping over a loose rug at home yesterday evening (05/01/26) with a minor fall onto carpeted flooring, no LOC reported. - Initially felt wel but developed confusion later in the evening, described as difficulty recognising familiar objects and people. - No recol lection of the events leading to confusion. - Denies any vertigo, N&V, or CP. - Reports a mild R-sided headache that started after the fall, described as dull and persistent, rated 3/10 in severity, not worsening over time. - No limb weakness, visual disturbances, or incontinence reported.

Review of Systems
- CNS: Mild confusion, no focal neurological deficits, no seizures, no dysarthria.
- CVS: No chest pain, palpitations, or syncope.
- Resp: No shortness of breath, cough, or wheeze.
- GI: No nausea, vomiting, abdominal pain, or change in bowel habits.
- GU: No dysuria, haematuria, or incntinence.
- MSK: eports mild discomfort in the right hip area, no obvious swelling or deformity.
- Endocrine: No symptoms of hyperglycaemia or hypoglycaemia.

Past Medical History
- HTN
- OA
- TIA (2018)

Medications
Paracetamol 1g PRN every 6 hours for headache as prescribed in A&E.

Allergies
- Pollen

Social History
- Retired builder, lives alone in a bungalow.
- Independent with ADLs.
- Mobilises with a single walking stick due to OA affecting knees.
- Denies smoking or recreational drug use.
- Drinks aproximately 10 units of alcohol weekly (occasional beer).

Family History
- Father had a history of stroke in his 70s.
- Mother had HTN and osteoarthriti s.

On Examination
- Alert but mildly confused, disoriented to time (stated the incorrect year), oriented to place and person.
- Speech fluent, normal tone and volume.
- CNs intact.
- Power 5/5 in all muscle groups bilatreally.
- Sensation intact to light touch and pinprick in all limbs.
- Reflexes symmetrical in upper and lower limbs.
- Gait not assessed due to acute confusion.
- No scalp lacerations or haematomas observed.
- Mild tenderness over the right hip, no obvious swelling, deformity, or crepitus.
- Skin turgor slightly reduced; dry mucous membranes, indicating mild dehydration.
- No peripheral oedema or cyanosis.

Observations
HR 88
BP 160/95
RR 18
Temp 36.7
SpO2 96% on room air

Investigations
- T head: Subdural hygroma confirmed with no acute haemorrhage or mass effect.

Test Results
- Urea: 9.8 mmol/L
- All other blood test results within normal limits.

Impression
Subdural hygroma, mild dehydration, and acute confusion post minor fall. Suspected contributing factors include recent minor head trauma and possible suboptimal oral intake.

Plan
- Commence IV fluids: 0.9% sodium chloride 1L over 8 hours to address dehydration.
- Neudrological observations, including GCS monitooring and pupil responses.
- Monitor fluid input/output to assess hydration status.
- Repeat U&E tests in 24 hours.
- Prescribe paracetamol 1g PRN every 6 hours for headache as needed.
- Liaise with physio for mobility assessment when clinically appropriate.
- If confusion persists after rehydration, consider further cognitive assessment and liaise with psych if required.
- Reassess for any changes in neurological status; escalate to neurosurgery if indicated.


Dr. Abdul Yaqoob (Specialty Registrar)
GMC number: 1153326

================================================================================
Words: 523
Subject: Medical Clerking
Type: Medicine Inpatients

Clerking Doctor
Dr. Joanna Naomi Burgess (SpR)

Presenting Complaint
Acute confusion

History of Presenting Complaint
- Patient reported by her son, Edward Ali, to have been increasingly confused over the past 3 days.
- No history of head trauma or recent travel.
- Associated symptoms include reduced oral intake, decreased mobility, and lethargy.
- No reported hallucinations, visual changes, or seizures.
- No complaints of dysuria, urinary frequency, or visible haematuria as per sonâ€™s account.
- No chest pain, cough, or SOB noted prior to presentation.
- No history of vomiting or diarhoea.

Review of Systems
- Cardiovascular: No palpitations, chest pain, or syncope.
- Respiratory: No SOB or cough.
- Gastrointestinal: No abdominal pain, nausea, or vomiting. No changes in bowel habits.
- Genitourinary: No dysuria or visible haematuria. Reduced urinary output reported.
- Neurological: Acute confusion noted. No focal neuroklogical deficits (FND) reported by the son.
- Musculoskeletal: No recent falls or new joint pains.
- Dermatological: No rashes or skin changes.

Past Medical History
- HTN
- Osteoarthritis
- Cataract surgery (LE)

Medications
- None currently prescribed

Allergies
No known drug allergies

Social History
- Livesalone with support from her son, who visits daily.
- Mobilises with a frame indoors and uses a walking stick outdoors.
- Independent with most ADLs but requires assistance with shopping and heavier household tasks.
- Non-smoker and no alcohol consumption.
- No recreational drug use.

Family History
- No family history of dementia or neurological disorders.
- Father had IHD diagnosed in his 60s.
- Mother had OA.

On Examination
- Alert but disoriented to time, place, and person.
- Appears frail and dehydrated.
- Neurological: GCS 13/15 (E4, V4, M5). No focal neurological defiicts. Pupils equal and reactive to light. No limb weakness or tremors.
- Abdominal: Soft, non-tender, no organomegaly or palpable masses. No evidence of bladder distension.
- Hydration: Dry mucous membranes and reduced skin turgor.
- Musculoskeletal: Generalised joint stiffness consistent with known OA. No swelling or erythema in joints. Reduced mobility noted.
- General: No peripheral oedema. No obvious signs of infection such as rashes or erythema.

Observations
HR 112
BP 96/60
RR 18
Temp 38.8
SpO2 96% on room air

Investigations
- CXR: No focal consolidation or abnormalities detected.
- Awaiting urine C&S results.
- Bloods: Elevated CRP (120 mg/L). Creatinine 145 Âµmol/L, consistent with mild AKI.
- Urinalysis: Positive for leukocytes and nitrites, suggesting UTI.
- FBC: Mild leucocytosis.
- U&Es: Elevated urea and creatinine, borderline sodium levels.
- LFTs: Normal.
- Blood glucose: Normal.

Impression
Delirium likely secondary to UTI, with associated dehydration and mild AKI.

Plan
- Start IVceftriaxone 1g daily for suspected UTI as per ED decision.
- Transition to IV cefuroxime 750 mg TDS for continued treatment of UTI after admission.
- Commence IV 0.9% sodium chloride 1 litre over 8 hours for rehydration.
- Monitor renal function daily.
- Repeat urinalysis and send for C&S if required.
- Liaise with the geriatric team for further assessment and management of delirium.
- Mobilisation support with physiotherapy if needed.
- Encourage oral intake as tolerated.


Dr. Joanna Naomi Burgess (Specialty Registrar)
GMC number: 1346744

================================================================================
Words: 447
Subject: Medical Clerking
Type: Paediatric Respiratory Inpatients

Clerking Doctor
Dr. Anika Hossain (SpR)

Presenting Complaint
Wheeze

History of Presenting Complaint
- Lei Zhao reports a 3-day history of worsening wheeze and SOB.
- Symptoms began gradually and progressively worsened.
- Associated with increased coughing and a sensation of chest tightnewss.
- Symptoms developed shortly after contracting a cold with nasal congestion and sore throat.
- No associated fever, CP, or haemoptysis.
- No vomiting or abdominal pain.

Review of Systems
- Respiratory: Persistent wheeze, SOB, no haenoptysis or pleuritic chest pain.
- Cardiovascular: No palpitations, syncope, or chest pain.
- Gastrointestinal: No nausea, vomiting, abdo pain, or diarrhoea.
- Neurological: No headaches, dizziness, or focal neurologica l symptoms.
- Genitourinary: No dysuria, haematuria, or flank pain.
- ENT: Recent nasal congestion and sore throat, no ear pain or hearing loss.
- Musculoskeletal: No joint pain or swelling.
- Dermatological: No rashes or skin changes.

Past Medical History
- Asthma
- Seasonal allergies

Medications
None

Allergies
- Sulfonamides

Social History
- Lives with parents and attends secondary school.
- Independent with ADLs.
- Denies smoking, alcohol, or recreational drug use.
- Active lifestyle with regular participation in sports but unable to engage in physical actviity over the past 3 days due to symptoms.

Family History
- Mother has asthma.
- No known FH of other respiratory or chronic illnesses.

On Examination
- General appearance: Alert but in moderate respiratory distress, sitting upright in bed.
- Respiratory: Moderate use of accessory muscles, reduced chest expansion bilaterally, persistent expiratory wheeze on auscultation, no crackles, no signs of cyanosis. Peak flow measured at 180 L/min.
- ENT: Mild nasal congestion noted, oropharynx mildly erythematous with no exudates.
- CVS: Heart sounds norkal, no murmurs or added sounds.
- Abdomen: Soft, non-tender, no organomegaly.
- Neuro: Alert and oriented, no focal neurological deficits.

Observations
HR 96
BP 112/68
RR 24
Temp 36.8
SpO2 93% on 2L oxygen via nasal cannula

Investigations
- CXR requested to exclude infection or pneumothorax.
- ABG results from A&E: pH 7.32, PaO2 9.8 kPa, PaCO2 6.2 kPa, consistent with mild respiratory acidosis.

Test Results
- ABG: pH 7.32, mild respiratory acidosis.
- PEF: 180 L/min, indicating severe airway obstruction.

Impression
Acute exacerbation of asthma, likely triggered by a recent upper respiratory tract infection (URTI).

Plan
- Administer IV hydrocortisone 100 mg Q6H to manage acute asthma exacerbation and discontinu e oral prednisolone.
- Continue nebulised salbutamol 2.5 mg Q4H.
- Continue nebulised ipratropium bromide 500 mcg Q6H.
- Maintain oxygentherapy via nasal cannula to target SpO2 >94%.
- Perform CXR to exclude infection or pneumothorax.
- Monitor clinical response and reassess PEF and ABGs as indicated.


Dr. Anika Hossain (Specialty Registrar)
GMC number: 1812838

================================================================================
Words: 444
Subject: Pre-op Assessment
Type: Surgery Outpatients

Pre-clerking Doctor
Dr. Lewis Joe Lamb (FY1)

Presenting Complaint
Severe left hip pain due to end-stage OA.

Procedure
Total left hip replacement

History of Presenting Complaint
Site: L hip Onset: Gradual overthe past 4 yrs, progressively worsening Character: Deep, aching pain Radiates: Occasionally radiates to the L thigh Associations: Stiffness, reduced ROM, difficulty walking Timing: Constant pain, worse at night and after prolonged activity Exacerbating factors: Weight-bearing activities, prolonged standing or walking Severity: 8/10 at worst, 4/10 at best with analgesics

Past Medical History
- HTN
- Hyperlipidemia
- Mild osteopenia

Medications
- Paracetamol 500mg twice daily
- Ibuprofen 400mg as needed

Allergies
No known drug allergies

Social History
- Lives in a bungalow with her partner
- Independent in activities of daily living (ADLs) but uses a walking stick for mobility
- Non-smoker
- Drinks 6-8 units of alcohol per week
- No recreational drug use
- Retired school teacher
- Engages in light stretchnig exercises but has significantly reduced activity levels due to hip pain

Family History
- Mother had HTN and osteoarthritis
- Father had type 2 diabetes and HLD

On Examination
- Patient appeared comfortable at rest but had a slightly antalgic gait due to left hip pain
- CVS: Normal heart sounds, no murmurs, no peripheral oedema
- Resp: Clear breath sounds bilaterally, no wheeze or crackles
- Abdo: Soft, non-tender, no organomegaly, normal bowel sounds
- MSK: Left hip joint tender to palpation, reduced ROM (especially internaland external rotation), mild muscle wasting noted in the left thigh. No effusion or erythema
- Neruo: Normal tone, power 4/5 in left lower limb due to pain, normal reflexes, intact sensation in both lower limbs

Observations
HR 78
BP 145/90
RR 16
Temp 36.8
SpO2 98%

Investigations
- ECG: Normal sinus rhythm, no evidence of ischaemia or arrhythmia
- Urinalysis: Normal, no evidence of infection or other abnormalities
- Blood tests as part of routine pre-operative investigations revealed mild anaemia (Hb 10.8 g/dL). Other results including renal and liver function tests were within normal limits.

Test Results
- Bloods: Mild anaemia (Hb 10.8 g/dL), other results including renal and LFTs within normal limits
- Pending: None

Plan

In [4]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

In [5]:
import sys

sys.path.insert(0, str(PROJECT_ROOT))
notes = pd.read_csv(DATA_DIR / "raw" / "clinical_notes.csv")
print("Original notes:", len(notes))
print(notes.columns.tolist())
print("Notes:", notes.shape)

Original notes: 1602
['ingest_timestamp', 'clinical_note_id', 'clean_note_text', 'creation_timestamp', 'updt_dt_tm', 'note_subject', 'note_type', 'admission_id', 'person_id']
Notes: (1602, 9)

In [8]:
# ============================================================
# SELECT PILOT PATIENTS BY LONGITUDINAL RECORD SIZE
#
# Restrict selection to the longitudinal cohort:
# patients with >= 2 admissions and ground truth for both.
# ============================================================

# ============================================================
# RECORD SIZE PER PATIENT
# ============================================================

patient_sizes = (
    notes
    .groupby("person_id")
    .size()
    .reset_index(name="note_count")
    .sort_values("note_count")
    .reset_index(drop=True)
)

display(patient_sizes)

print("\nNote-count distribution:")
print(patient_sizes["note_count"].describe())

                               person_id  note_count
0   c87e610e-ac2a-48cf-ac32-054f3e595498          10
1   58b8aad6-7327-4450-956f-b775be0f4984          11
2   96766f3f-aa50-4bcb-abbf-884328049ea9          11
3   a8629d2e-7fd8-449a-9149-e0f5045a04c4          12
4   f97ee974-67f3-4d72-9ed4-f17025da3749          13
5   c54a9649-495a-4f89-a8ca-fbb14ba70ca6          14
6   900efb9a-fb57-4f25-b2a3-0a8c6f55b2d6          15
7   028998ee-babc-4096-9b28-001bc2f9a84e          15
8   0f438665-d430-4adb-8acc-c3beed9e4942          15
9   f1538231-21af-4cfa-8b40-3303aa0d0c96          15
10  fc6268ab-ad15-4613-9d8d-12c045e2fd46          16
11  b8085350-6748-47a5-a12f-6acd07c40a82          16
12  1dbe23dc-0d1e-431b-81eb-497282b46a14          17
13  c51243b8-e3d9-4cf7-ab29-0315048f91dc          17
14  29ea304f-821d-474e-81a1-394ca3945e02          17
15  973ee9d2-7c23-4e1d-afb2-86f679b55964          17
16  94264e23-ea67-496e-b027-5dd0cc334f1e          18
17  68258b8d-7d36-4d32-9093-6170a32bf087          18
18  28570119-9cdc-4120-98c0-4edb76cf36a3          19
19  e8885d7c-b863-4c41-997e-588416d655ae          19
20  5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb          20
21  ef943dfb-1368-44e0-a946-a0be360e1d54          20
22  ce0046dc-0ad3-4710-8147-549793c58b44          21
23  ebb1ca4c-f42f-41d8-adbc-1b08949036d1          22
24  f44d4a08-4c76-4000-ad61-d1d81032e643          24
25  420df33b-0072-4124-b1c6-0589daef3677          25
26  9d8fd25d-c4fe-4343-8ff5-5da5dad4e740          26
27  d362867a-d350-4aca-82d0-a63b7e0a14c7          27
28  1705dd0f-011a-492c-b006-b27e03f2f4ed          28
29  c332ce87-7afd-4a74-9896-3fef50179bd0          29
30  51f15281-8840-4fd0-92de-89188ab8d736          32
31  a9827c1c-fb54-4e5b-8bc6-d3099869e671          35
32  6e93f9d9-213d-4f2c-a1f0-f475dacef554          35
33  136c7916-4f9b-4e5c-bf01-77e9d2c681a2          37
34  0c04d9fb-d8d0-4ee0-8fc9-0c3f7f148bdf          38
35  8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc          44
36  61699d6d-904a-4ece-9026-cd61b3fd9a50          44
37  31f9612b-5a6b-48ea-887b-895772a83b99          46
38  05192757-942f-460d-b4ff-004ec39cc5ee          46
39  b70c7ff6-c2af-4df6-bd88-889bf767a168          50
40  42149ae1-6a3c-471e-a002-cb7263e8bb8c          50
41  37b5ce4d-dcfd-4bb7-bee4-d597eb114703          52
42  5e434d78-b2f6-4d88-b327-fff6ee50b901          54
43  c50e236f-6b3d-41c8-9e16-7ec343cac820          60
44  04df53ea-55c1-48d9-84a1-1f15c133b29b          66
45  ff8c4724-b7de-4189-bccf-cffddd4d6d44          66
46  359014a1-10e6-4bd8-9ba7-513d021c971e          68
47  69bf7e25-abb2-4dde-857f-f1138d4d0d8a          70
48  137b8481-4f1d-4b7f-babd-20f7117023ad          72
49  c6c45c39-cd73-49dd-818d-0a7865fe8a7f          90

Note-count distribution:
count    50.000000
mean     32.040000
std      19.973411
min      10.000000
25%      17.000000
50%      24.500000
75%      45.500000
max      90.000000
Name: note_count, dtype: float64

In [9]:
notes_clean = notes[
    notes["clean_note_text"]
    .astype(str)
    .str.strip()
    != "#NAME?"
].copy()

notes_dedup = (
    notes_clean
    .sort_values(
        ["person_id", "creation_timestamp"]
    )
    .drop_duplicates(
        subset=[
            "person_id",
            "clean_note_text"
        ],
        keep="first"
    )
    .reset_index(drop=True)
)

print("Raw notes:", len(notes))
print("After cleaning + deduplication:", len(notes_dedup))

Raw notes: 1602
After cleaning + deduplication: 1103

In [10]:
patient_sizes_dedup = (
    notes_dedup
    .groupby("person_id")
    .size()
    .reset_index(name="note_count")
    .sort_values("note_count")
    .reset_index(drop=True)
)

display(patient_sizes_dedup)

print("\nDeduplicated note-count distribution:")
print(
    patient_sizes_dedup["note_count"].describe()
)

                               person_id  note_count
0   ef943dfb-1368-44e0-a946-a0be360e1d54          10
1   c87e610e-ac2a-48cf-ac32-054f3e595498          10
2   96766f3f-aa50-4bcb-abbf-884328049ea9          11
3   58b8aad6-7327-4450-956f-b775be0f4984          11
4   f44d4a08-4c76-4000-ad61-d1d81032e643          12
5   a8629d2e-7fd8-449a-9149-e0f5045a04c4          12
6   f97ee974-67f3-4d72-9ed4-f17025da3749          13
7   1705dd0f-011a-492c-b006-b27e03f2f4ed          14
8   c54a9649-495a-4f89-a8ca-fbb14ba70ca6          14
9   028998ee-babc-4096-9b28-001bc2f9a84e          15
10  900efb9a-fb57-4f25-b2a3-0a8c6f55b2d6          15
11  f1538231-21af-4cfa-8b40-3303aa0d0c96          15
12  0f438665-d430-4adb-8acc-c3beed9e4942          15
13  fc6268ab-ad15-4613-9d8d-12c045e2fd46          16
14  b8085350-6748-47a5-a12f-6acd07c40a82          16
15  1dbe23dc-0d1e-431b-81eb-497282b46a14          17
16  c51243b8-e3d9-4cf7-ab29-0315048f91dc          17
17  973ee9d2-7c23-4e1d-afb2-86f679b55964          17
18  94264e23-ea67-496e-b027-5dd0cc334f1e          17
19  29ea304f-821d-474e-81a1-394ca3945e02          17
20  68258b8d-7d36-4d32-9093-6170a32bf087          18
21  e8885d7c-b863-4c41-997e-588416d655ae          19
22  28570119-9cdc-4120-98c0-4edb76cf36a3          19
23  0c04d9fb-d8d0-4ee0-8fc9-0c3f7f148bdf          19
24  5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb          20
25  ce0046dc-0ad3-4710-8147-549793c58b44          21
26  8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc          21
27  61699d6d-904a-4ece-9026-cd61b3fd9a50          22
28  31f9612b-5a6b-48ea-887b-895772a83b99          22
29  ebb1ca4c-f42f-41d8-adbc-1b08949036d1          22
30  05192757-942f-460d-b4ff-004ec39cc5ee          23
31  420df33b-0072-4124-b1c6-0589daef3677          24
32  b70c7ff6-c2af-4df6-bd88-889bf767a168          25
33  42149ae1-6a3c-471e-a002-cb7263e8bb8c          25
34  9d8fd25d-c4fe-4343-8ff5-5da5dad4e740          26
35  37b5ce4d-dcfd-4bb7-bee4-d597eb114703          26
36  5e434d78-b2f6-4d88-b327-fff6ee50b901          27
37  d362867a-d350-4aca-82d0-a63b7e0a14c7          27
38  c332ce87-7afd-4a74-9896-3fef50179bd0          29
39  c50e236f-6b3d-41c8-9e16-7ec343cac820          30
40  51f15281-8840-4fd0-92de-89188ab8d736          32
41  04df53ea-55c1-48d9-84a1-1f15c133b29b          33
42  ff8c4724-b7de-4189-bccf-cffddd4d6d44          33
43  359014a1-10e6-4bd8-9ba7-513d021c971e          34
44  6e93f9d9-213d-4f2c-a1f0-f475dacef554          34
45  69bf7e25-abb2-4dde-857f-f1138d4d0d8a          35
46  a9827c1c-fb54-4e5b-8bc6-d3099869e671          35
47  137b8481-4f1d-4b7f-babd-20f7117023ad          36
48  136c7916-4f9b-4e5c-bf01-77e9d2c681a2          37
49  c6c45c39-cd73-49dd-818d-0a7865fe8a7f          45

Deduplicated note-count distribution:
count    50.000000
mean     22.060000
std       8.471826
min      10.000000
25%      15.250000
50%      20.500000
75%      27.000000
max      45.000000
Name: note_count, dtype: float64

In [11]:
pilot_patients = {
    "short": "c87e610e-ac2a-48cf-ac32-054f3e595498",
    "medium": "ce0046dc-0ad3-4710-8147-549793c58b44",
    "long": "c6c45c39-cd73-49dd-818d-0a7865fe8a7f",
}

for case, patient_id in pilot_patients.items():
    n = len(
        notes_dedup[
            notes_dedup["person_id"] == patient_id
        ]
    )
    print(f"{case}: {patient_id} | {n} notes")

short: c87e610e-ac2a-48cf-ac32-054f3e595498 | 10 notes
medium: ce0046dc-0ad3-4710-8147-549793c58b44 | 21 notes
long: c6c45c39-cd73-49dd-818d-0a7865fe8a7f | 45 notes

In [12]:
# Short: 10 notes — c87e610e-ac2a-48cf-ac32-054f3e595498
# Medium: 21 notes — ce0046dc-0ad3-4710-8147-549793c58b44
# Long: 45 notes — c6c45c39-cd73-49dd-818d-0a7865fe8a7f